Repository wazuh/wazuh-documentation, pull requests merged in 2018-04, with the labels that each got.

#196 Updated and fixed Elasticsearch tuning guide
  source/installation-guide/optional-configurations/elastic-tuning.rst
Labels: enhancement

#204 Replaced Java install docs for Elastic on Debian
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
Labels: 3.2, bugfix

#206 Typo fix
  source/user-manual/agents/wazuh-app.rst
Labels: 3.2, typo

#205 Restore Java installation to previous guide
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
Labels: 3.2, bugfix

#208 Merging master branch into 3.2
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/user-manual/agents/agent-life-cycle.rst
Labels: 3.2, bugfix
