Repository wazuh/wazuh-documentation, pull requests merged in 2018-11, with the labels that each got.

#449 Fix global geoip config docs.
  source/user-manual/reference/ossec-conf/global.rst
Labels: community

#569 Add Remoted internal option "send_timeout"
  source/user-manual/reference/internal-options.rst
Labels: wazuh 3.7

#586 Update documentation for Elastic Stack v6.4.3
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/troubleshooting.rst
Labels: kibana app, update docs

#571 Add PEM, KEY options and some examples for registering an agent
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/user-manual/registering/use-registration-service.rst
Labels: update docs

#555 Several documentation improvements
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/user-manual/capabilities/policy-monitoring/openscap/oscap-configuration.rst
  source/user-manual/manager/manual-email-report/smtp_authentication.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/client.rst
  source/user-manual/reference/ossec-conf/index.rst
  source/user-manual/reference/ossec-conf/rootcheck.rst
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
  source/user-manual/reference/tools/update_ruleset.rst
  source/user-manual/ruleset/cdb-list.rst
  source/user-manual/ruleset/update.rst
Labels: typofix, update docs

#595 3.7 aix rpm
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/packages-list/index.rst
Labels: new docs, wazuh 3.7

#592 [3.7] Update documentation for Elastic Stack v6.4.3
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/release-notes/release_3_7_0.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/troubleshooting.rst
Labels: update docs

#596 [3.7] Checksums for release v3.7.0
  source/installation-guide/packages-list/index.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
Labels: wazuh 3.7

#600 [3.7] Update Wazuh Kibana app installation command
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/same_major.rst
Labels: update docs

#599 [3.6] Update Wazuh Kibana app installation command
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/same_major.rst
Labels: update docs

#598 AWS wodle image was updated
  source/images/aws/aws-create-firehose-14.png
Labels: images

#583 [3.0] Update version selector and tab titles
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#582 [3.1] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#581 [3.2] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#580 [3.3] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#579 [3.4] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#578 [3.5] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#577 [3.6] Update version selector and tab titles
  source/_static/my-script 2.js
  source/_static/my-script.js
  source/_templates/layout.html
  source/conf.py
Labels: docs core

#576 [3.7] Update documentation version selector
  source/_static/my-script 2.js
  source/_static/my-script.js
Labels: docs core

#574 Fixed API reference typo
  source/user-manual/api/reference.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: typofix

#593 Update and improve guide to create a custom WPK package
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/api/reference.rst
Labels: update docs

#597 Fix multiple grammar typos
  source/amazon/use-cases/s3.rst
  source/amazon/use-cases/vpc.rst
  source/deploying-with-ansible/guide/install-ansible.rst
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-elasticsearch.rst
  source/deploying-with-ansible/roles/wazuh-kibana.rst
  source/deploying-with-ansible/roles/wazuh-logstash.rst
  source/development/message-format.rst
  source/docker/wazuh-container.rst
  source/getting-started/use-cases.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/build-lab/install-windows-agent.rst
  source/learning-wazuh/build-lab/launch-ec2-instances.rst
  source/learning-wazuh/rdp-brute-force.rst
  source/learning-wazuh/shellshock.rst
  source/learning-wazuh/ssh-brute-force.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/migrating-from-ossec/index.rst
  source/release-notes/release_3_4_0.rst
  source/user-manual/agents/agent-life-cycle.rst
  source/user-manual/capabilities/auditing-whodata/who-linux.rst
  source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
  source/user-manual/capabilities/auditing-whodata/who-windows.rst
  source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/kibana-app/features/app-overview.rst
  source/user-manual/kibana-app/features/dev-tools.rst
  source/user-manual/overview.rst
  source/user-manual/reference/daemons/ossec-authd.rst
  source/user-manual/reference/daemons/wazuh-db.rst
  source/user-manual/reference/daemons/wazuh-modulesd.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/ossec-conf/global.rst
  source/user-manual/registering/registration-process.rst
  source/user-manual/registering/use-registration-service.rst
Labels: typofix

#607 Create requirements.txt
  requirements.txt
Labels: community, repository

#612 Change fim_migrate tool URL
  source/user-manual/reference/tools/fim_migrate.rst
Labels: update docs, wazuh 3.7

#610 Fix typo in certificate generation command
  source/installation-guide/optional-configurations/elastic_ssl.rst
  source/learning-wazuh/build-lab/install-elastic-stack.rst
Labels: typofix

#605 Updated Kibana app troubleshooting documentation
  source/user-manual/kibana-app/troubleshooting.rst
Labels: update docs

#611 Change steps order in several upgrading guides
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
Labels: update docs

#604 Update for FIM migration tool documentation
  source/user-manual/reference/tools/fim_migrate.rst
Labels: update docs

#603 Update API reference
  source/user-manual/api/reference.rst
  source/user-manual/kibana-app/features/query-configuration.rst
Labels: typofix

#608 Add timeout documentation for Authd
  source/user-manual/reference/internal-options.rst
Labels: update docs, wazuh 3.7

#615 Updating documentation favicon
  source/_static/favicon.ico
Labels: docs core

#618 Update Remote reference about queue_size usage
  source/user-manual/reference/ossec-conf/remote.rst
Labels: update docs

#621 Added more information about CIS-CAT and how to install Java
  source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst
Labels: update docs

#617 Added steps to disable unwanted Wazuh upgrades
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_deb.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
Labels: update docs

#619 Unify curl command usage
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/restore_alerts.rst
  source/learning-wazuh/build-lab/install-elastic-stack.rst
  source/release-notes/release_3_6_1.rst
  source/release-notes/release_3_7_0.rst
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/agents/restful-api/listing.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/queries.rst
  source/user-manual/api/reference.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/kibana-app/configure-xpack/configure-xpack-users.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/configure-xpack/xpack-troubleshooting.rst
  source/user-manual/kibana-app/troubleshooting.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/centralized-configuration.rst
Labels: review, update docs

#620 Changed ossec-control command with systemctl/service alternative
  source/amazon/installation.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/build-lab/install-linux-agents.rst
  source/learning-wazuh/build-lab/install-wazuh-server.rst
  source/learning-wazuh/hidden-processes.rst
  source/learning-wazuh/shellshock.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/learning-wazuh/vuln-detection.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/restful-api/register.rst
  source/user-manual/capabilities/policy-monitoring/openscap/oscap-configuration.rst
  source/user-manual/capabilities/system-calls-monitoring/audit-configuration.rst
  source/user-manual/capabilities/virustotal-scan/integration.rst
  source/user-manual/capabilities/vulnerability-detection.rst
  source/user-manual/manager/manual-integration.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/tools/ossec-control.rst
Labels: review, update docs

#624 Fix compilation warnings
  source/user-manual/api/queries.rst
Labels: bugfix

#626 Update documentation for Elastic Stack v6.5.0
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/troubleshooting.rst
Labels: kibana app, update docs

#647 Fix the typo in the option open attempts from logcollector in the internal options
  source/user-manual/reference/internal-options.rst
Labels: typofix

#636 Add description of API parameter "wait_for_complete"
  source/user-manual/api/getting-started.rst
Labels: update docs

#651 Fix typo in API reference
  source/user-manual/api/reference.rst
Labels: typofix

#622 New internal option remoted.guess_agent_group (#1864)
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/reference/internal-options.rst
Labels: wazuh TBA

#640 Change jsonout_output value according the changes in the code
  source/user-manual/reference/ossec-conf/global.rst
Labels: stalled, wazuh TBA

#648 New values for open attempts option in Logcollector section of the internal options
  source/user-manual/reference/internal-options.rst
Labels: wazuh TBA

#625 Describe options for audit keys for FIM
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: stalled, wazuh TBA

#655 Fix typo in The registration process
  source/user-manual/registering/registration-process.rst
Labels: typo

#662 Update agent_groups.rst
  source/user-manual/reference/tools/agent_groups.rst
Labels: update docs

#667 Update documentation for Elastic Stack 6.5.1
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/troubleshooting.rst
Labels: [app] kibana, [docs] update

#668 Update documentation for Splunk 7.2.1
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/packages-list/index.rst
  source/installing-splunk/splunk_installation.rst
  source/installing-splunk/splunk_wazuh.rst
Labels: [app] splunk, [docs] update

#635 Add description for new admin setting for Wazuh Kibana app
  source/user-manual/kibana-app/features/dev-tools.rst
  source/user-manual/kibana-app/reference/config-file.rst
Labels: [app] kibana, [docs] update

#638 Redesigned diagrams for Anti-flooding mechanism
  source/images/manual/internal-capabilities/bucket.png
  source/images/manual/internal-capabilities/graphic_with_flood.png
  source/images/manual/internal-capabilities/graphic_without_flooding.png
Labels: [docs] update, images

#663 Fix Integratord reference documentation for <event_location>
  source/user-manual/reference/ossec-conf/integration.rst
Labels: [docs] typo fix

#641 Update docker documentation
  source/docker/container-usage.rst
  source/docker/docker-installation.rst
  source/docker/faq-wazuh-container.rst
  source/docker/index.rst
  source/docker/wazuh-container.rst
Labels: [docs] update, [section] deployment

#661 Adding information about custom AR scripts
  source/user-manual/capabilities/active-response/remediation-faq.rst
Labels: [docs] update
