Repository wazuh/wazuh-documentation, pull requests merged in 2018-09, with the labels that each got.

#376 Adding case of use for recursion_level
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
Labels: [docs] new content

#371 Fix AR firewall-drop example
  source/user-manual/capabilities/active-response/remediation-configuration.rst
Labels: [docs] update, [release] 3.6

#370 Fix AWS configuration example
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: [docs] update, [release] 3.6

#378 Remove aws inspector from supported services
  source/amazon/index.rst
  source/amazon/installation.rst
  source/release-notes/release_3_6_0.rst
Labels: [docs] update

#381 Release notes for 3.6.1
  source/release-notes/release_3_6_1.rst
Labels: [release] 3.6

#387 Fixed wrong Kibana role name
  source/user-manual/kibana-app/configure-xpack/defining-xpack-users.rst
Labels: [app] kibana, [docs] typofix

#390 Add ova, ovf and vmdk links and checksums
  source/installation-guide/packages-list/index.rst
  source/installation-guide/virtual-machine.rst
Labels: [docs] update, [release] 3.6

#188 New AWS CloudTrail lab
  source/images/learning-wazuh/labs/cloudtrail-policy-assign.png
  source/images/learning-wazuh/labs/cloudtrail-policy-review.png
  source/images/learning-wazuh/labs/cloudtrail-results.png
  source/images/learning-wazuh/labs/create-trail.png
  source/images/learning-wazuh/labs/created-trail.png
  source/images/learning-wazuh/labs/vt-detect.png
  source/images/learning-wazuh/labs/vt-events.png
  source/images/learning-wazuh/labs/vt-newfile.png
  source/images/learning-wazuh/labs/vt-user-image-icon.png
  source/learning-wazuh/cloudtrail.rst
  source/learning-wazuh/index.rst
  source/learning-wazuh/virus-total.rst
  source/learning-wazuh/vuln-detection.rst
Labels: [docs] new content

#379 Update on deprecated options used by ossec-authd
  source/user-manual/registering/use-registration-service.rst
Labels: [docs] update

#398 Updated Splunk version to v7.1.3
  source/installing-splunk/splunk_installation.rst
  source/installing-splunk/splunk_wazuh.rst
  source/release-notes/release_3_6_1.rst
Labels: [app] splunk, [docs] update

#396 Fixed owner:group for some Kibana folders when upgrading
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/same_major.rst
Labels: [app] kibana, [docs] update

#409 Fix who-data typo
  source/user-manual/capabilities/auditing-whodata/who-linux.rst
Labels: [docs] typofix
