Repository wazuh/wazuh-documentation, pull requests merged in 2018-08, with the labels that each got.

#313 Updated Elastic version
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
Labels: [app] kibana

#281 Rename cluster client to worker
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/ossec-conf/cluster.rst
  source/user-manual/reference/tools/cluster_control.rst
Labels: [docs] update, [release] 3.4

#304 Adding documentation for max_depth option of syscheck
  source/user-manual/reference/internal-options.rst
Labels: [docs] new content

#330 Update API documentation
  source/user-manual/api/configuration.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/reference.rst
Labels: [docs] update

#333 Add internal option logcollector.sample_log_length
  source/user-manual/reference/internal-options.rst
Labels: [docs] new content

#277 Update rules syntax reference
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: [docs] update, [release] 3.5

#275 Add 'json_null_field' field to the decoder syntax documentation
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
Labels: [docs] new content, [release] 3.5

#305 Adding remove_old_diff documentation
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: [docs] new content, [release] 3.4

#319 Add ossquery documentation
  source/user-manual/capabilities/index.rst
  source/user-manual/capabilities/osquery.rst
  source/user-manual/reference/daemons/wazuh-modulesd.rst
  source/user-manual/reference/ossec-conf/index.rst
  source/user-manual/reference/ossec-conf/wodle-osquery.rst
Labels: [docs] new content

#332 Add Syscollector page at the capabilities section
  source/images/manual/devtools-syscollector.png
  source/images/manual/inventory.png
  source/user-manual/capabilities/index.rst
  source/user-manual/capabilities/syscollector.rst
Labels: [docs] new content

#320 Fix typos
  source/learning-wazuh/audit-commands.rst
  source/release-notes/release_3_2_0.rst
  source/user-manual/capabilities/file-integrity/index.rst
  source/user-manual/capabilities/policy-monitoring/openscap/how-it-works.rst
Labels: [docs] typofix, [docs] update

#340 Using the Kibana user
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
Labels: [app] kibana, [docs] update

#290 Unify
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/restore_alerts.rst
  source/learning-wazuh/vuln-detection.rst
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/agents/remote-upgrading/upgrading-agent.rst
  source/user-manual/agents/restful-api/listing.rst
  source/user-manual/agents/restful-api/register.rst
  source/user-manual/agents/restful-api/remove.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/reference.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/centralized-configuration.rst
Labels: [docs] update, stalled

#338 Add option -n to agent, syscheck and rootcheck control tools
  source/user-manual/reference/tools/agent_control.rst
  source/user-manual/reference/tools/rootcheck_control.rst
  source/user-manual/reference/tools/syscheck_control.rst
Labels: [docs] new content

#344 Syscheck tags documentation
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: [docs] new content

#323 Add checksum options to wodle command
  source/user-manual/reference/ossec-conf/wodle-command.rst
Labels: [docs] new content

#349 Adding statistics files documentation
  source/user-manual/reference/index.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/statistics-files.rst
Labels: [docs] new content

#356 Fixed order in X-Pack installation guide
  source/user-manual/kibana-app/configure-xpack/index.rst
Labels: [docs] typofix

#359 Update Elastic version to 6.4.0
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/kibana-app/configure-xpack/index.rst
  source/user-manual/kibana-app/troubleshooting.rst
Labels: [app] kibana, [docs] update

#351 Added shards and replicas configuration for wazuh-monitoring-3.x-*
  source/user-manual/kibana-app/reference/config-file.rst
Labels: [app] kibana, [docs] update

#365 3.6 logcollector parallelization
  source/user-manual/reference/daemons/ossec-logcollector.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: [docs] new content

#362 Update documentation for Wazuh 3.6.0
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-splunk/splunk_forwarder.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/command-line/remove.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/agents/restful-api/register.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/reference.rst
  source/user-manual/kibana-app/troubleshooting.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/tools/cluster_control.rst
Labels: [docs] update, [release] 3.6

#366 Several documentation fixes
  source/amazon/use-cases/index.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
  source/installation-guide/packages-list/index.rst
  source/user-manual/reference/daemons/wazuh-modulesd.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: [docs] typofix
