Repository wazuh/wazuh-documentation, pull requests merged in 2018-06, with the labels that each got.

#235 Add information about agent registration in cluster
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/registering/registration-process.rst
Labels: 3.2

#236 Update documentation for 3.2.4 release
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-splunk/splunk_installation.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/release-notes/index.rst
  source/release-notes/release_3_2_4.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/command-line/remove.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/manager/manual-integration.rst
Labels: 3.2, enhancement, update

#243 Update links and md5sum of wazuh packages
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-wazuh-agent/index.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/virtual-machine.rst
Labels: 3.2, enhancement

#253 New content for user manual documentation in 3.3
  source/user-manual/capabilities/log-data-collection/log-data-configuration.rst
  source/user-manual/reference/ossec-conf/active-response.rst
  source/user-manual/reference/ossec-conf/localfile.rst
  source/user-manual/ruleset/cdb-list.rst
  source/user-manual/ruleset/json-decoder.rst
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: 3.3

#255 Change active-response example to pass logtest
  source/user-manual/capabilities/active-response/how-it-works.rst
Labels: 3.3, bugfix

#256 Updated documentarion for v3.3.0 release
  source/conf.py
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-splunk/splunk_forwarder.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/virtual-machine.rst
  source/release-notes/index.rst
  source/release-notes/release_3_2_4.rst
  source/release-notes/release_3_3_0.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/command-line/remove.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/agents/restful-api/register.rst
  source/user-manual/ruleset/json-decoder.rst
Labels: 3.3, update

#257 Logcollector out format
  source/release-notes/release_3_3_0.rst
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: [release] 3.3

#260 Add option <ca_verification> to Active Reponse reference manual
  source/user-manual/reference/ossec-conf/active-response.rst
Labels: [docs] update, [release] 3.3

#263 Update documentation for 3.3.1 release
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/release-notes/index.rst
  source/release-notes/release_3_3_1.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/command-line/remove.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/api/reference.rst
Labels: [docs] update, [release] 3.3

#271 Update md5sums, links and installation pages for Solaris, AIX and HP-UX
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/packages-list/index.rst
Labels: [docs] new content, [release] 3.3

#267 Update documentation for 3.1.1_6.2.4
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/legacy/upgrading-elastic-stack.rst
Labels: [app] kibana, [docs] update, [release] 3.3

#272 Updated Elastic version to 6.3.0
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
Labels: [app] kibana, [docs] update
