Repository wazuh/wazuh-documentation, pull requests merged in 2018-07, with the labels that each got.

#273 Update Splunk installation for 3.3.1_7.1.1
  source/images/splunk-app/appconf-1.png
  source/images/splunk-app/appconf-2.png
  source/images/splunk-app/general.png
  source/installation-guide/installing-splunk/splunk_forwarder.rst
  source/installation-guide/installing-splunk/splunk_installation.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
Labels: [app] splunk, [docs] typofix, stalled

#295 Fix java curl
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/learning-wazuh/build-lab/install-elastic-stack.rst
Labels: [docs] bugfix, [release] 3.3

#293 Fix agent registration with Authd documentation
  source/user-manual/registering/use-registration-service.rst
Labels: [release] 3.3

#298 Add syscheck changes for release 3.4
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: [release] 3.4

#302 Add new internal options for 3.4
  source/user-manual/reference/internal-options.rst
Labels: [docs] new content, [release] 3.4

#294 Update API reference to 3.4
  source/user-manual/api/reference.rst
Labels: [release] 3.4

#306 Release notes version 3.4.0
  source/conf.py
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-splunk/splunk_forwarder.rst
  source/installation-guide/installing-splunk/splunk_installation.rst
  source/installation-guide/installing-splunk/splunk_wazuh.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/virtual-machine.rst
  source/release-notes/index.rst
  source/release-notes/release_3_4_0.rst
  source/user-manual/agents/command-line/register.rst
  source/user-manual/agents/command-line/remove.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/agents/restful-api/register.rst
  source/user-manual/registering/use-registration-service.rst
Labels: [docs] new content, [release] 3.4

#314 Fix packages version
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/packages-list/index.rst
Labels: [docs] bug, [release] 3.4

#231 Update vulnerability-detector documentation
  source/user-manual/capabilities/vulnerability-detection.rst
  source/user-manual/reference/ossec-conf/wodle-vuln-detector.rst
Labels: [docs] update

#229 Added new remoted and analysisd options
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: [docs] update
