Repository wazuh/wazuh-documentation, pull requests merged in 2018-10, with the labels that each got.

#413 Fix typo in ossec-conf/rootcheck documentation.
  source/user-manual/reference/ossec-conf/rootcheck.rst
Labels: community

#414 Fix typo in ossec-conf/syslog-output docs.
  source/user-manual/reference/ossec-conf/syslog-output.rst
Labels: community

#417 Label attribute "hidden" can be "no".
  source/user-manual/reference/ossec-conf/labels.rst
Labels: community

#419 Fix the ciscat wodle default java_path.
  source/user-manual/reference/ossec-conf/wodle-ciscat.rst
Labels: community

#421 Fix osquery "disabled" default.
  source/user-manual/reference/ossec-conf/wodle-osquery.rst
Labels: community

#423 Edit "check_winaudit" docs for consistency.
  source/user-manual/reference/ossec-conf/rootcheck.rst
Labels: community

#444 Correct command/timeout_allowed default.
  source/user-manual/reference/ossec-conf/commands.rst
Labels: community

#448 Document the "max_log" integration option.
  source/user-manual/reference/ossec-conf/integration.rst
Labels: community

#450 Document the global/helo_server option.
  source/user-manual/reference/ossec-conf/global.rst
Labels: community

#451 Fix global/memory_size default and limits.
  source/user-manual/reference/ossec-conf/global.rst
Labels: community

#452 Fix global/prelude_output default.
  source/user-manual/reference/ossec-conf/global.rst
Labels: community

#453 Document prelude_log_level and prelude_profile
  source/user-manual/reference/ossec-conf/global.rst
Labels: community

#415 Update osquery wodle docs to match example.
  source/user-manual/reference/ossec-conf/wodle-osquery.rst
Labels: community

#464 Adding wazuh db daemon doc
  source/user-manual/reference/daemons/index.rst
  source/user-manual/reference/daemons/wazuh-db.rst
Labels: new docs

#311 Disable the Elasticsearch updates by setting dpkg state
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
Labels: kibana app, stalled

#357 Replaces policycoreutils-python-utils dependency with policycoreutils
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
Labels: stalled, update docs

#388 Add underscore to \w character class, and less-than to escaped characters
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: update docs

#402 Add internal option wazuh.thread_stack_size
  source/user-manual/reference/internal-options.rst
Labels: new docs, stalled, wazuh 3.6

#412 Added compatibility matrix for Splunk app for Wazuh, this closes #406
  source/installation-guide/compatibility_matrix/index.rst
Labels: new docs, splunk app

#439 Update decoder_order_size to match source
  source/user-manual/reference/internal-options.rst
Labels: community

#442 Deprecate the unused alerts/use_geoip option.
  source/user-manual/reference/ossec-conf/alerts.rst
Labels: community

#445 Note email_alerts/format can be "default".
  source/user-manual/reference/ossec-conf/email_alerts.rst
Labels: community

#455 Deleted useless example in Kibana SSL guide
  source/installation-guide/optional-configurations/kibana_ssl.rst
Labels: kibana app

#458 Change wrong info about assign a group to an agent
  source/user-manual/agents/grouping-agents.rst
Labels: typofix

#465 fim_upgrade tool documentation
  source/user-manual/reference/tools/fim_migrate.rst
  source/user-manual/reference/tools/index.rst
Labels: new docs, ready to merge, wazuh 3.7

#437 Add multigroups documentation
  source/images/manual/multigroups.png
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/api/reference.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/tools/agent_groups.rst
Labels: new docs, ready to merge, wazuh 3.7

#456 Analysisd parallel
  source/images/manual/analysisd-alerts-queue-full.png
  source/images/manual/analysisd-flow-example.png
  source/images/manual/analysisd-structure.png
  source/images/manual/analysisd-syscheck-full.png
  source/user-manual/reference/daemons/ossec-analysisd.rst
  source/user-manual/reference/internal-options.rst
Labels: new docs, ready to merge, wazuh 3.7

#470 Add documentation for new API queries
  source/user-manual/api/index.rst
  source/user-manual/api/queries.rst
Labels: new docs, wazuh 3.7

#468 Update cluster documentation for distributed API
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/tools/cluster_control.rst
Labels: update docs, wazuh 3.7

#472 Update documentation for centralized configuration
  source/user-manual/reference/centralized-configuration.rst
Labels: update docs

#447 Note "email_to" option is required.
  source/user-manual/reference/ossec-conf/email_alerts.rst
Labels: community, stalled

#486 Change false default values to examples
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: typofix

#490 Fixed compilation warnings
  source/user-manual/reference/internal-options.rst
Labels: bugfix

#400 Ansible rework
  source/deploying-with-ansible/consider.rst
  source/deploying-with-ansible/guide/install-ansible.rst
  source/deploying-with-ansible/guide/install-elk-server.rst
  source/deploying-with-ansible/guide/install-wazuh-agent.rst
  source/deploying-with-ansible/guide/install-wazuh-server.rst
  source/deploying-with-ansible/index.rst
  source/deploying-with-ansible/install-ansible-control.rst
  source/deploying-with-ansible/installation-guide.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/images/ansible/ansible-agent.png
  source/images/ansible/ansible-agent2.png
  source/images/ansible/ansible-elk.png
Labels: wazuh 3.7

#488 Fix warning compilation on Azure reference
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
Labels: typofix

#491 Added ip.ignore option for the Wazuh app configuration file
  source/user-manual/kibana-app/reference/config-file.rst
Labels: kibana app, update docs

#463 Adding wazuh-db internal options description
  source/user-manual/reference/internal-options.rst
Labels: new docs, wazuh 3.7

#471 Adding information about wazuh-db tables
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/reference/daemons/wazuh-db.rst
Labels: new docs

#481 Adding note to update OVA
  source/installation-guide/virtual-machine.rst
Labels: update docs

#473 Add 3.7 release notes
  source/images/release-notes/kibana-remote-query.png
  source/release-notes/index.rst
  source/release-notes/release_3_7_0.rst
Labels: new docs, wazuh 3.7

#500 API documentation was generated
  source/user-manual/api/reference.rst
Labels: new docs, update docs, wazuh 3.7

#501 Added Kibana Query on demand documentation
  source/images/kibana-app/features/query-configuration/cluster.png
  source/images/kibana-app/features/query-configuration/configuration-section.png
  source/images/kibana-app/features/query-configuration/is-sync.png
  source/images/kibana-app/features/query-configuration/logcollector-json.png
  source/images/kibana-app/features/query-configuration/logcollector-query.png
  source/images/kibana-app/features/query-configuration/logcollector-xml.png
  source/images/kibana-app/features/query-configuration/manager.png
  source/images/kibana-app/features/query-configuration/tab-agent.png
  source/user-manual/api/index.rst
  source/user-manual/kibana-app/features/index.rst
  source/user-manual/kibana-app/features/query-configuration.rst
Labels: wazuh 3.7

#484 Move ossec-analysisd state file information to the correct section
  source/images/manual/analysisd-new-structure.png
  source/user-manual/reference/daemons/ossec-analysisd.rst
  source/user-manual/reference/index.rst
  source/user-manual/reference/statistics-files.rst
  source/user-manual/reference/statistics-files/index.rst
  source/user-manual/reference/statistics-files/ossec-agentd-state.rst
  source/user-manual/reference/statistics-files/ossec-analysisd-state.rst
  source/user-manual/reference/statistics-files/ossec-remoted-state.rst
Labels: update docs, wazuh 3.7

#502 Added more new features to release notes
  source/release-notes/release_3_7_0.rst
Labels: new docs, wazuh 3.7

#504 Fixed typo in Windows agent documentation
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
Labels: typofix

#515 Update remote config table
  source/user-manual/api/reference.rst
Labels: update docs, wazuh 3.7

#519 Fix oracle java cookie
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/learning-wazuh/build-lab/install-elastic-stack.rst
Labels: bugfix

#514 Several typo fixes and improvements for the documentation
  source/installation-guide/installing-elastic-stack/index.rst
  source/installation-guide/installing-wazuh-server/index.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm.rst
  source/installing-splunk/index.rst
  source/release-notes/release_3_7_0.rst
  source/user-manual/agents/grouping-agents.rst
Labels: typofix, update docs

#517 Update filtering data documentation
  source/user-manual/api/queries.rst
Labels: stalled, update docs, wazuh 3.7

#536 Update package checksums
  source/installation-guide/packages-list/index.rst
Labels: typofix

#526 Update Ruleset upgrading guide
  source/user-manual/ruleset/update.rst
Labels: typofix

#533 Add Wazuh apps for packages list
  source/installation-guide/packages-list/index.rst
Labels: kibana app, splunk app, update docs

#540 Update Syscheck reference
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: update docs, wazuh 3.7

#527 Updated Splunk guide with requirements warning
  source/installing-splunk/index.rst
  source/installing-splunk/splunk_wazuh.rst
Labels: splunk app, update docs

#543 Fixed external link not properly formatted
  source/user-manual/reference/ossec-conf/alerts.rst
Labels: typofix

#532 Improve cluster documentation for 3.7
  source/user-manual/api/reference.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/ossec-conf/email_alerts.rst
Labels: typofix, update docs, wazuh 3.7

#552 Added rlimit option to wazuh-db in internal options
  source/user-manual/reference/internal-options.rst
Labels: update docs, wazuh 3.7

#548 node filter was renamed to node_name
  source/user-manual/api/reference.rst
Labels: typofix, wazuh 3.7

#554 Update vulnerability-detector scan interval
  source/user-manual/capabilities/vulnerability-detection.rst
  source/user-manual/reference/ossec-conf/wodle-vuln-detector.rst
Labels: wazuh 3.7

#556 Add some information about the FIM migration script
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/user-manual/reference/tools/fim_migrate.rst
Labels: wazuh 3.7

#436 Fix to not recommend a 3rdparty PPA for recent Ubuntu/Debian versions
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
Labels: community

#547 Update documentation diagrams and 3.7.0 release notes
  source/_templates/layout.html
  source/conf.py
  source/development/message-format.rst
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/index.rst
  source/images/development/encryption_flow.png
  source/images/getting_started/agent_1024x1016.png
  source/images/getting_started/data_flow_2048x794.png
  source/images/getting_started/ossec_openscap_elastic_1024x445.png
  source/images/getting_started/server_1024x872.png
  source/images/getting_started/wazuh_agent_processes.png
  source/images/getting_started/wazuh_data_flow.png
  source/images/getting_started/wazuh_graphic_poc.png
  source/images/getting_started/wazuh_server_processes.png
  source/images/installation/installing_wazuh.png
  source/images/installation/installing_wazuh_distributed.png
  source/images/installation/installing_wazuh_singlehost.png
  source/images/manual/analysisd-alerts-queue-full.png
  source/images/manual/analysisd-diagram/analysisd-alerts-queue-full.png
  source/images/manual/analysisd-diagram/analysisd-flow-example.png
  source/images/manual/analysisd-diagram/analysisd-structure.png
  source/images/manual/analysisd-diagram/analysisd-syscheck-full.png
  source/images/manual/analysisd-flow-example.png
  source/images/manual/analysisd-new-structure.png
  source/images/manual/analysisd-structure.png
  source/images/manual/analysisd-syscheck-full.png
  source/images/manual/automatic-remediation/automatic-remediation.png
  source/images/manual/cluster/cluster_flow.png
  source/images/manual/cluster/cluster_infrastructure.png
  source/images/manual/cluster/introduction_cluster.png
  source/images/manual/command-monitoring/command-monitoring.png
  source/images/manual/fim/fim-flow.png
  source/images/manual/intrusion-anomaly/rootcheck-flow.png
  source/images/manual/log_analysis/log-analysis-flow.png
  source/images/manual/managing-agents/agent-status.png
  source/images/manual/policy-compliance/openscap-flow.png
  source/images/manual/policy-compliance/rootcheck-compliance.png
  source/images/release-notes/alert_docker_example.png
  source/images/release-notes/azure_integration_diagram.png
  source/installation-guide/index.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/release-notes/release_3_7_0.rst
  source/user-manual/agents/agent-life-cycle.rst
  source/user-manual/kibana-app/troubleshooting.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/daemons/ossec-analysisd.rst
Labels: update docs, wazuh 3.7

#558 Add documentation of FIM new features for 3.7 release and fix some er…
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/capabilities/file-integrity/fim-faq.rst
  source/user-manual/capabilities/file-integrity/how-it-works.rst
  source/user-manual/reference/tools/index.rst
  source/user-manual/reference/tools/syscheck_control.rst
  source/user-manual/reference/tools/syscheck_update.rst
Labels: new docs

#566 Change documentation background to pure white
  source/_static/my-styles.css
Labels: update docs
