Repository wazuh/wazuh-documentation, pull requests merged in 2019-11, with the labels that each got.

#2002 Improve AWS Config documentation
  source/amazon/services/config.rst
  source/images/aws/aws-create-config-1.png
Labels: enhancement

#1996 Documentation for integration with Cisco Umbrella
  source/amazon/services/index.rst
  source/amazon/services/supported-services/cisco-umbrella.rst
  source/amazon/services/supported-services/config.rst
  source/amazon/services/supported-services/index.rst
  source/amazon/services/troubleshooting.rst
Labels: new-docs

#2044 Updated the version of the documentation corresponding to this release
  source/_static/js/version-selector.js
  source/conf.py
Labels: bug

#2043 [3.11] Fixed wrong path in one of the thumbnails
  source/amazon/services/supported-services/config.rst
Labels: bug

#2031 [3.11] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2029 [3.10] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2030 [3.12] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2032 [3.9] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2033 [3.8] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2034 [3.7] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2035 [3.6] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2036 [3.5] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2037 [3.4] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2038 [3.3] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2039 [3.2] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2040 [3.1] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2041 [3.0] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2042 [2.1] Fixed code that excludes 'Release notes' from search results
  source/_static/js/style.js
Labels: bug

#2006 [3.10] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2020 [2.1] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2019 [3.0] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2018 [3.1] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2017 [3.2] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2016 [3.3] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2015 [3.4] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2014 [3.5] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2013 [3.6] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2012 [3.7] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2011 [3.8] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2010 [3.9] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2009 [3.12] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2008 [3.11] Fixed the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2000 Indicate package compatibility with macOS Catalina
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/installing-wazuh-agent/macos/wazuh_agent_package_macos.rst
Labels: enhancement

#2048 [3.10] Fixed some bugs occurring only on Internet Explorer
  source/_static/css/style.css
  source/_static/js/style.js
Labels: bug

#2051 Typo found
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: typo

#2077 Add json_escaped_log parameter to Localfile output format
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: enhancement

#2080 Modify Osquery's Windows path
  source/user-manual/reference/ossec-conf/wodle-osquery.rst
Labels: enhancement

#2079 Add poll_interval and keepalive options to Fluent Forward module
  source/user-manual/reference/ossec-conf/fluent-forward.rst
Labels: enhancement

#2082 [3.11] Replace Docker base image for python:3.7-alpine
  Dockerfile
Labels: bug
