Repository wazuh/wazuh-documentation, pull requests merged in 2019-02, with the labels that each got.

#885 Clarify 3.8.2 release notes
  source/release-notes/release_2_1.rst
  source/release-notes/release_3_0_0.rst
  source/release-notes/release_3_1_0.rst
  source/release-notes/release_3_2_0.rst
  source/release-notes/release_3_2_1.rst
  source/release-notes/release_3_2_2.rst
  source/release-notes/release_3_2_3.rst
  source/release-notes/release_3_2_4.rst
  source/release-notes/release_3_3_0.rst
  source/release-notes/release_3_3_1.rst
  source/release-notes/release_3_4_0.rst
  source/release-notes/release_3_5_0.rst
  source/release-notes/release_3_6_0.rst
  source/release-notes/release_3_6_1.rst
  source/release-notes/release_3_7_0.rst
  source/release-notes/release_3_7_1.rst
  source/release-notes/release_3_7_2.rst
  source/release-notes/release_3_8_0.rst
  source/release-notes/release_3_8_1.rst
  source/release-notes/release_3_8_2.rst
Labels: enhancement

#905 Reference documentation for the network buffer related features in Remoted
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/statistics-files/ossec-remoted-state.rst
Labels: enhancement

#930 Fixed typo
  source/user-manual/overview.rst
Labels: Pending merge

#931 Add allowed interval to chunk option
  source/user-manual/reference/tools/agent_upgrade.rst
Labels: Pending merge

#928 Add information about system labels
  source/user-manual/reference/ossec-conf/labels.rst
Labels: Pending merge

#914 Added small changes to improve docker monitoring doc
  source/docker-monitor/monitoring_containers_activity.rst
Labels: Pending merge

#915 Added more info about SSL verification
  source/images/manual/managing-agents/SSLregister1.png
  source/images/manual/managing-agents/SSLregister2.png
  source/user-manual/registering/use-registration-service.rst
Labels: Pending merge

#935 New documentation to use the Syscollector information to generate alerts.
  source/images/manual/internal-capabilities/syscollector_alerts.png
  source/user-manual/capabilities/syscollector.rst
Labels: Pending merge

#925 Added agent modules with new antiflooding configurations
  source/user-manual/capabilities/antiflooding.rst
Labels: pending review

#937 Update AWS configuration
  source/amazon/configuration/considerations.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: enhancement

#941 Fix error in GuardDuty configuration (AWS)
  source/amazon/services/guardduty.rst
Labels: bug

#943 Fixed integration.rst
  source/user-manual/reference/ossec-conf/integration.rst
Labels: Pending merge

#949 Specified options for <expect> in commands.rst
  source/user-manual/reference/ossec-conf/commands.rst
Labels: Pending merge

#946 Update Docker Listener module settings reference
  source/user-manual/reference/ossec-conf/wodle-docker.rst
Labels: pending review

#889 Added new features and reworked statistical files.
  source/user-manual/reference/statistics-files/index.rst
  source/user-manual/reference/statistics-files/ossec-agentd-state.rst
  source/user-manual/reference/statistics-files/ossec-analysisd-state.rst
  source/user-manual/reference/statistics-files/ossec-remoted-state.rst
Labels: Pending merge

#952 Add install / update examples for wazuhapp without having sudo installed
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/same_major.rst
Labels: pending review

#953 Bump splunk version
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/packages-list/index.rst
  source/installing-splunk/index.rst
  source/installing-splunk/splunk-app.rst
  source/installing-splunk/splunk-basic.rst
  source/installing-splunk/splunk-distributed.rst
  source/installing-splunk/splunk-forwarder.rst
  source/installing-splunk/splunk-polling.rst
Labels: Pending merge
