Repository wazuh/wazuh-documentation, pull requests merged in 2019-10, with the labels that each got.

#1783 Correct typo (in order to knows → in order to know)
  source/user-manual/reference/ossec-conf/commands.rst
Labels: operations

#1786 Correct typo in decoders syntax documentation
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
Labels: invalid

#1891 Fix example for removing agents.
  source/user-manual/agents/remove-agents/restful-api-remove.rst
Labels: bug

#1888 [2.1] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1887 [3.0] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1886 [3.1] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1885 [3.2] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1884 [3.3] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1883 [3.4] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1882 [3.5] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1881 [3.6] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1880 [3.7] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1879 [3.8] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1878 [3.9] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1821 [3.10] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1877 [3.11] Avoid the unnecessary rebuilding of the minified files
  source/conf.py
Labels: bug

#1589 Add RPM generation documentation
  source/packaging/generate-rpm-package.rst
Labels: enhancement, packages

#1858 Add OSX generation documentation
  source/packaging/generate-osx-package.rst
Labels: enhancement, packages

#1608 Add HPUX generation documentation
  source/packaging/generate-hpux-package.rst
Labels: enhancement, packages

#1594 Add AIX generation documentation
  source/packaging/generate-aix-package.rst
Labels: enhancement, packages

#1593 Add Solaris generation documentation
  source/packaging/generate-sol-package.rst
Labels: enhancement, packages

#1592 Add DEB generation documentation
  source/packaging/generate-deb-package.rst
Labels: enhancement, packages

#1913 Updated all references to 6.8.2 to 6.8.3
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_hard_upgrade.rst
Labels: operations

#1909 Added a correct way to execute certutil
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: enhancement, operations

#1902 Update template
  source/user-manual/kibana-app/reference/configure-indices.rst
Labels: operations

#1931 Forced min-width for sidebar buttons
  source/_static/css/style.css
Labels: design

#1916 Update API reference ('condition' field in a SCA endpoint)
  source/user-manual/api/reference.rst
Labels: enhancement

#1964 [3.11] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1965 [3.10] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1966 [3.9] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1967 [3.8] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1968 [3.7] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1970 [3.6] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1971 [3.5] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1973 [3.3] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1974 [3.2] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1976 [3.0] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1977 [2.1] Fixed error in the minification process during compilation
  source/conf.py
Labels: bug

#1963 Fix typo and remove parentheses
  source/user-manual/capabilities/sec-config-assessment/how_it_works.rst
Labels: typo

#1949 Correct a couple of typos in Splunk documentation.
  source/installation-guide/installing-splunk/splunk-distributed.rst
Labels: typo

#1946 X pack settings
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: bug, operations

#1388 Update documentation to include windows
  source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst
Labels: operations

#1989 Minor fixes to the Docker installation documentation.
  source/docker/docker-installation.rst
  source/docker/wazuh-container.rst
Labels: enhancement, operations

#1991 Next steps indication after Wazuh upgrade.
  source/upgrade-guide/upgrading/latest_wazuh3_minor.rst
Labels: enhancement, operations

#1990 Remote agent upgrade mention within the Wazuh upgrade section.
  source/upgrade-guide/upgrading/latest_wazuh3_minor.rst
Labels: enhancement, operations

#1983 Improve AWS documentation
  source/amazon/configuration/considerations.rst
  source/amazon/configuration/index.rst
  source/amazon/index.rst
  source/amazon/services/index.rst
  source/amazon/services/prerequisites/S3-bucket.rst
  source/amazon/services/prerequisites/considerations.rst
  source/amazon/services/prerequisites/credentials.rst
  source/amazon/services/prerequisites/dependencies.rst
  source/amazon/services/prerequisites/index.rst
  source/amazon/services/supported-services/cloudtrail.rst
  source/amazon/services/supported-services/config.rst
  source/amazon/services/supported-services/guardduty.rst
  source/amazon/services/supported-services/index.rst
  source/amazon/services/supported-services/inspector.rst
  source/amazon/services/supported-services/kms.rst
  source/amazon/services/supported-services/macie.rst
  source/amazon/services/supported-services/trusted-advisor.rst
  source/amazon/services/supported-services/vpc.rst
  source/amazon/services/troubleshooting.rst
  source/amazon/troubleshooting.rst
Labels: enhancement
