Repository wazuh/wazuh-documentation, pull requests merged in 2019-06, with the labels that each got.

#1248 minor fixes to the OSQuery capability
  source/user-manual/capabilities/osquery.rst
Labels: operations

#1244 Docker listener docu fixes
  source/docker-monitor/monitoring_containers_activity.rst
  source/user-manual/reference/ossec-conf/index.rst
Labels: operations

#1251 Update documentation for auth parameters
  source/user-manual/reference/ossec-conf/auth.rst
Labels: bug

#1272 Delete `wazuh-api must be restarted after deleting agents`
  source/user-manual/api/reference.rst
Labels: operations

#1266 Restart Kibana after setting elastic user
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: operations

#1211 Modified the explanation about how to change api's username
  source/installation-guide/installing-wazuh-server/securing_api.rst
Labels: operations

#1279 Replaced version selector with a dropdown menu
  source/_static/css/style.css
  source/_static/js/my-script.js
  source/_static/js/popper.min.js
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/versions.html
Labels: new-design

#1282 Changes based on the feedback from June 7th
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: new-design

#1287 Update documentation for installing Wazuh API on Fedora 30.
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_fedora.rst
Labels: enhancement

#1278 Fix some documentation grammatical errors
  source/user-manual/capabilities/antiflooding.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
Labels: operations

#1280 Custom external integration info
  source/user-manual/manager/manual-integration.rst
  source/user-manual/reference/ossec-conf/integration.rst
Labels: missing-docs

#1292 Bump Wazuh 3.9.2, Elastic 7.1.1
  source/docker/container-usage.rst
  source/docker/faq-wazuh-container.rst
  source/docker/index.rst
  source/docker/wazuh-container.rst
Labels: docker, operations

#1281 Inserting references to blog on documentation
  source/getting-started/architecture.rst
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/capabilities/command-monitoring/how-it-works.rst
  source/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.rst
  source/user-manual/kibana-app/index.rst
Labels: new-docs

#1274 Build clean notice between compilations on different platforms
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
Labels: missing-docs
