Repository wazuh/wazuh-documentation, pull requests merged in 2019-05, with the labels that each got.

#1185 Fix 3.9 compatibility matrix.
  source/installation-guide/compatibility_matrix/index.rst
Labels: enhancement

#1176 Restructure the documentation about registering agents
  source/deploying-with-kubernetes/kubernetes-conf.rst
  source/installation-guide/installing-wazuh-agent/automated_deployment_variables.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_deb.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_rpm.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/user-manual/agents/agent-life-cycle.rst
  source/user-manual/agents/index.rst
  source/user-manual/agents/registering/index.rst
  source/user-manual/agents/registering/restful-api-register.rst
  source/user-manual/agents/registering/use-registration-service.rst
  source/user-manual/agents/registering/using-command-line.rst
  source/user-manual/index.rst
  source/user-manual/registering/api/api-register-linux-unix.rst
  source/user-manual/registering/api/api-register-macos.rst
  source/user-manual/registering/api/api-register-windows.rst
  source/user-manual/registering/cli/using-command-line-linux.rst
  source/user-manual/registering/cli/using-command-line-macos.rst
  source/user-manual/registering/cli/using-command-line-unix.rst
  source/user-manual/registering/cli/using-command-line-windows.rst
  source/user-manual/registering/index.rst
  source/user-manual/registering/linux-unix-simple-registration.rst
  source/user-manual/registering/macos-simple-registration.rst
  source/user-manual/registering/manager-verification/agent-verification-registration.rst
  source/user-manual/registering/manager-verification/agents/linux-unix-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/linux-unix-manager-verification.rst
  source/user-manual/registering/manager-verification/agents/macos-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/macos-manager-verification.rst
  source/user-manual/registering/manager-verification/agents/windows-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/windows-manager-verification.rst
  source/user-manual/registering/manager-verification/host-verification-registration.rst
  source/user-manual/registering/manager-verification/manager-verification-registration.rst
  source/user-manual/registering/password-authorization-registration-service.rst
  source/user-manual/registering/password/linux-unix-password-registration.rst
  source/user-manual/registering/password/macos-password-registration.rst
  source/user-manual/registering/password/windows-password-registration.rst
  source/user-manual/registering/registration-process.rst
  source/user-manual/registering/restful-api-register.rst
  source/user-manual/registering/simple-registration-method.rst
  source/user-manual/registering/using-command-line.rst
  source/user-manual/registering/windows-simple-registration.rst
Labels: enhancement, new-docs

#1209 Unattended installation ca store n option
  source/user-manual/reference/unattended-installation.rst
Labels: operations

#1218 Updated Checksums
  source/installation-guide/packages-list/index.rst
Labels: operations

#1219 Fixed rule regex option explanation
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: operations

#1227 Update active configuration tables (API reference)
  source/user-manual/api/reference.rst
Labels: new-docs

#1228 Reviewed documentation of the SCA module for better readability
  source/user-manual/capabilities/sec-config-assessment/how-it-works.rst
  source/user-manual/capabilities/sec-config-assessment/index.rst
  source/user-manual/capabilities/sec-config-assessment/security-configuration-assessment.rst
  source/user-manual/capabilities/sec-config-assessment/use-case.rst
Labels: operations

#1240 Minor fixes to X-Pack security docs
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: elastic, operations

#1243 Update API documentation for 3.9.2
  source/user-manual/api/reference.rst
Labels: enhancement
