Repository wazuh/wazuh-documentation, pull requests merged in 2019-08, with the labels that each got.

#1382 Add <email_log_source> option in ossec.conf <global>
  source/user-manual/reference/ossec-conf/global.rst
Labels: missing-docs

#1397 Added optional step for disabling Elastic repo
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_amazon.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_centos.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_fedora.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_oracle.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_rhel.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_suse_opensuse.rst
Labels: enhancement

#1400 Correct typo in "command" wodle documentation
  source/user-manual/reference/ossec-conf/wodle-command.rst
Labels: invalid

#1393 Added # to setting up Ansible code for Debian
  source/deploying-with-ansible/guide/install-ansible.rst
Labels: enhancement

#1302 Add a way to unzip certs.zip
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: missing-docs

#1411 Bump version to Wazuh 3.9.5 and Elastic 7.3.0
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-elastic-stack/elastic_tuning.rst
  source/installation-guide/installing-elastic-stack/transform_logstash.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables_windows.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_aix.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_hpux.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_macos.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_sources.rst
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
  source/installation-guide/installing-wazuh-server/sources_installation.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_deb.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_amazon.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_centos.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_fedora.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_oracle.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_rhel.rst
  source/installation-guide/installing-wazuh-server/wazuh_server_rpm_suse_opensuse.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading-elastic-stack/elastic_server_hard_upgrade.rst
  source/installation-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
  source/installation-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/upgrading/latest_wazuh3_minor.rst
  source/installation-guide/upgrading/same_major.rst
  source/installation-guide/upgrading/same_minor.rst
  source/installation-guide/virtual-machine.rst
  source/installing-splunk/splunk-app.rst
  source/installing-splunk/splunk-forwarder.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
  source/user-manual/agents/remove-agents/remove.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/reference.rst
  source/user-manual/kibana-app/reference/configure-indices.rst
  source/user-manual/kibana-app/troubleshooting.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/tools/cluster_control.rst
Labels: enhancement

#1329 Made steps order X-pack security cluster compatible
  source/installation-guide/installing-elastic-stack/protect-installation/xpack.rst
Labels: operations

#1417 1416 Cache docu bugfix
  source/user-manual/api/reference.rst
Labels: bug

#1399 Changes to FIM training documentation
  source/learning-wazuh/detect-fs-changes.rst
Labels: operations

#1429 Fixed visual bug caused by wrong tabulation
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
Labels: bug, operations

#1453 [Design] Fixed style of highlighted string (3.9)
  source/_static/css/style.css
Labels: new-design

#1464 [Design] Fixed style of highlighted string (3.8)
  source/_static/css/style.css
Labels: new-design

#1465 [Design] Fixed style of highlighted string (3.7)
  source/_static/css/style.css
Labels: new-design

#1466 [Design] Fixed style of highlighted string (3.6)
  source/_static/css/style.css
Labels: new-design

#1467 [Design] Fixed style of highlighted string (3.5)
  source/_static/css/style.css
Labels: new-design

#1468 [Design] Fixed style of highlighted string (3.4)
  source/_static/css/style.css
Labels: new-design

#1469 [Design] Fixed style of highlighted string (3.3)
  source/_static/css/style.css
Labels: new-design

#1470 [Design] Fixed style of highlighted string (3.2)
  source/_static/css/style.css
Labels: new-design

#1471 [Design] Fixed style of highlighted string (3.1)
  source/_static/css/style.css
Labels: new-design

#1472 [Design] Fixed style of highlighted string (3.0)
  source/_static/css/style.css
Labels: new-design

#1473 [Design] Fixed style of highlighted string (2.1)
  source/_static/css/style.css
Labels: new-design

#1463 [Design] Javascript code linted (2.1)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1462 [Design] Javascript code linted (3.0)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1461 [Design] Javascript code linted (3.1)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1460 [Design] Javascript code linted (3.2)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1459 [Design] Javascript code linted (3.3)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1458 [Design] Javascript code linted (3.4)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1457 [Design] Javascript code linted (3.5)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1456 [Design] Javascript code linted (3.6)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1455 [Design] Javascript code linted (3.7)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1454 [Design] Javascript code linted (3.8)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1450 [Design] Javascript code linted (3.9)
  .gitignore
  source/_static/js/style.js
  source/_static/js/version-selector.js
Labels: new-design

#1476 Added documentation for multizone installation in Solaris 11
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
Labels: packages

#1475 [3.9] Fixed some broken links in rst files
  source/deploying-with-kubernetes/kubernetes-conf.rst
  source/installation-guide/installing-elastic-stack/elastic_tuning.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
  source/user-manual/reference/ossec-conf/agentless.rst
Labels: bug

#1489 [3.8] Fixed some broken links in rst files
  source/installation-guide/installing-elastic-stack/elastic_tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
  source/user-manual/reference/ossec-conf/agentless.rst
Labels: bug

#1490 [3.7] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
  source/user-manual/reference/ossec-conf/agentless.rst
Labels: bug

#1491 [3.6] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1492 Version on the conf.py changed to 3.1
  source/conf.py
Labels: design

#1493 Version on the conf.py changed to 3.0
  source/conf.py
Labels: design

#1487 Sticky menu fixed (3.0)
  source/_static/css/style.css
Labels: design

#1488 Sticky menu fixed (2.1)
  source/_static/css/style.css
Labels: design

#1486 Sticky menu fixed (3.1)
  source/_static/css/style.css
Labels: design

#1485 Sticky menu fixed (3.2)
  source/_static/css/style.css
Labels: design

#1494 [3.5] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/kibana-app/reference/elasticsearch.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1495 [3.4] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1496 [3.3] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1497 [3.2] Fixed some broken links in rst files
  source/installation-guide/installing-splunk/splunk_installation.rst
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1484 Sticky menu fixed (3.3)
  source/_static/css/style.css
Labels: design

#1483 Sticky menu fixed (3.4)
  source/_static/css/style.css
Labels: design

#1482 Sticky menu fixed (3.5)
  source/_static/css/style.css
Labels: design

#1481 Sticky menu fixed (3.6)
  source/_static/css/style.css
Labels: design

#1480 Sticky menu fixed (3.8)
  source/_static/css/style.css
Labels: design

#1477 Sticky menu fixed (3.7)
  source/_static/css/style.css
Labels: design

#1479 Sticky menu fixed (3.9)
  source/_static/css/style.css
Labels: design

#1498 [3.1] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1407 Added guide for creating custom dashboards
  source/images/kibana-app/custom-dashboard/add-visualization-to-dashboard.png
  source/images/kibana-app/custom-dashboard/bucket-apply-changes.png
  source/images/kibana-app/custom-dashboard/bucket-select-an-aggregation-terms.png
  source/images/kibana-app/custom-dashboard/bucket-term-field.png
  source/images/kibana-app/custom-dashboard/bucket-x-axis.png
  source/images/kibana-app/custom-dashboard/choose-a-source.png
  source/images/kibana-app/custom-dashboard/complex-dashboard.png
  source/images/kibana-app/custom-dashboard/confirm-save-dashboard.png
  source/images/kibana-app/custom-dashboard/confirm-save-visualization.png
  source/images/kibana-app/custom-dashboard/create-new-dashboard.png
  source/images/kibana-app/custom-dashboard/create-new-visualization.png
  source/images/kibana-app/custom-dashboard/dashboard-tab.png
  source/images/kibana-app/custom-dashboard/horizontal-example-chart.png
  source/images/kibana-app/custom-dashboard/indices-healthcheck.png
  source/images/kibana-app/custom-dashboard/metrics-and-buckets.png
  source/images/kibana-app/custom-dashboard/panel-was-properly-added.png
  source/images/kibana-app/custom-dashboard/save-dashboard.png
  source/images/kibana-app/custom-dashboard/save-visualization.png
  source/images/kibana-app/custom-dashboard/select-lapse-time.png
  source/images/kibana-app/custom-dashboard/select-panels-to-add.png
  source/images/kibana-app/custom-dashboard/select-visualization-type.png
  source/images/kibana-app/custom-dashboard/visualize-tab.png
  source/user-manual/kibana-app/reference/custom-dashboard.rst
  source/user-manual/kibana-app/reference/index.rst
Labels: enhancement, operations

#1514 [3.6] Fixed table in page util.sh
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1512 [2.1] Fixed some broken links in rst files
  source/installation-guide/virtual-machine.rst
  source/user-manual/capabilities/agentless-monitoring/how-it-works.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1511 [3.0] Fixed some broken links in rst files
  source/installation-guide/optional-configurations/elastic-tuning.rst
  source/installation-guide/packages-list/index.rst
  source/installation-guide/upgrading/different_major.rst
  source/installation-guide/virtual-machine.rst
  source/user-manual/capabilities/agentless-monitoring/how-it-works.rst
  source/user-manual/reference/ossec-conf/agentless.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/ruleset/getting-started.rst
Labels: bug

#1500 Cache problem solved (2.1)
  source/conf.py
Labels: design

#1501 Cache problem solved (3.0)
  source/conf.py
Labels: design

#1502 Cache problem solved (3.1)
  source/conf.py
Labels: design

#1503 Cache problem solved (3.2)
  source/conf.py
Labels: design

#1504 Cache problem solved (3.3)
  source/conf.py
Labels: design

#1505 Cache problem solved (3.4)
  source/conf.py
Labels: design

#1506 Cache problem solved (3.5)
  source/conf.py
Labels: design

#1507 Cache problem solved (3.6)
  source/conf.py
Labels: design

#1508 Cache problem solved (3.7)
  source/conf.py
Labels: design

#1509 Cache problem solved (3.8)
  source/conf.py
Labels: design

#1510 Cache problem solved (3.9)
  source/conf.py
Labels: design

#1519 [3.1] Fixed table in page util.sh and warnings
  source/installation-guide/packages-list/index.rst
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1518 [3.2] Fixed table in page util.sh
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1513 Change Solaris 10 reference to Solaris 11
  source/installation-guide/installing-wazuh-agent/wazuh_agent_solaris.rst
Labels: enhancement

#1517 [3.3] Fixed table in page util.sh
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1516 [3.4] Fixed table in page util.sh
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1515 [3.5] Fixed table in page util.sh
  source/user-manual/reference/tools/util.sh.rst
Labels: bug

#1530 The contents section links are now blue (2.1)
  source/_static/css/style.css
Labels: design

#1529 The contents section links are now blue (3.0)
  source/_static/css/style.css
Labels: design

#1528 The contents section links are now blue (3.1)
  source/_static/css/style.css
Labels: design

#1527 The contents section links are now blue (3.2)
  source/_static/css/style.css
Labels: design

#1526 The contents section links are now blue (3.3)
  source/_static/css/style.css
Labels: design

#1520 The contents section links are now blue (3.9)
  source/_static/css/style.css
Labels: design

#1525 The contents section links are now blue (3.4)
  source/_static/css/style.css
Labels: design

#1523 The contents section links are now blue (3.6)
  source/_static/css/style.css
Labels: design

#1522 The contents section links are now blue (3.7)
  source/_static/css/style.css
Labels: design

#1521 The contents section links are now blue (3.8)
  source/_static/css/style.css
Labels: design

#1452 Update Filebeat installation instructions
  source/deploying-with-ansible/guide/install-wazuh-server.rst
Labels: ansible

#1308 Update WPK documentation.
  source/user-manual/agents/remote-upgrading/create-custom-wpk.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/create-custom-wpk-automatically.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/create-custom-wpk-manually.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/create-wpk-key.rst
  source/user-manual/agents/remote-upgrading/index.rst
Labels: enhancement, wpk

#1561 Added differentiation between CMD and PowerShell agent install
  source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst
Labels: operations

#1543 Azure deprecated json file
  source/azure/monitoring activity.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
Labels: operations

#1544 Added example on how to test Report generation
  source/user-manual/manager/automatic-reports.rst
Labels: operations

#1562 Made distintion between installing app from URL and installing from a…
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
Labels: operations

#1564 [2.1] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1565 [3.0] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1566 [3.1] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1567 [3.2] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1568 [3.3] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1569 [3.4] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1570 [3.5] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1571 [3.6] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1572 [3.7] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1573 [3.8] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1574 [3.9] Sidebar functionality compatible with IE11
  source/_static/js/style.js
Labels: bug

#1588 Refactor auto-deploy variables
  source/installation-guide/installing-wazuh-agent/deployment_variables.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables_windows.rst
Labels: enhancement, packages

#1610 [3.9] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1611 [3.8] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1612 [3.7] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1613 [3.6] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1614 [3.5] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1615 [3.4] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1616 [3.3] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1617 [3.2] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1618 [3.1] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1619 [3.0] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1620 [2.1] Fixed responsivity for smartphone/tablet sizes
  source/_static/css/style.css
Labels: bug

#1623 Improvements in cluster documentation
  source/development/wazuh-cluster.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables.rst
  source/release-notes/release_3_0_0.rst
  source/release-notes/release_3_2_3.rst
  source/user-manual/configuring-cluster/advanced-settings.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/configuring-cluster/cluster_management.rst
  source/user-manual/configuring-cluster/index.rst
  source/user-manual/index.rst
  source/user-manual/manager/index.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/reference/ossec-conf/cluster.rst
  source/user-manual/registering/registration-process.rst
Labels: enhancement, new-docs

#1652 3.9 elastic installation changes
  source/installation-guide/installing-elastic-stack/configure-elasticsearch-cluster.rst
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/installation-guide/installing-elastic-stack/index.rst
Labels: operations
