Repository wazuh/wazuh-documentation, pull requests merged in 2020-02, with the labels that each got.

#2167 Correct typo in 'Configuring an S3 Bucket' documentation
  source/amazon/services/prerequisites/S3-bucket.rst
Labels: typo

#2165 Ruleset XML Syntax rework
  source/images/manual/ruleset/ruleset-xml-syntax/decoders-tree.png
  source/images/manual/ruleset/ruleset-xml-syntax/sibling_decoders_tree.png
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/index.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
  source/user-manual/ruleset/ruleset-xml-syntax/sibling-decoders.rst
Labels: enhancement, new-docs, operations, typo

#2155 [AWS-S3 wodle] Correct typo
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: typo

#2089 [3.10] Added reminded to cdb lists
  source/user-manual/ruleset/cdb-list.rst
Labels: enhancement, operations

#2072 Update release_3_0_0.rst
  source/release-notes/release_3_0_0.rst
Labels: operations

#2071 3.10 cdb-list edit
  source/user-manual/ruleset/cdb-list.rst
Labels: enhancement, operations, typo

#2069 Typo fix on link
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: typo

#1994 Rephrased an explanation and fixed a mistake
  source/user-manual/manager/alert-threshold.rst
Labels: typo

#2171 3.11 cdb list edit
  source/user-manual/ruleset/cdb-list.rst
Labels: operations, typo

#2172 Rephrased and explanation and fixed a mistake
  source/user-manual/manager/alert-threshold.rst
Labels: operations

#2173 [2.1] Learning Wazuh: Added newUrls to redirections.js
  source/_static/js/redirects.js
Labels: SEO

#2174 [3.0] Learning Wazuh: Added newUrls to redirections.js
  source/_static/js/redirects.js
Labels: SEO

#2175 [3.1] Learning Wazuh: Added newUrls to redirections.js
  source/_static/js/redirects.js
Labels: SEO

#2186 Improve wording when referring to time
  source/development/wazuh-cluster.rst
  source/user-manual/agents/agent-life-cycle.rst
Labels: typo

#2208 Moving packaging information to development
  source/development/index.rst
  source/development/packaging/generate-aix-package.rst
  source/development/packaging/generate-deb-package.rst
  source/development/packaging/generate-hpux-package.rst
  source/development/packaging/generate-osx-package.rst
  source/development/packaging/generate-ova.rst
  source/development/packaging/generate-rpm-package.rst
  source/development/packaging/generate-sol-package.rst
  source/development/packaging/generate-wazuh-kibana-app.rst
  source/development/packaging/generate-wazuh-splunk-app.rst
  source/development/packaging/generate-windows-package.rst
  source/development/packaging/generate-wpk-package.rst
  source/development/packaging/index.rst
  source/development/wazuh-cluster.rst
  source/index.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/create-wpk-key.rst
Labels: cicd, enhancement

#2209 [3.11] Changes in redirects.js after moving the packaging folder
  source/_static/js/redirects.js
Labels: bug

#2161 Add database option to syscheck
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: enhancement, fim-rework

#2188 [2.1] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2189 [3.0] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2190 [3.1] Fixed some broken links
  source/_static/js/redirects.min.js
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2191 [3.2] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2192 [3.3] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2193 [3.4] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2194 [3.5] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2195 [3.6] Fixed some broken links
  source/docker/wazuh-container.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2196 [3.7] Fixed some broken links
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2197 [3.8] Fixed some broken links
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2198 [3.9] Fixed some broken links
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/capabilities/osquery.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2199 [3.10] Fixed some broken links
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/user-manual/capabilities/osquery.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2200 [3.11] Fixed some broken links
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/rootkit-detection.rst
  source/release-notes/release_3_11_0.rst
  source/user-manual/capabilities/osquery.rst
  source/user-manual/capabilities/vulnerability-detection/how_it_works.rst
  source/user-manual/reference/ossec-conf/integration.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
Labels: bug

#2158 [3.10] Fixed the position of the lightbox in releases other than the latest
  source/_static/js/style.js
Labels: bug

#2214 Add step to perform a wazuh.yml backup in 3.11.X upgrades
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
Labels: kibana-plugin

#2088 [3.10] Grammar and style corrections
  source/_static/css/style.css
  source/_static/js/style.js
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/deploying-with-puppet/setup-puppet/install-puppet-master.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: bug

#2215 Fixed link
  source/user-manual/kibana-app/troubleshooting.rst
Labels: operations, typo

#2207 Fixed description of value older_than
  source/user-manual/api/reference.rst
Labels: operations

#2212 Update Syscheck option max_eps reference
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: fim-rework

#2228 [3.11] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2239 [2.1] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2238 [3.0] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2237 [3.1] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2236 [3.2] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2235 [3.3] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2234 [3.4] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2233 [3.5] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2232 [3.6] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2231 [3.7] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2230 [3.8] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2229 [3.9] Minor corrections in some RST files
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-ansible/roles/wazuh-manager.rst
  source/deploying-with-ansible/setup-remote-systems.rst
  source/deploying-with-puppet/setup-puppet/install-puppet-master.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/reference/tools/ossec-logtest.rst
Labels: typo

#2117 Adjusting deployment variables to correct version
  source/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.rst
Labels: deployment

#2118 Adjusting deployment variables to correct version on Wazuh v3.10
  source/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.rst
Labels: packages

#2245 New structure daria
  source/_templates/installations/elastic/common/elastic-single-node/generate_deploy_certificates.rst
Labels: rework, typo
