Repository wazuh/wazuh-documentation, pull requests merged in 2020-06, with the labels that each got.

#2557 Added command to increase heap size of Kibana - 3.11
  source/installation-guide/installing-elastic-stack/elastic_server_deb.rst
  source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.rst
Labels: elastic, installation guide, upgrade-guide

#2558 Bumped Elasticsearch version to 7.7.1
  source/conf.py
Labels: elastic, operations

#2559 Fix and update some API documentation examples and endpoints
  source/user-manual/api/reference.rst
Labels: API

#2492 Vulnerability Detector: NVD linux support
  source/images/manual/vuln-detector/vuln-detector-kibana.png
  source/images/manual/vuln-detector/vuln-detector-overview.png
  source/images/manual/vuln-detector/vuln-detector-splunk.png
  source/user-manual/capabilities/vulnerability-detection/compatibility_matrix.rst
  source/user-manual/capabilities/vulnerability-detection/how_it_works.rst
  source/user-manual/capabilities/vulnerability-detection/running_vu_scan.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: core/vuln detector

#2574 Vulnerability Detector documentation for 3.13
  source/images/manual/vuln-detector/vuln-detector-alert.png
  source/images/manual/vuln-detector/vuln-detector-kibana.png
  source/images/manual/vuln-detector/vuln-detector-overview.png
  source/images/manual/vuln-detector/vuln-detector-splunk.png
  source/learning-wazuh/vuln-detection.rst
  source/user-manual/capabilities/vulnerability-detection/compatibility_matrix.rst
  source/user-manual/capabilities/vulnerability-detection/how_it_works.rst
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
  source/user-manual/capabilities/vulnerability-detection/running_vu_scan.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
Labels: core/vuln detector

#2596 Corrected sentence in hotfixes subsection of the ossec.conf section of the documentation.
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
Labels: typo

#2552 [3.0] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2551 [3.1] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2550 [3.2] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2549 [3.3] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2548 [3.4] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2547 [3.5] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2546 [3.6] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2545 [3.7] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2544 [3.8] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2543 [3.9] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2542 [3.10] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2541 [3.11] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2540 [3.12] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2599 [3.13] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement

#2650 Add ARM packages to packages-list page
  source/conf.py
  source/installation-guide/packages-list/index.rst
Labels: enhancement, packages

#2652 Add base64_log to Logcollector's output format
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: new-docs
