Repository wazuh/wazuh-documentation, pull requests merged in 2020-09, with the labels that each got.

#2794 Fixed a bug in the style of the top bar (develop)
  source/_static/css/style.css
  source/_themes/wazuh_doc_theme/header.html
Labels: bug

#2692 [2.1] Fixed the style of nested lists and minor errors
  .gitignore
  source/_static/css/style.css
Labels: bug

#2693 [3.0] Fixed the style of nested lists and minor errors
  .gitignore
  source/_static/css/style.css
  source/_static/js/redirects.min.js
  source/user-manual/manager/manual-email-report/smtp_authentication.rst
Labels: bug

#2694 [3.1] Fixed the style of nested lists
  source/_static/css/style.css
Labels: bug

#2695 [3.2] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
Labels: bug

#2696 [3.3] Fixed the style of nested lists
  source/_static/css/style.css
Labels: bug

#2697 [3.4] Fixed the style of nested lists
  source/_static/css/style.css
Labels: bug

#2698 [3.5] Fixed the style of nested lists
  source/_static/css/style.css
Labels: bug

#2699 [3.6] Fixed the style of nested lists
  source/_static/css/style.css
Labels: bug

#2701 [3.7] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/docker/wazuh-container.rst
Labels: bug

#2702 [3.8] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/docker/wazuh-container.rst
Labels: bug

#2706 [3.9] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/docker/wazuh-container.rst
  source/installation-guide/securing_api.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2708 [3.10] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/development/wazuh-cluster.rst
  source/docker/wazuh-container.rst
  source/installation-guide/securing_api.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2711 [3.11] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/development/wazuh-cluster.rst
  source/docker/wazuh-container.rst
  source/installation-guide/securing_api.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/survive-flood.rst
  source/user-manual/kibana-app/reference/configure-indices.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2714 [3.12] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/development/wazuh-cluster.rst
  source/docker/container-usage.rst
  source/docker/wazuh-container.rst
  source/installation-guide/securing_api.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.rst
  source/user-manual/kibana-app/reference/configure-indices.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2715 [3.13] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/development/wazuh-cluster.rst
  source/docker/container-usage.rst
  source/docker/wazuh-container.rst
  source/installation-guide/securing_api.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.rst
  source/user-manual/kibana-app/reference/configure-indices.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2717 [4.0] Fixed the style of nested lists and minor errors
  source/_static/css/style.css
  source/deploying-with-ansible/guide/install-ansible.rst
  source/development/wazuh-cluster.rst
  source/docker/container-usage.rst
  source/docker/wazuh-container.rst
  source/learning-wazuh/audit-commands.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.rst
  source/upgrade-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.rst
  source/user-manual/kibana-app/reference/configure-indices.rst
  source/user-manual/kibana-app/reference/custom-dashboard.rst
Labels: bug

#2852 [3.13] New screenshots in home page
  source/_static/css/style.css
  source/_static/js/style.js
  source/images/screenshots/01-Wazuh-Security-Analytics.png
  source/images/screenshots/02-Wazuh-Intrusion-Detection.png
  source/images/screenshots/03-Wazuh-Log-Data-Analysis.png
  source/images/screenshots/04-Wazuh-File-Integrity-Monitoring.png
  source/images/screenshots/05-Wazuh-Vulnerability-Detection.png
  source/images/screenshots/06-Wazuh-Configuration-Assessment.png
  source/images/screenshots/07-Wazuh-Incident-Response.png
  source/images/screenshots/08-Wazuh-Regulatory-Compliance.png
  source/images/screenshots/09-Wazuh-Cloud-Security.png
  source/images/screenshots/10-Wazuh-Containers-Security.png
  source/images/screenshots/ag-welcome.png
  source/images/screenshots/discover.png
  source/images/screenshots/mg-ruleset.png
  source/images/screenshots/ow-fim.png
  source/images/screenshots/ow-general.png
  source/images/screenshots/ow-welcome.png
  source/index.rst
Labels: design

#2851 [develop] New screenshots in home page
  source/_static/css/style.css
  source/_static/js/style.js
  source/images/screenshots/01-Wazuh-Security-Analytics.png
  source/images/screenshots/02-Wazuh-Intrusion-Detection.png
  source/images/screenshots/03-Wazuh-Log-Data-Analysis.png
  source/images/screenshots/04-Wazuh-File-Integrity-Monitoring.png
  source/images/screenshots/05-Wazuh-Vulnerability-Detection.png
  source/images/screenshots/06-Wazuh-Configuration-Assessment.png
  source/images/screenshots/07-Wazuh-Incident-Response.png
  source/images/screenshots/08-Wazuh-Regulatory-Compliance.png
  source/images/screenshots/09-Wazuh-Cloud-Security.png
  source/images/screenshots/10-Wazuh-Containers-Security.png
  source/images/screenshots/ag-welcome.png
  source/images/screenshots/discover.png
  source/images/screenshots/mg-ruleset.png
  source/images/screenshots/ow-fim.png
  source/images/screenshots/ow-general.png
  source/images/screenshots/ow-welcome.png
  source/index.rst
Labels: design

#2680 [2.1] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2679 [3.0] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2678 [3.1] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2677 [3.2] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2676 [3.3] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2675 [3.4] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2674 [3.5] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2673 [3.6] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2672 [3.7] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2671 [3.8] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2670 [3.9] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2669 [3.10] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2668 [3.11] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2667 [3.12] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2666 [3.13] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2665 [4.0] Decreased CLS to improve UX
  source/_static/css/style.css
  source/_static/js/style.js
  source/_themes/wazuh_doc_theme/layout.html
Labels: enhancement

#2911 Remove allow Redhat option for VDT
  source/user-manual/capabilities/vulnerability-detection/allow_os.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: core/vuln detector

#2784 Updated the help messages of the package generators
  source/development/packaging/generate-aix-package.rst
  source/development/packaging/generate-deb-package.rst
  source/development/packaging/generate-hpux-package.rst
  source/development/packaging/generate-osx-package.rst
  source/development/packaging/generate-ova.rst
  source/development/packaging/generate-rpm-package.rst
  source/development/packaging/generate-sol-package.rst
  source/development/packaging/generate-wazuh-kibana-app.rst
  source/development/packaging/generate-wazuh-splunk-app.rst
  source/development/packaging/generate-windows-package.rst
  source/development/packaging/generate-wpk-package.rst
Labels: operations, packages
