Repository wazuh/wazuh-documentation, pull requests merged in 2020-11, with the labels that each got.

#3082 Add ruleset reference of PCRE2 attribute for expressions
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/regex.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: pending-core

#3120 Add rootcheck to RBAC reference.
  source/user-manual/api/equivalence.rst
  source/user-manual/api/rbac/reference.rst
Labels: API

#3089 Added macOS for vdt and os_patch
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
  source/release-notes/index.rst
  source/release-notes/release_4_1_0.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/capabilities/vulnerability-detection/compatibility_matrix.rst
Labels: pending-core

#2973 wazuh logtest documentation
  source/_static/js/redirects.js
  source/development/index.rst
  source/development/wazuh-logtest.rst
  source/images/development/logtest-flow.png
  source/images/manual/wazuh-logtest/logtest_session_collector.png
  source/user-manual/capabilities/index.rst
  source/user-manual/capabilities/wazuh-logtest/how-it-works.rst
  source/user-manual/capabilities/wazuh-logtest/index.rst
  source/user-manual/capabilities/wazuh-logtest/logtest-configuration.rst
  source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
  source/user-manual/reference/ossec-conf/index.rst
  source/user-manual/reference/ossec-conf/rule_test.rst
  source/user-manual/reference/tools/index.rst
  source/user-manual/reference/tools/ossec-logtest.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/reference/tools/wazuh-logtest.rst
Labels: core/logtest, pending-core

#3147 Adapt SCA available policies table with latest changes
  source/user-manual/capabilities/sec-config-assessment/how_to_configure.rst
Labels: core/sca

#3158 Updating agents' status diagram
  source/images/manual/managing-agents/agent-status.png
Labels: team/duff

#3162 Connection status fixes
  source/images/manual/managing-agents/agent-status.png
  source/user-manual/reference/ossec-conf/global.rst
Labels: team/duff
