Repository wazuh/wazuh-documentation, pull requests merged in 2020-04, with the labels that each got.

#2365 [3.12] Fixed the copy functionality in code-blocks containing here-documents
  source/_static/css/style.css
  source/_static/js/style.js
Labels: bug

#1944 [3.11] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1943 [3.10] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1942 [3.9] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1941 [3.8] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1940 [3.7] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1939 [3.6] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1938 [3.5] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1937 [3.4] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1936 [3.3] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1935 [3.2] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1934 [3.1] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1933 [3.0] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#1932 [2.1] Added the option to include/exclude GA
  Makefile
  make.bat
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: bug

#2395 [3.12] Fixed the code that excludes the release notes from the search results
  source/_static/js/style.js
Labels: bug

#2406 Updated 'software and libraries used' in README.md
  README.md
Labels: bug

#2410 [Vulnerability-Detector] Support Ubuntu 20.04
  source/learning-wazuh/vuln-detection.rst
  source/user-manual/capabilities/vulnerability-detection/compatibility_matrix.rst
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: core/vuln detector

#2415 Clarify how to apply Canonical feeds to Vulnerability Detector
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
Labels: core/vuln detector

#2405 Update IIS location
  source/user-manual/capabilities/log-data-collection/log-data-configuration.rst
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: missing-docs, new-docs
