Repository wazuh/wazuh-documentation, pull requests merged in 2020-05, with the labels that each got.

#2394 User manual - Registering agents improvement done for the branch 3.12
  source/_static/css/style.css
  source/_templates/common/client_server_section.rst
  source/_templates/common/linux/restart_agent.rst
  source/_templates/common/macosx/restart_agent.rst
  source/_templates/common/restart_manager.rst
  source/_templates/common/windows/restart_agent.rst
  source/_templates/registrations/common/client_server_section.rst
  source/_templates/registrations/common/set_agent_name.rst
  source/_templates/windows/installation_directory.rst
  source/conf.py
  source/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_aix.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_macos.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables/linux/deployment_variables_apt.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables/linux/deployment_variables_dnf.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables/linux/deployment_variables_yum.rst
  source/installation-guide/installing-wazuh-agent/deployment_variables/linux/deployment_variables_zypper.rst
  source/user-manual/agents/agent-life-cycle.rst
  source/user-manual/configuring-cluster/advanced-settings.rst
  source/user-manual/registering/api/api-register-linux-unix.rst
  source/user-manual/registering/api/api-register-macos.rst
  source/user-manual/registering/api/api-register-windows.rst
  source/user-manual/registering/cli/using-command-line-linux.rst
  source/user-manual/registering/cli/using-command-line-macos.rst
  source/user-manual/registering/cli/using-command-line-unix.rst
  source/user-manual/registering/cli/using-command-line-windows.rst
  source/user-manual/registering/command-line-registration.rst
  source/user-manual/registering/host-verification-registration.rst
  source/user-manual/registering/index.rst
  source/user-manual/registering/linux-unix-simple-registration.rst
  source/user-manual/registering/macos-simple-registration.rst
  source/user-manual/registering/manager-verification/agent-verification-registration.rst
  source/user-manual/registering/manager-verification/agents/linux-unix-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/linux-unix-manager-verification.rst
  source/user-manual/registering/manager-verification/agents/macos-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/macos-manager-verification.rst
  source/user-manual/registering/manager-verification/agents/windows-agent-verification.rst
  source/user-manual/registering/manager-verification/agents/windows-manager-verification.rst
  source/user-manual/registering/manager-verification/host-verification-registration.rst
  source/user-manual/registering/manager-verification/manager-verification-registration.rst
  source/user-manual/registering/password-authorization-registration-service.rst
  source/user-manual/registering/password-authorization-registration.rst
  source/user-manual/registering/password/linux-unix-password-registration.rst
  source/user-manual/registering/password/macos-password-registration.rst
  source/user-manual/registering/password/windows-password-registration.rst
  source/user-manual/registering/registering-agents-theory.rst
  source/user-manual/registering/registering-agents-troubleshooting.rst
  source/user-manual/registering/registration-process.rst
  source/user-manual/registering/restful-api-register.rst
  source/user-manual/registering/restful-api-registration.rst
  source/user-manual/registering/simple-registration-method.rst
  source/user-manual/registering/using-command-line.rst
  source/user-manual/registering/windows-simple-registration.rst
Labels: registering, rework, user-manual

#2421 Deploying a Wazuh cluster - "agent_control -l" command explanation improvement.
  source/user-manual/configuring-cluster/index.rst
Labels: cluster, user-manual

#2398 fixing a badly closed tag
  source/user-manual/capabilities/log-data-collection/how-it-works.rst
Labels: bug, operations, typo

#2428 Ansible Deployment guide - Fixed typo
  source/deploying-with-ansible/guide/install-elk-server.rst
Labels: ansible, typo

#2427 "How to share policy files and configuration with agents" section improvement
  source/user-manual/capabilities/sec-config-assessment/how_to_configure.rst
Labels: rework, user-manual

#2400 Redirections guide
  .github/pull_request_template.md
  NEW_RELEASE.md
Labels: Pending merge, enhancement

#2438 Fix issue 2437 regarding syntax for <field>
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: operations

#2435 Added all the redirections for the changes in 'Registering agents'
  source/_static/js/redirects.js
Labels: bug

#2436 [3.12] Recoverd missing fixes for the style
  source/_static/css/style.css
Labels: bug

#2445 [3.11] Updated CSS and JS
  source/_static/css/style.css
  source/_static/js/redirects.js
Labels: design

#2446 [3.10] Updated CSS and JS
  source/_static/css/style.css
  source/_static/js/redirects.js
Labels: design

#2459 Minor fix
  source/user-manual/manager/manual-email-report/index.rst
Labels: typo

#2485 Added clarification to the command explanation.
  source/user-manual/capabilities/sec-config-assessment/how_to_configure.rst
Labels: user-manual

#2419 Clarify the command expect option
  source/user-manual/reference/ossec-conf/commands.rst
Labels: user-manual

#2507 Added clarification to the rotate_interval option - branch 3.10
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf

#2506 Added clarification to the rotate_interval option - branch 3.11
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf

#2505 Added clarification to the rotate_interval option - branch 3.12
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf

#2523 Added the clarification of the rotate_interval option - branch 3.8
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf

#2522 Added the clarification of the rotate_interval option - branch 3.9
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf

#2491 [3.12] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2508 [3.11] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2509 [3.10] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2510 [3.9] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2511 [3.8] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2512 [3.7] Increased compatibility with Sphinx 3.0.3
  README.md
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2513 [3.6] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2514 [3.5] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2515 [3.4] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2516 [3.3] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2517 3.2 sphinx update
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2518 [3.1] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2519 [3.0] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2520 [2.1] Increased compatibility with Sphinx 3.0.3
  requirements.txt
  source/_static/css/style.css
  source/conf.py
Labels: enhancement

#2524 [2.1] Added sitemap generation during the compilation process
  source/_themes/wazuh_doc_theme/theme.conf
  source/conf.py
Labels: enhancement
