Repository wazuh/wazuh-documentation, pull requests merged in 2020-01, with the labels that each got.

#2115 Add release notes of 3.11.1
  source/release-notes/index.rst
  source/release-notes/release_3_11_1.rst
Labels: new-docs

#2106 Grammar typo
  source/user-manual/kibana-app/reference/configure-indices.rst
Labels: operations, typo

#2086 3.10 typos below.
  source/user-manual/api/getting-started.rst
  source/user-manual/capabilities/agent-key-polling.rst
  source/user-manual/kibana-app/features/query-configuration.rst
Labels: operations, typo

#2087 [3.10] Filter the content of the code-block on copy to the clipboard
  source/_static/js/style.js
Labels: enhancement

#2131 Fixed the CSS rules for the style of the button 'Copy to clipboard'
  source/_static/css/style.css
Labels: bug

#2153 Update OVA Elastic version to 7.5.2
  source/installation-guide/virtual-machine.rst
Labels: bug

#2154 Bump Puppet to 3.11.3_7.5.2
  source/deploying-with-puppet/wazuh-puppet-module/index.rst
Labels: puppet

#2162 [3.11] Added special management for code blocks with escaped tag signs
  source/_static/js/style.js
Labels: enhancement
