Repository wazuh/wazuh-documentation, pull requests merged in 2020-12, with the labels that each got.

#3199 Add Windows registries documentation
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: pending-core

#3161 localfile: add multiline-regex and continue from last read line
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: ossec.conf

#3243 Documentation for Wazuh daemons renaming
  source/_static/js/redirects.js
  source/deploying-with-ansible/roles/wazuh-agent.rst
  source/deploying-with-kubernetes/kubernetes-conf.rst
  source/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/development/makefile.rst
  source/development/wazuh-logtest.rst
  source/installation-guide/requirements.rst
  source/installation-guide/wazuh-agent/deployment_variables/deployment_variables_windows.rst
  source/learning-wazuh/build-lab/install-linux-agents.rst
  source/learning-wazuh/build-lab/install-wazuh-manager.rst
  source/learning-wazuh/build-lab/install-windows-agent.rst
  source/learning-wazuh/detect-fs-changes.rst
  source/learning-wazuh/survive-flood.rst
  source/pci-dss/policy-monitoring.rst
  source/release-notes/release_2_1.rst
  source/user-manual/agents/agent-connection.rst
  source/user-manual/agents/index.rst
  source/user-manual/api/configuration.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/capabilities/agent-key-polling.rst
  source/user-manual/capabilities/agentless-monitoring/how-it-works.rst
  source/user-manual/capabilities/log-data-collection/log-data-configuration.rst
  source/user-manual/capabilities/wazuh-logtest/index.rst
  source/user-manual/capabilities/wazuh-logtest/logtest-faq.rst
  source/user-manual/kibana-app/troubleshooting.rst
  source/user-manual/manager/automatic-reports.rst
  source/user-manual/reference/daemons/index.rst
  source/user-manual/reference/daemons/wazuh-agentd.rst
  source/user-manual/reference/daemons/wazuh-agentlessd.rst
  source/user-manual/reference/daemons/wazuh-analysisd.rst
  source/user-manual/reference/daemons/wazuh-authd.rst
  source/user-manual/reference/daemons/wazuh-csyslogd.rst
  source/user-manual/reference/daemons/wazuh-dbd.rst
  source/user-manual/reference/daemons/wazuh-execd.rst
  source/user-manual/reference/daemons/wazuh-integratord.rst
  source/user-manual/reference/daemons/wazuh-logcollector.rst
  source/user-manual/reference/daemons/wazuh-maild.rst
  source/user-manual/reference/daemons/wazuh-monitord.rst
  source/user-manual/reference/daemons/wazuh-remoted.rst
  source/user-manual/reference/daemons/wazuh-reportd.rst
  source/user-manual/reference/daemons/wazuh-syscheckd.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/localfile.rst
  source/user-manual/reference/ossec-conf/verifying-configuration.rst
  source/user-manual/reference/statistics-files/index.rst
  source/user-manual/reference/statistics-files/wazuh-agentd-state.rst
  source/user-manual/reference/statistics-files/wazuh-analysisd-state.rst
  source/user-manual/reference/statistics-files/wazuh-remoted-state.rst
  source/user-manual/reference/tools/agent-auth.rst
  source/user-manual/reference/tools/index.rst
  source/user-manual/reference/tools/ossec-control.rst
  source/user-manual/reference/tools/ossec-logtest.rst
  source/user-manual/reference/tools/rootcheck_control.rst
  source/user-manual/reference/tools/util.sh.rst
  source/user-manual/reference/tools/wazuh-logtest.rst
  source/user-manual/registering/password-authorization-registration.rst
  source/user-manual/registering/registering-agents-theory.rst
Labels: pending-core

#3250 Typo Offline Update
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
Labels: operations, typo

#3230 removed / before URL of debian offline update config
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
Labels: operations, typo

#3253 Enhancing log analysis with PCRE2
  source/_static/js/redirects.js
  source/user-manual/ruleset/ruleset-xml-syntax/index.rst
  source/user-manual/ruleset/ruleset-xml-syntax/pcre2.rst
Labels: user manual
