Repository wazuh/wazuh-documentation, pull requests merged in 2020-10, with the labels that each got.

#2563 "Insert a Wazuh API entry automatically" page removed and its content moved - for branch 3.12
  source/_static/js/redirects.js
  source/installation-guide/installing-elastic-stack/automatic_api.rst
  source/installation-guide/installing-elastic-stack/index.rst
  source/installation-guide/installing-splunk/splunk-app.rst
Labels: API, installation guide, splunk

#2887 [3.13] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2885 [3.11] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2884 [3.10] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2975 Replaced diagrams for API section
  source/images/rbac/auth_context_login.png
  source/images/rbac/auth_context_rule.png
  source/images/rbac/example1_rule.png
  source/images/rbac/example2_rule.png
Labels: design

#2883 [3.9] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2882 [3.8] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2881 [3.7] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2880 [3.6] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2879 [3.5] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2878 [3.4] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2877 [3.3] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2876 [3.2] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2874 [3.1] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2873 [3.0] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2919 Removed Logstash from K8S configuration guide
  source/deploying-with-kubernetes/kubernetes-conf.rst
Labels: kubernetes

#2872 [2.1] Correctly ignore theme's min files
  .gitignore
Labels: type: bug

#2960 Fix and update API documentation
  source/installation-guide/installing-splunk/splunk-basic.rst
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_packages_amazon.rst
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.rst
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_packages_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_sources_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_packages_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_sources_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_packages_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_sources_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_packages_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_sources_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_packages_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_sources_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.rst
  source/installation-guide/securing_api.rst
  source/learning-wazuh/build-lab/install-wazuh-manager.rst
  source/user-manual/agents/remove-agents/restful-api-remove.rst
  source/user-manual/api/configuration.rst
  source/user-manual/api/equivalence.rst
  source/user-manual/api/examples.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/queries.rst
  source/user-manual/api/rbac/auth_context.rst
  source/user-manual/api/rbac/configuration.rst
  source/user-manual/api/rbac/how-it-works.rst
  source/user-manual/api/rbac/index.rst
  source/user-manual/api/rbac/reference.rst
Labels: API

#3029 Update list_ parameters
  source/user-manual/api/equivalence.rst
  source/user-manual/api/examples.rst
Labels: API

#3031 Update RBAC reference page.
  source/user-manual/api/rbac/reference.rst
Labels: API

#3038 Minor typo fix
  source/docker/faq-wazuh-container.rst
Labels: docker

#2990 Update documentation with the negate attribute for expressions
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: pending-core

#3068 Create release notes for v4.0.0
  source/_static/js/redirects.js
  source/release-notes/index.rst
  source/release-notes/release_4_0_0.rst
Labels: hacktoberfest-accepted

#3069 Fix uppercase typo
  source/installation-guide/requirements.rst
Labels: typo

#3072 Simplified instructions to install Kibana and enter its user web interface.
  source/installation-guide/open-distro/all-in-one-deployment/all_in_one.rst
  source/installation-guide/open-distro/all-in-one-deployment/unattended-installation.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/kibana/index.rst
  source/installation-guide/open-distro/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.rst
  source/installation-guide/packages-list.rst
  source/user-manual/elasticsearch/elastic_tuning.rst
Labels: hacktoberfest-accepted

#3078 Add MSU quick link
  source/installation-guide/packages-list.rst
Labels: hacktoberfest-accepted

#3084 Add wazuh_clusterd.debug in internal_options.
  source/user-manual/reference/internal-options.rst
Labels: cluster

#3086 Simplified the instructions for changing Elasticsearch users’ passwords
  source/user-manual/elasticsearch/elastic_tuning.rst
Labels: hacktoberfest-accepted

#3093 Replaced the getting started images and changed the installation guide title
  source/images/getting_started/agent_architecture.png
  source/images/getting_started/data_flow.png
  source/images/getting_started/deployment.png
  source/images/getting_started/server_architecture.png
  source/installation-guide/index.rst
Labels: hacktoberfest-accepted

#3094 Simplified the instructions for installing Kibana and accessing its web interface (Elastic Stack basic license)
  source/installation-guide/more-installation-alternatives/elastic-stack/all-in-one-deployment/all_in_one.rst
  source/installation-guide/more-installation-alternatives/elastic-stack/all-in-one-deployment/unattended-installation.rst
  source/installation-guide/more-installation-alternatives/elastic-stack/distributed-deployment/step-by-step-installation/kibana/index.rst
  source/installation-guide/more-installation-alternatives/elastic-stack/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.rst
Labels: hacktoberfest-accepted

#3098 Changed the agent connection service protocol
  source/getting-started/architecture.rst
Labels: hacktoberfest-accepted

#3096 [develop] Fixed the spacing in the stylesheet for the pages that use ReDoc
  source/_static/css/custom-redoc.css
Labels: design

#3095 [4.0] Fixed the spacing in the stylesheet for the pages that use ReDoc
  source/_static/css/custom-redoc.css
Labels: design

#3102 Moved the credentials to enter the WUI to improve their visibility on the OVA webpage
  source/virtual-machine/virtual-machine.rst
Labels: hacktoberfest-accepted

#3103 Added instructions to start the Wazuh agent
  source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst
  source/installation-guide/wazuh-agent/wazuh_agent_package_linux.rst
Labels: hacktoberfest-accepted

#3105 Removed the .service from the systemctl commands
  source/_templates/installations/basic/elastic/common/enable_elasticsearch.rst
  source/_templates/installations/basic/elastic/common/enable_filebeat.rst
  source/_templates/installations/basic/elastic/common/enable_kibana.rst
  source/_templates/installations/elastic/common/enable_elasticsearch.rst
  source/_templates/installations/elastic/common/enable_filebeat.rst
  source/_templates/installations/elastic/common/enable_kibana.rst
  source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst
  source/_templates/installations/wazuh/common/enable_wazuh_manager_service.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-2.x-to-5.x.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.x-to-6.8.rst
Labels: hacktoberfest-accepted

#3106 Added the recommended hardware requirements
  source/installation-guide/requirements.rst
Labels: hacktoberfest-accepted

#3107 Updated instructions regarding service starting on manager and linux …
  source/learning-wazuh/build-lab/install-linux-agents.rst
  source/learning-wazuh/build-lab/install-wazuh-manager.rst
Labels: hacktoberfest-accepted

#3111 Add HP-UX uninstallation guide and fix some typos
  source/installation-guide/index.rst
  source/installation-guide/open-distro/distributed-deployment/index.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/index.rst
  source/installation-guide/wazuh-agent/wazuh_agent_package_aix.rst
  source/installation-guide/wazuh-agent/wazuh_agent_package_hpux.rst
  source/virtual-machine/virtual-machine.rst
Labels: hacktoberfest-accepted, installation guide, missing docs
