Repository wazuh/wazuh-documentation, pull requests merged in 2020-03, with the labels that each got.

#2110 Update allow_os.rst
  source/user-manual/capabilities/vulnerability-detection/allow_os.rst
Labels: community, vulnerability-detector

#2247 Reviewed and fixed style details in Learning Wazuh section
  source/learning-wazuh/hidden-processes.rst
  source/learning-wazuh/rdp-brute-force.rst
  source/learning-wazuh/replace-stock-rule.rst
  source/learning-wazuh/shellshock.rst
  source/learning-wazuh/suricata.rst
  source/learning-wazuh/survive-flood.rst
  source/learning-wazuh/vuln-detection.rst
Labels: bug, design

#2249 Audit configuration for huge amount of events at the same time
  source/user-manual/capabilities/file-integrity/fim-faq.rst
Labels: fim-rework

#2254 Fixed 17 typos
  source/development/packaging/generate-sol-package.rst
  source/docker/container-usage.rst
  source/gdpr/gdpr-IV.rst
  source/installation-guide/installing-splunk/splunk-basic.rst
  source/learning-wazuh/hidden-processes.rst
  source/learning-wazuh/replace-stock-rule.rst
  source/learning-wazuh/ssh-brute-force.rst
  source/migrating-from-ossec/ossec-server.rst
  source/release-notes/release_3_11_0.rst
  source/release-notes/release_3_2_1.rst
  source/release-notes/release_3_3_1.rst
  source/user-manual/capabilities/vulnerability-detection/cpe_helper.rst
  source/user-manual/reference/daemons/ossec-analysisd.rst
  source/user-manual/reference/ossec-conf/fluent-forward.rst
  source/user-manual/registering/password-authorization-registration-service.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: operations, typo

#2253 Detected typo en Learning Wazuh
  source/learning-wazuh/detect-fs-changes.rst
Labels: operations, typo

#2259 Fixes minor typos in Rules Syntax (scr -> src)
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: operations, typo

#2261 Update versions for Docker, Ansible, Puppet and Kubernetes guides
  source/deploying-with-ansible/guide/install-ansible.rst
  source/deploying-with-ansible/reference.rst
  source/deploying-with-kubernetes/kubernetes-conf.rst
  source/deploying-with-kubernetes/kubernetes-upgrade.rst
  source/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/docker/wazuh-container.rst
Labels: ansible, docker, kubernetes, puppet

#2287 Fix a minor typo
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: typo

#2295 Learning Wazuh improvements
  source/learning-wazuh/vuln-detection.rst
Labels: enhancement, operations

#2251 restyle, rephrase, more explanation to the congiguration file added, …
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch.rst
  source/_templates/installations/elastic/common/elastic-multi-node/deploy_certificates.rst
  source/_templates/installations/elastic/common/elastic-multi-node/generate_certificates.rst
  source/_templates/installations/elastic/common/elastic-single-node/configure_elasticsearch.rst
  source/_templates/installations/elastic/deb/disabling_repositories.rst
  source/installation-guide/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
  source/installation-guide/elasticsearch-cluster/elasticsearch-single-node-cluster.rst
Labels: elastic, installation guide, new-docs

#2264 Changes in Installation guige - Wazuh cluster
  source/_templates/installations/elastic/common/configure_filebeat.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat_wazuh_cluster.rst
  source/_templates/installations/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/common/configure_wazuh_master_node.rst
  source/_templates/installations/wazuh/common/configure_wazuh_worker_node.rst
  source/_templates/installations/wazuh/deb/disabling_repositories.rst
  source/installation-guide/wazuh-cluster/wazuh_multi_node_cluster.rst
  source/installation-guide/wazuh-cluster/wazuh_single_node_cluster.rst
Labels: installation guide, new-docs

#2276 Changes in Installation guide - Kibana
  source/_templates/installations/elastic/common/configure_kibana.rst
  source/_templates/installations/elastic/common/generate_new_kibana_certificates.rst
  source/_templates/installations/elastic/deb/disabling_repositories.rst
  source/installation-guide/kibana/index.rst
Labels: elastic, installation guide, new-docs

#2311 [3.11] Rule ID change
  source/learning-wazuh/rdp-brute-force.rst
Labels: enhancement, operations

#1297 Add description for <fts> option in rules syntax
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: new-docs, operations

#1316 Add dequeued_after_close to remoted state file
  source/user-manual/reference/statistics-files/ossec-remoted-state.rst
Labels: new-docs

#2314 FIM synchronization documentation
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/capabilities/file-integrity/fim-synchronization.rst
  source/user-manual/capabilities/file-integrity/index.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: fim-rework

#2027 Add new options to Syscheck documentation
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/capabilities/file-integrity/fim-faq.rst
  source/user-manual/capabilities/file-integrity/fim-synchronization.rst
  source/user-manual/capabilities/file-integrity/index.rst
  source/user-manual/reference/daemons/wazuh-db.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: fim-rework

#1823 Update rootcheck.rst
  source/user-manual/reference/ossec-conf/rootcheck.rst
Labels: missing-docs, operations

#1863 Remove wrong <regex> option on <description> field example
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: invalid

#2324 [3.12] Updated redirects.js with new and missing redirections
  source/_static/js/redirects.js
Labels: bug

#2329 Improved grammar on fim-synchronization.rst
  source/user-manual/capabilities/file-integrity/fim-synchronization.rst
Labels: typo

#2292 Reworks Docker Documentation
  source/docker/container-usage.rst
  source/docker/wazuh-container.rst
Labels: operations

#2323 Updating wazuh-agent ansible role info
  source/deploying-with-ansible/guide/install-wazuh-agent.rst
  source/deploying-with-ansible/reference.rst
  source/deploying-with-ansible/roles/wazuh-agent.rst
Labels: ansible

#2334 Add code-block xml to fim synchronization configuration
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
Labels: fim-rework

#1563 Add missing systemctl command in deploying-with-ansible/install-wazuh-manager.rst
  source/deploying-with-ansible/guide/install-wazuh-manager.rst
Labels: community

#1761 wazuh::server renamed ::manager, ossec_smtp prefix
  source/deploying-with-puppet/wazuh-puppet-module/index.rst
Labels: community

#2340 Learning wazuh 3.12 fixes
  source/learning-wazuh/build-lab/install-elastic-stack.rst
  source/learning-wazuh/build-lab/install-wazuh-manager.rst
  source/learning-wazuh/build-lab/launch-ec2-instances.rst
  source/learning-wazuh/build-lab/xpack-security-setup.rst
Labels: operations
