Repository wazuh/wazuh-documentation, pull requests merged in 2021-06, with the labels that each got.

#3916 Add new option to configure the API requests timeout
  source/user-manual/api/configuration.rst
  source/user-manual/api/getting-started.rst
Labels: API

#3925 [develop] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh_agent.rst
  source/getting-started/components/wazuh_server.rst
  source/getting-started/use_cases/active_response.rst
  source/getting-started/use_cases/cloud_security.rst
  source/getting-started/use_cases/configuration_assessment.rst
  source/getting-started/use_cases/file_integrity.rst
  source/getting-started/use_cases/log_analysis.rst
  source/getting-started/use_cases/regulatory_compliance.rst
  source/getting-started/use_cases/system_inventory.rst
  source/getting-started/use_cases/vulnerability_detection.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/host-verification-registration.rst
Labels: SEO

#3926 [4.1] Added new custom extension for the images
  .gitignore
  requirements.txt
  source/_exts/wazuh-doc-images.py
  source/_exts/wazuh-doc-images/img/close.png
  source/_exts/wazuh-doc-images/img/loading.gif
  source/_exts/wazuh-doc-images/img/next.png
  source/_exts/wazuh-doc-images/img/prev.png
  source/_exts/wazuh-doc-images/wazuh-light-box.css
  source/_exts/wazuh-doc-images/wazuh-light-box.js
  source/_static/css/style.css
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh_agent.rst
  source/getting-started/components/wazuh_server.rst
  source/getting-started/use_cases/active_response.rst
  source/getting-started/use_cases/cloud_security.rst
  source/getting-started/use_cases/configuration_assessment.rst
  source/getting-started/use_cases/file_integrity.rst
  source/getting-started/use_cases/log_analysis.rst
  source/getting-started/use_cases/regulatory_compliance.rst
  source/getting-started/use_cases/system_inventory.rst
  source/getting-started/use_cases/vulnerability_detection.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/host-verification-registration.rst
Labels: SEO

#3927 [4.0] Added new custom extension for the images
  .gitignore
  requirements.txt
  source/_exts/wazuh-doc-images.py
  source/_exts/wazuh-doc-images/img/close.png
  source/_exts/wazuh-doc-images/img/loading.gif
  source/_exts/wazuh-doc-images/img/next.png
  source/_exts/wazuh-doc-images/img/prev.png
  source/_exts/wazuh-doc-images/wazuh-light-box.css
  source/_exts/wazuh-doc-images/wazuh-light-box.js
  source/_static/css/style.css
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh_agent.rst
  source/getting-started/components/wazuh_server.rst
  source/getting-started/use_cases/active_response.rst
  source/getting-started/use_cases/cloud_security.rst
  source/getting-started/use_cases/configuration_assessment.rst
  source/getting-started/use_cases/file_integrity.rst
  source/getting-started/use_cases/log_analysis.rst
  source/getting-started/use_cases/regulatory_compliance.rst
  source/getting-started/use_cases/system_inventory.rst
  source/getting-started/use_cases/vulnerability_detection.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/host-verification-registration.rst
Labels: SEO

#3928 [3.13] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh_agent.rst
  source/getting-started/components/wazuh_server.rst
  source/getting-started/use_cases/active_response.rst
  source/getting-started/use_cases/cloud_security.rst
  source/getting-started/use_cases/configuration_assessment.rst
  source/getting-started/use_cases/file_integrity.rst
  source/getting-started/use_cases/log_analysis.rst
  source/getting-started/use_cases/regulatory_compliance.rst
  source/getting-started/use_cases/system_inventory.rst
  source/getting-started/use_cases/vulnerability_detection.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/host-verification-registration.rst
Labels: SEO

#3929 [3.12] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/host-verification-registration.rst
Labels: SEO

#3930 [3.11] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/manager-verification/agent-verification-registration.rst
  source/user-manual/registering/manager-verification/manager-verification-registration.rst
Labels: SEO

#3931 [3.10] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/development/wazuh-cluster.rst
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/registering/manager-verification/agent-verification-registration.rst
  source/user-manual/registering/manager-verification/manager-verification-registration.rst
Labels: SEO

#3932 [3.9] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
  source/user-manual/registering/manager-verification/agent-verification-registration.rst
  source/user-manual/registering/manager-verification/manager-verification-registration.rst
Labels: SEO

#3933 [3.8] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/kibana-app/features/query-configuration.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3934 [3.7] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/kibana-app/features/query-configuration.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3935 [3.6] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3936 [3.5] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3937 [3.4] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3938 [3.3] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3939 [3.2] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
  source/user-manual/manager/wazuh-cluster.rst
Labels: SEO

#3940 [3.1] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
Labels: SEO

#3941 [3.0] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
Labels: SEO

#3942 [2.1] Fixed custom extension for images
  source/_exts/wazuh-doc-images.py
  source/_static/css/style.css
  source/getting-started/architecture.rst
  source/getting-started/components.rst
  source/getting-started/use-cases.rst
  source/index.rst
Labels: SEO

#3945 Corrected typo in configuration example for Red Hat's offline update
  source/user-manual/capabilities/vulnerability-detection/offline_update.rst
Labels: typo

#3897 Current IG_ Elasticsearch multi-node editorial review
  source/_templates/installations/elastic/common/before_installation.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_initial.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_subsequent.rst
  source/_templates/installations/elastic/common/elastic-multi-node/deploy_certificates.rst
  source/_templates/installations/elastic/common/elastic-multi-node/generate_certificates.rst
  source/_templates/installations/elastic/common/elastic-single-node/generate_deploy_certificates.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
Labels: priority: highest, type: refactor

#3913 Added syscheck fields specification and example rules
  source/user-manual/capabilities/file-integrity/fim-fields-rule-mapping.rst
  source/user-manual/capabilities/file-integrity/index.rst
Labels: core/fim, missing docs

#3991 IG rework based on feedback
  source/_templates/installations/elastic/common/certificates-aio.rst
  source/_templates/installations/elastic/common/elastic-multi-node/generate_certificates.rst
  source/_templates/installations/elastic/common/elastic-single-node/generate_deploy_certificates.rst
  source/installation-guide/index.rst
  source/installation-guide/open-distro/all-in-one-deployment/all_in_one.rst
  source/installation-guide/open-distro/all-in-one-deployment/index.rst
  source/installation-guide/open-distro/all-in-one-deployment/unattended-installation.rst
  source/installation-guide/open-distro/distributed-deployment/index.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/elasticsearch-cluster/elasticsearch-single-node-cluster.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/index.rst
  source/installation-guide/open-distro/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh_multi_node_cluster.rst
  source/installation-guide/open-distro/distributed-deployment/unattended/index.rst
  source/installation-guide/open-distro/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.rst
  source/installation-guide/open-distro/distributed-deployment/unattended/unattended-wazuh-cluster-installation.rst
  source/installation-guide/open-distro/index.rst
  source/installation-guide/requirements.rst
  source/virtual-machine/virtual-machine.rst
Labels: type: refactor

#3955 [develop] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3956 [4.1] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3957 [4.0] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3958 [3.13] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3959 [3.12] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3960 [3.11] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3961 [3.10] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3962 [3.9] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3963 [3.8] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3964 [3.7] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3965 [3.6] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3966 [3.5] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3967 [3.4] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3968 [3.3] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3969 [3.2] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3970 [3.1] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3971 [3.0] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO

#3972 [2.1] Preload theme assets
  source/_static/css/wazuh-icons.css
  source/_static/fonts/wazuh-icons.woff2
  source/_static/js/bootstrap.min.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/_themes/wazuh_doc_theme/searchbar.html
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css
  source/_themes/wazuh_doc_theme/static/css/bootstrap.min.css.map
  source/_themes/wazuh_doc_theme/static/css/google-fonts.css
  source/_themes/wazuh_doc_theme/static/js/bootstrap.min.js.map
  source/conf.py
Labels: SEO
