Repository wazuh/wazuh-documentation, pull requests merged in 2021-02, with the labels that each got.

#3358 Moved USER_CA_STORE from Manager section to Global
  source/user-manual/reference/unattended-installation.rst
Labels: operations

#3323 Update API and RBAC documentation with the new /rules/files/{filename} endpoints
  source/user-manual/api/equivalence.rst
  source/user-manual/api/rbac/reference.rst
Labels: API

#3370 Update RBAC documentation with the new configuration endpoints
  source/user-manual/api/rbac/reference.rst
Labels: API

#3390 [4.1] SEO and UX improvements
  source/_static/css/style-redirect.css
  source/_static/css/style.css
  source/_static/guide-assets/favicon.ico
  source/_static/guide-assets/guide-bg.png
  source/_static/guide-assets/guide.css
  source/_static/guide-assets/guide.js
  source/_static/guide-assets/wazuh_logo_w.png
  source/_static/img/deprecated-pic.png
  source/_static/js/moved-content.js
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_templates/guide.html
  source/_templates/moved-content.html
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3391 [4.0] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3392 [3.13] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3394 [3.11] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3393 [3.12] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3395 [3.10] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3396 [3.9] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3397 [3.8] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3398 [3.7] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3399 [3.6] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3400 [3.5] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3401 [3.4] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3403 [3.2] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3404 [3.1] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3405 [3.0] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3406 [2.1] SEO and UX improvements
  source/_static/css/style.css
  source/_static/img/deprecated-pic.png
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_static/js/version-selector.js
  source/_themes/wazuh_doc_theme/header.html
  source/_themes/wazuh_doc_theme/layout.html
  source/conf.py
Labels: SEO

#3218 Add max_fps option to the FIM documentation.
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: core/fim

#3206 [core-6650] Installing from sources - update based on latest changes
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
Labels: core/syscollector

#3381 Add ip_update_interval to client configuration
  source/user-manual/reference/ossec-conf/client.rst
Labels: user manual

#3429 Update make deps references
  source/development/makefile.rst
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.rst
Labels: installation guide

#3471 4.1 fix macOS deployment variables
  source/installation-guide/wazuh-agent/deployment_variables/deployment_variables_macos.rst
Labels: operations

#3389 Updated documentation for protocol in remoted
  source/user-manual/reference/ossec-conf/remote.rst
Labels: core/remoted
