Repository wazuh/wazuh-documentation, pull requests merged in 2021-09, with the labels that each got.

#4192 Values for opendistro node structure in configuration file - Wazuh Indexer Recomendation Action
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_initial.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_subsequent.rst
  source/installation-guide/wazuh-indexer/step-by-step.rst
Labels: priority: low, type: refactor

#4215 Changing node_name to NODE_NAME in the installation guide
  source/_templates/installations/elastic/common/copy_certificates_filebeat.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat_wazuh_cluster.rst
  source/_templates/installations/elastic/common/elastic-multi-node/deploy_certificates.rst
  source/_templates/installations/elastic/common/elastic-multi-node/generate_certificates.rst
  source/_templates/installations/elastic/common/elastic-single-node/generate_deploy_certificates.rst
  source/_templates/installations/elastic/common/generate_new_kibana_certificates.rst
Labels: priority: low, type: refactor

#4225 Skip message if wazuh server is going to be installed in the same host.
  source/installation-guide/wazuh-server/step-by-step.rst
Labels: priority: low, type: refactor

#4201 Fix syscheck synchronization examples v4.2
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: priority: medium, type: refactor

#4202 Fix syscheck synchronization examples v3.13
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: priority: medium, type: refactor

#3040 Adding Wazuh Cloud Service docs
  source/_static/js/redirects.js
  source/_static/js/style.js
  source/_templates/cloud-api-redoc.html
  source/cloud-service/account-billing/add-billing-details.rst
  source/cloud-service/account-billing/billing-faq.rst
  source/cloud-service/account-billing/billing-history.rst
  source/cloud-service/account-billing/index.rst
  source/cloud-service/account-billing/stop-charges.rst
  source/cloud-service/account-billing/update-billing.rst
  source/cloud-service/account-billing/user-settings.rst
  source/cloud-service/apis/authentication.rst
  source/cloud-service/apis/index.rst
  source/cloud-service/apis/reference.rst
  source/cloud-service/cli/index.rst
  source/cloud-service/cold-storage/index.rst
  source/cloud-service/getting-started/index.rst
  source/cloud-service/getting-started/starting-faq.rst
  source/cloud-service/glossary.rst
  source/cloud-service/index.rst
  source/cloud-service/your-environment/agents-without-internet.rst
  source/cloud-service/your-environment/cancel-environment.rst
  source/cloud-service/your-environment/configure-email.rst
  source/cloud-service/your-environment/index.rst
  source/cloud-service/your-environment/manage-auth.rst
  source/cloud-service/your-environment/monitor-environment-usage.rst
  source/cloud-service/your-environment/send-syslog-data.rst
  source/cloud-service/your-environment/technical-faq.rst
  source/conf.py
  source/images/cloud-service/nginx-scheme.png
  source/index.rst
Labels: new docs

#4237 Wazuh commits
  source/migrating-from-ossec/index.rst
Labels: priority: high, type: refactor

#4209 Fix RPM package generation directory
  source/development/packaging/generate-rpm-package.rst
Labels: priority: medium

#4226 Replace packages generation path
  source/development/packaging/generate-aix-package.rst
  source/development/packaging/generate-deb-package.rst
  source/development/packaging/generate-hpux-package.rst
Labels: priority: medium, type: refactor

#4254 Separate Cloud service-GS content into separate sections
  source/_static/js/redirects.js
  source/cloud-service/getting-started/access-wazuh-wui.rst
  source/cloud-service/getting-started/index.rst
  source/cloud-service/getting-started/register-agents.rst
  source/cloud-service/getting-started/sign-up-trial.rst
  source/cloud-service/getting-started/starting-faq.rst
  source/cloud-service/your-environment/agents-without-internet.rst
  source/cloud-service/your-environment/manage-auth.rst
Labels: type: refactor

#4245 Documentation 4.0 Virtual Machine download OVA text proposal
  source/virtual-machine/virtual-machine.rst
Labels: priority: low, type: refactor

#4243 Documentation 4.1 Virtual Machine download OVA text proposal
  source/virtual-machine/virtual-machine.rst
Labels: priority: low, type: refactor

#4247 Documentation 3.13 Virtual Machine download OVA text proposal
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4249 Documentation 3.12 Virtual Machine download OVA text proposal
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4251 Documentation 3.11 Virtual Machine download OVA text proposal
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4253 Documentation 3.10 Virtual Machine download OVA text proposal
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4218 Clarify that multiple `if_sid` values are allowed
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: medium, type: refactor

#4234 Steps proposal Cluster Initialization
  source/installation-guide/wazuh-indexer/step-by-step.rst
Labels: priority: low, type: refactor

#4230 Steps simplified for deploying certificates
  source/_templates/installations/elastic/common/copy_certificates_filebeat_wazuh_cluster.rst
  source/_templates/installations/elastic/common/elastic-multi-node/deploy_certificates.rst
  source/_templates/installations/elastic/common/generate_new_kibana_certificates.rst
Labels: priority: low, type: refactor

#4127 Update supported operating systems list
  source/installation-guide/requirements.rst
Labels: priority: medium, type: refactor

#4278 Update supported OS list simplified
  source/installation-guide/requirements.rst
Labels: priority: medium

#4135 Added remote upgrading for MacOS agents
  source/development/packaging/generate-wpk-package.rst
  source/user-manual/agents/remote-upgrading/agent-upgrade-module.rst
  source/user-manual/agents/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
Labels: wpk

#4259 Documentation 3.10 Virtual Machine OVA Update Information
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4261 Documentation 3.11 Virtual Machine OVA Update Information
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4263 Documentation 3.12 Virtual Machine OVA Update Information
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4265 Documentation 3.13 Virtual Machine OVA Update Information
  source/installation-guide/virtual-machine.rst
Labels: priority: low, type: refactor

#4279 Changing option same_source_ip by same_srcip - Docu 3.13
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: medium, type: refactor

#4280 Changing option same_source_ip by same_srcip - Docu 4.0
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: medium, type: refactor

#4281 Changing option same_source_ip by same_srcip - Docu 4.1
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: medium, type: refactor

#4282 Changing option same_source_ip by same_srcip - Docu 4.2
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: medium, type: refactor

#4293 Scaping character $ in repo name with \- Docu 4.2
  source/_templates/installations/wazuh/yum/add_repository.rst
Labels: priority: high, type: refactor

#4296 Fix SMTP certificate configuration on Ubuntu
  source/user-manual/manager/manual-email-report/smtp_authentication.rst
Labels: user manual, type: bug

#4274 3.13 Documentation: Installing-Fileabeat-Amazon-Linux changing installing filebeat hyperlink text
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.rst
Labels: priority: low, type: refactor

#4272 3.12 Documentation: Installing-Fileabeat-Amazon-Linux changing installing filebeat hyperlink text
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.rst
Labels: priority: low, type: refactor

#4270 3.11 Documentation: Installing-Fileabeat-Amazon-Linux changing installing filebeat hyperlink text
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.rst
Labels: priority: low, type: refactor

#4268 3.10 Documentation: Installing-Fileabeat-Amazon-Linux changing installing filebeat hyperlink text
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.rst
Labels: priority: low, type: refactor

#4301 Updated the required port for Kibana
  source/getting-started/architecture.rst
Labels: operations

#4303 Adding more changes to wazuh repo
  source/_templates/installations/basic/wazuh/yum/add_repository.rst
  source/_templates/installations/basic/wazuh/yum/add_repository_aio.rst
  source/_templates/installations/wazuh/yum/add_repository_aio.rst
  source/_templates/installations/wazuh/yum/add_repository_elastic_cluster.rst
  source/_templates/installations/wazuh/yum/add_repository_kibana.rst
  source/_templates/installations/wazuh/yum/add_repository_wazuh_server.rst
  source/upgrade-guide/upgrading-agent.rst
Labels: priority: high, type: refactor

#4322 Docu 3.10 - Changing text for pointing Filebeat installation from sources.
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_sources_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_sources_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_sources_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_sources_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_sources_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.rst
Labels: priority: low, type: refactor

#4320 Docu 3.11 - Changing text for pointing Filebeat installation from sources.
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_sources_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_sources_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_sources_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_sources_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_sources_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.rst
Labels: priority: low, type: refactor

#4318 Docu 3.12 - Changing text for pointing Filebeat installation from sources.
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_sources_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_sources_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_sources_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_sources_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_sources_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.rst
Labels: priority: low, type: refactor

#4316 Docu 3.13 - Changing text for pointing Filebeat installation from sources.
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_sources_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_sources_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_sources_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_sources_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_sources_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.rst
Labels: priority: low, type: refactor

#4331 Fixed two tables under the disk_quota section
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: operations

#4266 Include Getting started with Wazuh RBAC in Docu
  source/_static/js/redirects.js
  source/images/kibana-app/0.1.overview_framework_group.png
  source/images/kibana-app/0.2.overview_us-west_group.png
  source/images/kibana-app/0.3.mapped_users.png
  source/images/kibana-app/0.4.security_policies.png
  source/images/kibana-app/0.5.framework_agents.png
  source/images/kibana-app/0.6.role_edit.png
  source/images/kibana-app/0.7.login_1.png
  source/images/kibana-app/0.8.roles_mapping_create.png
  source/images/kibana-app/rbac_scheme.png
  source/images/kibana-app/rbac_scheme2.png
  source/user-manual/kibana-app/index.rst
  source/user-manual/kibana-app/wazuh-rbac.rst
Labels: priority: medium, type: infrastructure

#4334 Logcollector IP refresh time.
  source/user-manual/reference/internal-options.rst
Labels: core/logcollector

#4312 Changing click here Docu 3.12 - Download packages
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_packages_amazon.rst
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_packages_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_packages_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_packages_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_packages_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_packages_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.rst
Labels: priority: low, type: refactor

#4314 Changing click here Docu 3.13 - Download packages
  source/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_packages_amazon.rst
  source/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.rst
  source/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.rst
  source/installation-guide/installing-wazuh-manager/linux/fedora/wazuh_server_packages_fedora.rst
  source/installation-guide/installing-wazuh-manager/linux/opensuse/wazuh_server_packages_opensuse.rst
  source/installation-guide/installing-wazuh-manager/linux/oracle/wazuh_server_packages_oracle.rst
  source/installation-guide/installing-wazuh-manager/linux/rhel/wazuh_server_packages_rhel.rst
  source/installation-guide/installing-wazuh-manager/linux/suse/wazuh_server_packages_suse.rst
  source/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.rst
Labels: priority: low, type: refactor

#4381 New options added to the table.
  source/user-manual/elasticsearch/elastic_tuning.rst
Labels: priority: low, type: refactor

#4291 Scaping character $ in repo name with \ - Docu 4.1
  source/_templates/installations/basic/wazuh/yum/add_repository.rst
  source/_templates/installations/basic/wazuh/yum/add_repository_aio.rst
  source/_templates/installations/wazuh/yum/add_repository.rst
  source/_templates/installations/wazuh/yum/add_repository_aio.rst
  source/_templates/installations/wazuh/yum/add_repository_elastic_cluster.rst
  source/_templates/installations/wazuh/yum/add_repository_kibana.rst
  source/_templates/installations/wazuh/yum/add_repository_wazuh_server.rst
Labels: priority: high, type: refactor

#4227 Added changes to syscheck clear's related endpoints
  source/user-manual/api/equivalence.rst
Labels: API

#4396 Fix wazuh-logcollector.state default interval value
  source/user-manual/reference/statistics-files/wazuh-logcollector-state.rst
Labels: invalid, user manual, core/logcollector
