Repository wazuh/wazuh-documentation, pull requests merged in 2021-12, with the labels that each got.

#4665 Remove wrong RN 4_2_0 and 4_2_1 redirections
  source/_static/js/redirects.js
Labels: priority: high

#4653 Various changes to Installation guide
  source/_templates/installations/basic/elastic/common/configure_filebeat.rst
  source/_templates/installations/basic/elastic/common/configure_filebeat_cluster.rst
  source/_templates/installations/elastic/common/configure_filebeat.rst
  source/_templates/installations/elastic/common/configure_filebeat_all_in_one.rst
  source/_templates/installations/elastic/common/configure_filebeat_cluster.rst
  source/_templates/installations/elastic/common/configure_kibana.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat_un.rst
  source/_templates/installations/elastic/common/copy_certificates_filebeat_wazuh_cluster.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_initial.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_subsequent.rst
  source/_templates/installations/elastic/common/elastic-multi-node/deploy_certificates.rst
  source/_templates/installations/elastic/common/elastic-multi-node/generate_certificates.rst
  source/_templates/installations/elastic/common/elastic-single-node/generate_deploy_certificates.rst
  source/_templates/installations/elastic/common/generate_new_kibana_certificates.rst
  source/_templates/installations/elastic/common/install_elastic.rst
  source/_templates/installations/elastic/yum/install_filebeat.rst
  source/_templates/installations/elastic/yum/install_kibana.rst
  source/_templates/installations/wazuh/yum/add_repository_elastic_cluster.rst
  source/_templates/installations/wazuh/yum/add_repository_kibana.rst
  source/_templates/installations/wazuh/yum/add_repository_wazuh_server.rst
  source/_templates/installations/wazuh/yum/install_wazuh_manager.rst
  source/installation-guide/elasticsearch/step-by-step.rst
  source/installation-guide/elasticsearch/unattended.rst
  source/installation-guide/index.rst
  source/installation-guide/kibana/step-by-step.rst
  source/installation-guide/kibana/unattended.rst
  source/installation-guide/wazuh-server/step-by-step.rst
  source/installation-guide/wazuh-server/unattended.rst
  source/quickstart.rst
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.rst
Labels: priority: high

#4675 Add Log4j 2 mitigation steps
  source/_templates/installations/basic/elastic/common/enable_elasticsearch.rst
  source/_templates/installations/elastic/common/enable_elasticsearch.rst
  source/learning-wazuh/build-lab/install-elastic-stack.rst
Labels: priority: high

#4693 Fix GCC download URL for Solaris installation from sources
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
Labels: installation guide, type: bug

#4691 Change components name references in Getting started guide
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh-dashboard.rst
  source/getting-started/components/wazuh-indexer.rst
  source/getting-started/components/wazuh-server.rst
  source/getting-started/use-cases/file-integrity.rst
  source/getting-started/use-cases/log-analysis.rst
  source/getting-started/use-cases/security_analytics.rst
  source/installation-guide/index.rst
Labels: priority: medium

#4686 Enhance the Getting started sections V5.0
  source/deployment-options/index.rst
  source/getting-started/index.rst
Labels: priority: high, type: refactor

#4694 Cluster configs rewording
  source/installation-guide/index.rst
  source/installation-guide/wazuh-dashboard/index.rst
  source/installation-guide/wazuh-indexer/index.rst
  source/installation-guide/wazuh-server/index.rst
Labels: priority: high

#4698 Fix code line highlight out-of-range warnings
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_initial.rst
  source/_templates/installations/elastic/common/elastic-multi-node/configure_elasticsearch_subsequent.rst
Labels: priority: medium

#4696 Review of the "Installation guide rework"
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh-dashboard.rst
  source/getting-started/components/wazuh-indexer.rst
  source/getting-started/components/wazuh-server.rst
  source/getting-started/index.rst
  source/installation-guide/index.rst
  source/installation-guide/wazuh-dashboard/index.rst
  source/installation-guide/wazuh-indexer/index.rst
  source/installation-guide/wazuh-server/index.rst
  source/quickstart.rst
Labels: priority: high, type: refactor

#4700 Fix link to SCA examples in repo
  source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
Labels: priority: medium
