Repository wazuh/wazuh-documentation, pull requests merged in 2022-01, with the labels that each got.

#4711 Fix URLs and change Wazuh components names
  source/deployment-options/index.rst
Labels: installation guide, priority: high

#4725 Fix Solaris 11 URLs and file name extensions
  source/upgrade-guide/upgrading-agent.rst
Labels: priority: medium

#4602 New and deprecated features since prior to 4.x (docs v4.2)
  source/amazon/index.rst
  source/azure/index.rst
  source/docker-monitor/index.rst
  source/gcp/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.rst
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/agents/remote-upgrading/index.rst
  source/user-manual/api/queries.rst
  source/user-manual/capabilities/agent-key-polling.rst
  source/user-manual/capabilities/auditing-whodata/index.rst
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/capabilities/fluent-forwarder.rst
  source/user-manual/capabilities/osquery.rst
  source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst
  source/user-manual/capabilities/sec-config-assessment/index.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/capabilities/virustotal-scan/index.rst
  source/user-manual/capabilities/vulnerability-detection/index.rst
  source/user-manual/manager/manual-integration.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/daemons/clusterd.rst
  source/user-manual/reference/daemons/wazuh-agentd.rst
  source/user-manual/reference/daemons/wazuh-db.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/auth.rst
  source/user-manual/reference/ossec-conf/client-buffer.rst
  source/user-manual/reference/ossec-conf/client.rst
  source/user-manual/reference/ossec-conf/cluster.rst
  source/user-manual/reference/ossec-conf/commands.rst
  source/user-manual/reference/ossec-conf/fluent-forward.rst
  source/user-manual/reference/ossec-conf/gcp-pubsub.rst
  source/user-manual/reference/ossec-conf/global.rst
  source/user-manual/reference/ossec-conf/labels.rst
  source/user-manual/reference/ossec-conf/localfile.rst
  source/user-manual/reference/ossec-conf/sca.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
  source/user-manual/reference/ossec-conf/wodle-ciscat.rst
  source/user-manual/reference/ossec-conf/wodle-command.rst
  source/user-manual/reference/ossec-conf/wodle-docker.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
  source/user-manual/reference/tools/agent-groups.rst
  source/user-manual/reference/tools/agent-upgrade.rst
  source/user-manual/reference/tools/cluster-control.rst
  source/user-manual/reference/tools/fim-migrate.rst
  source/user-manual/ruleset/cdb-list.rst
  source/user-manual/ruleset/json-decoder.rst
  source/user-manual/ruleset/ruleset-xml-syntax/decoders.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: priority: high

#4650 Add information about `only_logs_after` and `reparse` in AWS integration's documentation
  source/amazon/services/prerequisites/considerations.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: aws, external_integrations

#4633 Fix AWS load balancers `Path to logs` value and add footnote
  source/amazon/services/supported-services/index.rst
Labels: typo, external_integrations

#4732 Update lesson to Suricata 6.0
  source/learning-wazuh/suricata.rst
Labels: priority: medium

#4760 Fix SCA example rule
  source/user-manual/capabilities/sec-config-assessment/creating-custom-policies.rst
Labels: type: bug, core/sca

#4765 Add new Wazuh on Docker and Wazuh on Kubernetes installation indexes
  source/deployment-options/deploying-with-kubernetes/index.rst
  source/deployment-options/docker/index.rst
Labels: installation guide, priority: medium

#4772 Adapt steps for Wazuh step-by-step installation
  source/_templates/installations/indexer/common/configure_indexer_nodes.rst
  source/_templates/installations/indexer/common/deploy_certificates.rst
  source/_templates/installations/indexer/common/enable_indexer.rst
  source/_templates/installations/indexer/common/generate_certificates.rst
  source/_templates/installations/indexer/common/install-indexer.rst
  source/_templates/installations/indexer/deb/add_repository.rst
  source/_templates/installations/indexer/yum/add_repository.rst
  source/_templates/installations/indexer/zypp/add_repository.rst
  source/installation-guide/wazuh-indexer/index.rst
  source/installation-guide/wazuh-indexer/step-by-step.rst
  source/installation-guide/wazuh-indexer/unattended.rst
Labels: installation guide, priority: high

#4776 Documentation enhancement works II
  source/deployment-options/deploying-with-kubernetes/index.rst
  source/deployment-options/docker/index.rst
Labels: priority: high, type: infrastructure, type: refactor

#4769 Add support for Azure module in agents
  source/user-manual/reference/ossec-conf/index.rst
Labels: ossec.conf, azure

#4788 3865 new indexer installation steps
  source/_templates/installations/common/apt/install-dependencies.rst
  source/_templates/installations/common/deb/add-repository.rst
  source/_templates/installations/common/deb/add_repository.rst
  source/_templates/installations/common/yum/add-repository.rst
  source/_templates/installations/common/yum/add_repository.rst
  source/_templates/installations/common/yum/install-dependencies.rst
  source/_templates/installations/common/zypp/add_repository.rst
  source/_templates/installations/common/zypp/install-dependencies.rst
  source/_templates/installations/dashboard/apt/add_repository.rst
  source/_templates/installations/dashboard/yum/add_repository.rst
  source/_templates/installations/dashboard/zypp/add_repository.rst
  source/_templates/installations/indexer/common/configure_indexer_nodes.rst
  source/_templates/installations/indexer/common/deploy_certificates.rst
  source/_templates/installations/indexer/common/enable_indexer.rst
  source/_templates/installations/indexer/common/generate_certificates.rst
  source/installation-guide/wazuh-indexer/step-by-step.rst
Labels: installation guide, priority: high
