Repository wazuh/wazuh-documentation, pull requests merged in 2022-11, with the labels that each got.

#5712 Fix typo in the aws-s3 wodle configuration documentation
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: hacktoberfest-accepted

#5737 Fix to correctly generate the macOS WPK manually
  source/user-manual/agents/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.rst
Labels: wpk, type: bug

#5744 Add storage in disk option for remoted groups generation
  source/user-manual/reference/internal-options.rst
Labels: core/remoted

#5751 Wazuh 4.3.10 release notes and versions update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/installation-guide/packages-list.rst
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-3-10.rst
  source/user-manual/agents/remote-upgrading/wpk-list.rst
Labels: release notes, priority: high

#5756 Update the section: Installation guide
  source/_templates/installations/dashboard/deploy_certificates.rst
  source/_templates/installations/filebeat/opensearch/configure_filebeat.rst
  source/_templates/installations/indexer/common/configure_indexer_nodes.rst
  source/_templates/installations/indexer/common/deploy_certificates.rst
  source/_templates/installations/indexer/common/generate_certificates.rst
  source/_templates/installations/indexer/common/install-dependencies.rst
  source/_templates/installations/manager/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/common/disable_wazuh_agent_service.rst
  source/_templates/installations/wazuh/common/disable_wazuh_manager_service.rst
  source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/installation-guide/index.rst
  source/installation-guide/wazuh-agent/index.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-aix.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-hpux.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-linux.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-macos.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-solaris.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-windows.rst
  source/installation-guide/wazuh-dashboard/index.rst
  source/installation-guide/wazuh-dashboard/installation-assistant.rst
  source/installation-guide/wazuh-dashboard/step-by-step.rst
  source/installation-guide/wazuh-indexer/index.rst
  source/installation-guide/wazuh-indexer/installation-assistant.rst
  source/installation-guide/wazuh-indexer/step-by-step.rst
  source/installation-guide/wazuh-server/index.rst
  source/installation-guide/wazuh-server/installation-assistant.rst
  source/installation-guide/wazuh-server/step-by-step.rst
Labels: priority: high, documentation

#5761 Update the SSO documentation
  source/images/single-sign-on/okta/09-saml-settings-section.png
  source/user-manual/wazuh-dashboard/single-sign-on/azure-active-directory.rst
  source/user-manual/wazuh-dashboard/single-sign-on/okta.rst
Labels: priority: high, documentation

#5763 Update the SSO documentation - Iteration 2
  source/images/single-sign-on/okta/09-saml-settings-section.png
Labels: priority: high, documentation

#5721 Change the links on the section: Restore the Wazuh alerts from Wazuh 2.x
  source/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.rst
Labels: priority: high, documentation

#5723 Editorial and grammar review: User manual
  source/_templates/installations/basic/wazuh/yum/uninstall_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/yum/uninstall_wazuh_manager_api.rst
  source/_templates/installations/basic/wazuh/zypp/uninstall_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/zypp/uninstall_wazuh_manager_api.rst
  source/cloud-service/your-environment/manage-auth.rst
  source/user-manual/agents/remote-upgrading/agent-upgrade-module.rst
  source/user-manual/elasticsearch/configure-indices.rst
  source/user-manual/elasticsearch/elastic-tuning.rst
  source/user-manual/elasticsearch/elasticsearch.rst
  source/user-manual/elasticsearch/troubleshooting.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/daemons/wazuh-analysisd.rst
  source/user-manual/reference/daemons/wazuh-authd.rst
  source/user-manual/reference/daemons/wazuh-db.rst
  source/user-manual/reference/daemons/wazuh-integratord.rst
  source/user-manual/reference/daemons/wazuh-modulesd.rst
  source/user-manual/reference/internal-options.rst
  source/user-manual/reference/ossec-conf/active-response.rst
  source/user-manual/reference/ossec-conf/agent-upgrade.rst
  source/user-manual/reference/ossec-conf/alerts.rst
  source/user-manual/reference/ossec-conf/auth.rst
  source/user-manual/reference/ossec-conf/client-buffer.rst
  source/user-manual/reference/ossec-conf/client.rst
  source/user-manual/reference/ossec-conf/cluster.rst
  source/user-manual/reference/ossec-conf/commands.rst
  source/user-manual/reference/ossec-conf/email-alerts.rst
  source/user-manual/reference/ossec-conf/fluent-forward.rst
  source/user-manual/reference/ossec-conf/gcp-bucket.rst
  source/user-manual/reference/ossec-conf/index.rst
  source/user-manual/reference/ossec-conf/rootcheck.rst
  source/user-manual/reference/ossec-conf/rule-test.rst
  source/user-manual/reference/ossec-conf/ruleset.rst
  source/user-manual/reference/ossec-conf/sca.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
  source/user-manual/reference/ossec-conf/syslog-output.rst
  source/user-manual/reference/ossec-conf/task-manager.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
  source/user-manual/reference/ossec-conf/wodle-agent-key-polling.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
  source/user-manual/reference/ossec-conf/wodle-ciscat.rst
  source/user-manual/reference/ossec-conf/wodle-command.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
  source/user-manual/reference/tools/agent-control.rst
  source/user-manual/reference/tools/agent-upgrade.rst
  source/user-manual/reference/tools/update-ruleset.rst
  source/user-manual/reference/tools/wazuh-control.rst
  source/user-manual/reference/unattended-installation.rst
  source/user-manual/securing-wazuh/opendistro.rst
  source/user-manual/securing-wazuh/wazuh-indexer.rst
  source/user-manual/wazuh-dashboard/config-file.rst
  source/user-manual/wazuh-dashboard/rbac.rst
  source/user-manual/wazuh-dashboard/settings.rst
  source/user-manual/wazuh-dashboard/single-sign-on/azure-active-directory.rst
  source/user-manual/wazuh-dashboard/single-sign-on/google.rst
  source/user-manual/wazuh-dashboard/single-sign-on/onelogin.rst
  source/user-manual/wazuh-dashboard/single-sign-on/pingone.rst
  source/user-manual/wazuh-dashboard/troubleshooting.rst
Labels: priority: high, documentation

#5715 Update the section: Using Wazuh for PCI DSS compliance
  source/_static/js/redirects.js
  source/images/pci/pci-dss-requirement-10.4.1-1.png
  source/images/pci/pci-dss-requirement-10.4.1-2.png
  source/pci-dss/active-response.rst
  source/pci-dss/analysis-engine.rst
  source/pci-dss/configuration-assessment.rst
  source/pci-dss/dashboard.rst
  source/pci-dss/file-integrity-monitoring.rst
  source/pci-dss/index.rst
  source/pci-dss/log-analysis.rst
  source/pci-dss/malware-detection.rst
  source/pci-dss/system-inventory.rst
  source/pci-dss/vulnerability-detection.rst
Labels: priority: high, documentation

#5767 Declare queue_size global option as deprecated
  source/user-manual/reference/ossec-conf/global.rst
Labels: type: bug, core/analysisd

#5779 Adjust SysV init instructions
  source/_templates/installations/basic/check_services_certificates.rst
  source/_templates/installations/basic/elastic/common/enable_elasticsearch.rst
  source/_templates/installations/basic/elastic/common/enable_filebeat.rst
  source/_templates/installations/basic/elastic/common/enable_kibana.rst
  source/_templates/installations/basic/elastic/common/stop_elasticsearch.rst
  source/_templates/installations/basic/elastic/common/stop_filebeat.rst
  source/_templates/installations/basic/elastic/common/stop_kibana_filebeat.rst
  source/_templates/installations/basic/wazuh/common/restart_wazuh_manager.rst
  source/_templates/installations/basic/wazuh/common/start_wazuh_api.rst
  source/_templates/installations/check_services_certificates.rst
  source/_templates/installations/dashboard/enable_dashboard.rst
  source/_templates/installations/elastic/common/enable_elasticsearch.rst
  source/_templates/installations/elastic/common/enable_filebeat.rst
  source/_templates/installations/elastic/common/enable_kibana.rst
  source/_templates/installations/filebeat/common/enable_filebeat.rst
  source/_templates/installations/indexer/common/enable_indexer.rst
  source/_templates/installations/manager/restart_wazuh_manager.rst
  source/_templates/installations/wazuh/common/check_wazuh_dashboard.rst
  source/_templates/installations/wazuh/common/check_wazuh_manager.rst
  source/_templates/installations/wazuh/common/disable_wazuh_agent_service.rst
  source/_templates/installations/wazuh/common/disable_wazuh_manager_service.rst
  source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst
  source/_templates/installations/wazuh/common/enable_wazuh_manager_service.rst
  source/_templates/installations/wazuh/common/restart_wazuh_manager.rst
  source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
  source/deployment-options/docker/docker-installation.rst
  source/deployment-options/splunk/splunk-wazuh.rst
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
  source/deployment-options/wazuh-from-sources/wazuh-server/index.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-2.x-to-5.x.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/user-manual/elasticsearch/elastic-tuning.rst
Labels: priority: medium, documentation
