Repository wazuh/wazuh-documentation, pull requests merged in 2022-02, with the labels that each got.

#4799 Adapt steps for Wazuh server and dashboard step-by-step installation
  source/_templates/installations/dashboard/deploy_certificates.rst
  source/_templates/installations/filebeat/opensearch/copy_certificates_filebeat_wazuh_cluster.rst
  source/installation-guide/wazuh-dashboard/step-by-step.rst
  source/installation-guide/wazuh-server/step-by-step.rst
Labels: installation guide

#4198 Remove documented `scan_on_start`, and `auto_ignore` deprecated features
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: priority: medium, type: refactor

#4856 Review AWS integration's meta descriptions
  source/amazon/services/prerequisites/S3-bucket.rst
  source/amazon/services/prerequisites/considerations.rst
  source/amazon/services/prerequisites/credentials.rst
  source/amazon/services/prerequisites/dependencies.rst
  source/amazon/services/supported-services/alb.rst
  source/amazon/services/supported-services/cisco-umbrella.rst
  source/amazon/services/supported-services/clb.rst
  source/amazon/services/supported-services/config.rst
  source/amazon/services/supported-services/index.rst
  source/amazon/services/supported-services/inspector.rst
  source/amazon/services/supported-services/kms.rst
  source/amazon/services/supported-services/macie.rst
  source/amazon/services/supported-services/nlb.rst
  source/amazon/services/supported-services/server-access.rst
  source/amazon/services/supported-services/trusted-advisor.rst
  source/amazon/services/supported-services/vpc.rst
  source/amazon/services/supported-services/waf.rst
  source/amazon/services/troubleshooting.rst
Labels: aws, external_integrations

#4857 Review descriptions that only mention buckets in AWS integration
  source/amazon/services/prerequisites/credentials.rst
  source/amazon/services/prerequisites/dependencies.rst
  source/amazon/services/supported-services/cloudwatchlogs.rst
  source/amazon/services/troubleshooting.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: aws, external_integrations

#4861 Enhance Wazuh agent enrollment
  source/user-manual/agent-enrollment/index.rst
  source/user-manual/agent-enrollment/security-options/index.rst
  source/user-manual/agent-enrollment/security-options/using-password-authentication.rst
  source/user-manual/agent-enrollment/via-manager-API/importing-the-key.rst
  source/user-manual/agent-enrollment/via-manager-API/requesting-the-key.rst
Labels: priority: high, type: refactor

#4862 Deprecate unused wdb setting
  source/user-manual/reference/internal-options.rst
Labels: type: refactor

#4884 Adust agent enrollment troubleshooting ul style
  source/_themes/wazuh_doc_theme/css-src/style.css
  source/user-manual/agent-enrollment/index.rst
  source/user-manual/agent-enrollment/security-options/using-password-authentication.rst
  source/user-manual/agent-enrollment/troubleshooting.rst
Labels: priority: medium, type: refactor
