Repository wazuh/wazuh-documentation, pull requests merged in 2022-05, with the labels that each got.

#5139 Add support for Ubuntu Jammy in Vulnerability Detector
  source/learning-wazuh/vuln-detection.rst
  source/proof-of-concept-guide/poc-vulnerability-detection.rst
  source/user-manual/capabilities/vulnerability-detection/compatibility-matrix.rst
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: core/vuln detector, type: feature

#5190 Update quickstart dashboard message 4.3
  source/quickstart.rst
Labels: cicd

#5194 Update default value of 'disabled' tag in cluster reference page
  source/user-manual/reference/ossec-conf/cluster.rst
Labels: user manual, cluster

#4797 Enhance AWS Inspector Classic integration's documentation
  source/amazon/services/supported-services/index.rst
  source/amazon/services/supported-services/inspector.rst
  source/images/aws/aws-inspector-advanced-setup.png
  source/images/aws/aws-inspector-assessment-target.png
  source/images/aws/aws-inspector-assessment-template.png
  source/images/aws/aws-inspector-get-started.png
  source/images/aws/aws-inspector-overview.png
  source/images/aws/aws-inspector-review.png
  source/images/aws/aws-inspector-side-menu.png
Labels: aws, external_integrations

#4793 Rework GCP Audit and DNS logs sections
  source/gcp/supported-services/cloud_audit_logs.rst
  source/gcp/supported-services/dns_queries.rst
  source/images/gcp/gcp-admin-activity.png
  source/images/gcp/gcp-create-sink-button.png
  source/images/gcp/gcp-create-sink-dns.png
  source/images/gcp/gcp-create-sink.png
  source/images/gcp/gcp-data-access.png
  source/images/gcp/gcp-kibana-dns-filtered-logs.png
  source/images/gcp/gcp-kibana-dns-log-filter.png
  source/images/gcp/gcp-kibana-dns-overview.png
  source/images/gcp/gcp-kibana-filtered-logs.png
  source/images/gcp/gcp-kibana-log-filter.png
  source/images/gcp/gcp-overview.png
  source/images/gcp/gcp-sink-destination.png
  source/images/gcp/gcp-sink-dns-destination.png
  source/images/gcp/gcp-sink-dns-name.png
  source/images/gcp/gcp-sink-name.png
  source/images/gcp/gcp-system-event.png
  source/images/gcp/kibana-gcp-log-filter.png
Labels: gcp

#5238 Add note to HPUX upgrade process related to the user and group
  source/upgrade-guide/upgrading-agent.rst
Labels: upgrade guide

#5231 Warn about ignored tags in the overwrite rules
  source/learning-wazuh/replace-stock-rule.rst
  source/user-manual/ruleset/custom.rst
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: user manual, ruleset, Pending relase 4.3.1

#4724 Migrate agent-group files to Wazuh-DB - Documentation changes implementation
  source/_static/js/redirects.js
  source/development/wazuh-cluster.rst
  source/images/manual/cluster/cluster-flow.png
  source/user-manual/agents/grouping-agents.rst
  source/user-manual/configuring-cluster/basics.rst
  source/user-manual/manager/index.rst
  source/user-manual/manager/manual-backup-restore.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/ossec-conf/index.rst
  source/user-manual/reference/ossec-conf/wazuh-db-config.rst
Labels: type: refactor

#5284 Wazuh 4.2.7 release notes and version update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/deb/deploy_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/deb/install_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/deb/install_wazuh_manager.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/_templates/installations/basic/wazuh/yum/deploy_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/yum/install_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/yum/install_wazuh_manager.rst
  source/_templates/installations/basic/wazuh/zypp/deploy_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/zypp/install_wazuh_agent.rst
  source/_templates/installations/basic/wazuh/zypp/install_wazuh_manager.rst
  source/_templates/installations/wazuh/deb/deploy_wazuh_agent.rst
  source/_templates/installations/wazuh/deb/install_wazuh_agent.rst
  source/_templates/installations/wazuh/deb/install_wazuh_manager.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/_templates/installations/wazuh/yum/deploy_wazuh_agent.rst
  source/_templates/installations/wazuh/yum/install_wazuh_agent.rst
  source/_templates/installations/wazuh/yum/install_wazuh_manager.rst
  source/_templates/installations/wazuh/zypp/deploy_wazuh_agent.rst
  source/_templates/installations/wazuh/zypp/install_wazuh_agent.rst
  source/_templates/installations/wazuh/zypp/install_wazuh_manager.rst
  source/_themes/wazuh_doc_theme_v3/static/js/min/redirects.min.js
  source/conf.py
  source/installation-guide/packages-list.rst
  source/release-notes/index.rst
  source/release-notes/release-3-13-4.rst
  source/release-notes/release-4-2-7.rst
  source/upgrade-guide/compatibility-matrix/index.rst
  source/user-manual/agents/remote-upgrading/upgrading-agent.rst
  source/user-manual/registering/agent-enrollment.rst
Labels: priority: high, type: infrastructure

#5285 Wazuh 4.3.2 release notes and version update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/_templates/installations/basic/wazuh/solaris/uninstall_wazuh_agent_s10.rst
  source/_templates/installations/basic/wazuh/solaris/uninstall_wazuh_agent_s11.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/deployment-options/virtual-machine/virtual-machine.rst
  source/release-notes/index-3x.rst
  source/release-notes/index-4x.rst
  source/release-notes/release-3-13-4.rst
  source/release-notes/release-4-2-7.rst
  source/release-notes/release-4-3-2.rst
  source/upgrade-guide/compatibility-matrix/index.rst
  source/upgrade-guide/upgrading-agent.rst
  source/user-manual/agents/remote-upgrading/install-custom-wpk.rst
Labels: priority: high, type: infrastructure

#5286 Wazuh 3.13.4 release notes and version update
  source/_static/js/redirects.js
  source/conf.py
  source/installation-guide/compatibility_matrix/index.rst
  source/installation-guide/packages-list/index.rst
  source/release-notes/index.rst
  source/release-notes/release-3-13-4.rst
Labels: priority: high, type: infrastructure

#5292 Add release note 3.13.4 to 4.0
  source/release-notes/index.rst
  source/release-notes/release-3-13-4.rst
Labels: priority: high, type: infrastructure

#5287 Add Release note 3.13.4 to 4.1
  source/_static/js/redirects.js
  source/release-notes/index.rst
  source/release-notes/release_3_13_4.rst
Labels: priority: high, type: infrastructure

#5293 Add release note 3.13.4 to 4.2
  source/release-notes/index.rst
  source/release-notes/release-3-13-4.rst
Labels: priority: high, type: infrastructure

#5294 Add release note 3.13.4 to 4.3
  source/_static/js/redirects.js
  source/release-notes/index-3x.rst
  source/release-notes/release-3-13-4.rst
Labels: priority: high, type: infrastructure
