Repository wazuh/wazuh-documentation, pull requests merged in 2022-03, with the labels that each got.

#4892 Change the Canonical OVAL link in Vulnerability Detector
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: pending-core, core/vuln detector

#4896 Remote enrollment typo
  source/user-manual/reference/ossec-conf/auth.rst
Labels: typo

#4667 Add ipv6 support
  source/user-manual/reference/ossec-conf/auth.rst
  source/user-manual/reference/ossec-conf/global.rst
  source/user-manual/reference/ossec-conf/remote.rst
Labels: core/remoted, core/authd

#4899 Correct AIX and Solaris installation instructions
  source/_templates/installations/wazuh/solaris/uninstall_wazuh_agent_s11.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-aix.rst
Labels: cicd

#4901 Correcting the path for the Kibana reports
  source/user-manual/kibana-app/features/reporting.rst
Labels: operations

#4885 Improve AWS integration's ossec.conf reference
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: ossec.conf, aws, external_integrations

#4905 Removed outdated ossec-reportd testing instructions
  source/user-manual/manager/automatic-reports.rst
Labels: operations

#4886 Add sample IAM policies to every AWS supported service
  source/_templates/cloud/amazon/attach_policy.rst
  source/_templates/cloud/amazon/bucket_policies.rst
  source/_templates/cloud/amazon/create_policy.rst
  source/_templates/cloud/amazon/delete_policy_description.rst
  source/_templates/cloud/amazon/read_only_policy_description.rst
  source/amazon/services/prerequisites/credentials.rst
  source/amazon/services/supported-services/cisco-umbrella.rst
  source/amazon/services/supported-services/cloudtrail.rst
  source/amazon/services/supported-services/cloudwatchlogs.rst
  source/amazon/services/supported-services/config.rst
  source/amazon/services/supported-services/elastic-load-balancing/alb.rst
  source/amazon/services/supported-services/elastic-load-balancing/clb.rst
  source/amazon/services/supported-services/elastic-load-balancing/nlb.rst
  source/amazon/services/supported-services/guardduty.rst
  source/amazon/services/supported-services/inspector.rst
  source/amazon/services/supported-services/kms.rst
  source/amazon/services/supported-services/macie.rst
  source/amazon/services/supported-services/server-access.rst
  source/amazon/services/supported-services/trusted-advisor.rst
  source/amazon/services/supported-services/vpc.rst
  source/amazon/services/supported-services/waf.rst
  source/images/aws/aws-attach-policy.png
  source/images/aws/aws-create-policy.png
  source/images/aws/aws-summary-policy.png
Labels: aws, external_integrations

#4801 Documentation enhancement works v1.1
  source/upgrade-guide/compatibility-matrix/index.rst
Labels: priority: high, type: infrastructure, type: refactor

#4919 Modify the description of the baseline scan type for Vulnerability Detector
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
Labels: core/vuln detector

#4924 Add missing redirections
  source/_static/js/redirects.js
  source/deployment-options/elastic-stack/all-in-one-deployment/all-in-one.rst
  source/deployment-options/elastic-stack/all-in-one-deployment/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/step-by-step-installation/wazuh-cluster/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh-multi-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh-single-node-cluster.rst
  source/getting-started/use-cases/incident-response.rst
  source/getting-started/use-cases/index.rst
  source/getting-started/use-cases/intrusion-detection.rst
  source/getting-started/use-cases/security-analytics.rst
Labels: installation guide, priority: high

#4968 Replace 4.2.5 with 4.2.6 version references
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/basic/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/development/packaging/generate-aix-package.rst
  source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
  source/installation-guide/packages-list.rst
  source/installation-guide/wazuh-agent/deployment-variables/deployment-variables-aix.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-aix.rst
  source/upgrade-guide/compatibility-matrix/index.rst
  source/upgrade-guide/upgrading-agent.rst
  source/user-manual/agents/remote-upgrading/upgrading-agent.rst
  source/user-manual/registering/agent-enrollment.rst
Labels: Pending release

#5003 Changes to installation guide
  source/_templates/installations/common/deb/add-repository.rst
  source/_templates/installations/dashboard/deploy_certificates.rst
  source/_templates/installations/filebeat/opensearch/copy_certificates_filebeat_wazuh_cluster.rst
  source/_templates/installations/indexer/common/deploy_certificates.rst
  source/installation-guide/wazuh-dashboard/step-by-step.rst
  source/installation-guide/wazuh-server/step-by-step.rst
Labels: installation guide
