Repository wazuh/wazuh-documentation, pull requests merged in 2022-10, with the labels that each got.

#5642 Add "Securing your Wazuh installation" instructions - Offline installation guide
  source/_templates/installations/filebeat/opensearch/configure_filebeat.rst
  source/deployment-options/offline-installation.rst
Labels: hacktoberfest-accepted

#5644 Include dependencies for monitoring Azure in an agent
  source/_static/js/redirects.js
  source/azure/activity-services/prerequisites/dependencies.rst
  source/azure/activity-services/prerequisites/index.rst
Labels: azure

#5658 Wazuh 4.3.9 release notes and version update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/elastic/deb/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/deb/install_filebeat.rst
  source/_templates/installations/basic/elastic/deb/install_kibana.rst
  source/_templates/installations/basic/elastic/yum/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/yum/install_filebeat.rst
  source/_templates/installations/basic/elastic/yum/install_kibana.rst
  source/_templates/installations/basic/elastic/zypp/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/zypp/install_filebeat.rst
  source/_templates/installations/basic/elastic/zypp/install_kibana.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/deployment-options/elastic-stack/all-in-one-deployment/index.rst
  source/deployment-options/splunk/splunk-app.rst
  source/installation-guide/packages-list.rst
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-3-9.rst
  source/upgrade-guide/compatibility-matrix/index.rst
Labels: hacktoberfest-accepted

#5673 Fix SCA configuration typo
  source/user-manual/reference/ossec-conf/sca.rst
Labels: hacktoberfest-accepted

#5346 Events per second limits added to ossec.conf global section
  source/user-manual/api/configuration.rst
  source/user-manual/reference/ossec-conf/global.rst
Labels: ossec.conf, core/analysisd

#5679 Add the Wazuh dashboard browser requirements
  source/installation-guide/wazuh-dashboard/index.rst
  source/quickstart.rst
Labels: hacktoberfest-accepted

#5704 Update URL for Arch Linux feed
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: core/vuln detector
