Repository wazuh/wazuh-documentation, pull requests merged in 2022-04, with the labels that each got.

#5018 Remove ossec ownership from Wazuh documentation
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
  source/deployment-options/wazuh-from-sources/wazuh-server/index.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-hpux.rst
  source/proof-of-concept-guide/block-malicious-actor-ip-reputation.rst
  source/proof-of-concept-guide/detect-malware-yara-integration.rst
  source/proof-of-concept-guide/detect-remove-malware-virustotal.rst
  source/user-manual/capabilities/active-response/ar-use-cases/removing-malware.rst
  source/user-manual/capabilities/active-response/ar-use-cases/wazuh-with-yara.rst
  source/user-manual/capabilities/agentless-monitoring/how-it-works.rst
Labels: release

#5029 Changes warning message in macOS localfile
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: core/logcollector, documentation

#5032 Github and Office365 configuration improvements
  source/github/monitoring-github-activity.rst
  source/office365/monitoring-office365-activity.rst
  source/user-manual/reference/ossec-conf/github-module.rst
  source/user-manual/reference/ossec-conf/office365-module.rst
Labels: ossec.conf

#5053 4.3.0 Getting started enhancement Stage 2
  source/getting-started/index.rst
  source/images/getting-started/screenshot-01-Wazuh-Security-Analytics.png
  source/images/getting-started/screenshot-02-Wazuh-Intrusion-Detection.png
  source/images/getting-started/screenshot-03-Wazuh-Log-Data-Analysis.png
  source/images/getting-started/screenshot-04-Wazuh-File-Integrity-Monitoring.png
  source/images/getting-started/screenshot-05-Wazuh-Vulnerability-Detection.png
  source/images/getting-started/screenshot-06-Wazuh-Configuration-Assessment.png
  source/images/getting-started/screenshot-07-Wazuh-Incident-Response.png
  source/images/getting-started/screenshot-08-Wazuh-Regulatory-Compliance.png
  source/images/getting-started/screenshot-09-Wazuh-Cloud-Security.png
  source/images/getting-started/screenshot-10-Wazuh-Containers-Security.png
Labels: priority: high, type: refactor

#5002 4.3.0 Getting started enhancement Stage 1
  source/_static/js/redirects.js
  source/getting-started/architecture.rst
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh-agent.rst
  source/getting-started/components/wazuh-dashboard.rst
  source/getting-started/components/wazuh-indexer.rst
  source/getting-started/components/wazuh-server.rst
  source/getting-started/use-cases/cloud-security.rst
  source/getting-started/use-cases/configuration-assessment.rst
  source/getting-started/use-cases/container-security.rst
  source/getting-started/use-cases/file-integrity.rst
  source/getting-started/use-cases/incident-response.rst
  source/getting-started/use-cases/index.rst
  source/getting-started/use-cases/log-analysis.rst
  source/getting-started/use-cases/regulatory-compliance.rst
  source/getting-started/use-cases/rootkits-detection.rst
  source/getting-started/use-cases/security-analytics.rst
  source/getting-started/use-cases/system-inventory.rst
  source/getting-started/use-cases/vulnerability-detection.rst
  source/installation-guide/wazuh-agent/index.rst
Labels: priority: high, type: refactor

#5061 Office 365 documentation improvement
  source/images/office365/0-azure-app-new-registration.png
  source/images/office365/1-azure-wazuh-app-register-application.png
  source/images/office365/2-azure-wazuh-app-overview.png
  source/images/office365/3-azure-wazuh-app-create-password-copy-value.png
  source/images/office365/3-azure-wazuh-app-create-password.png
  source/images/office365/4-azure-wazuh-app-configure-permissions-admin-consent.png
  source/images/office365/4-azure-wazuh-app-configure-permissions.png
  source/images/office365/azure-app-new-registration.png
  source/office365/monitoring-office365-activity.rst
  source/user-manual/reference/ossec-conf/office365-module.rst
Labels: documentation

#5084 4.3.0 images update stage 2
  source/deployment-options/deploying-with-ansible/guide/install-opendistro-server.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-agent.rst
  source/images/ansible/ansible-agent.png
  source/images/ansible/ansible-agent2.png
  source/images/ansible/wazuh-dashboard-main.png
  source/images/installation/windows.png
  source/images/manual/automatic-remediation/561-host-blocked-by-firewall-drop.png
  source/images/manual/automatic-remediation/5712-sshd-brute-force.png
  source/images/manual/automatic-remediation/YARA-Wazuh-ui-dashboard.png
  source/images/manual/devtools-syscollector.png
  source/images/manual/fim/fim-kibana-overview-1.png
  source/images/manual/inventory.png
  source/images/manual/mitre/mitre-1.png
  source/images/wodles-oscap/oscap-dashboard.png
  source/images/wodles-oscap/oscap-example.png
  source/images/wodles-oscap/oscap-overview.png
  source/images/wodles-oscap/pci-dashboard.png
  source/images/wodles-oscap/pci-oscap.png
  source/upgrade-guide/legacy/upgrading-agent/from-2.x-to-3.x.rst
  source/upgrade-guide/upgrading-agent.rst
  source/user-manual/capabilities/file-integrity/how-it-works.rst
  source/user-manual/capabilities/policy-monitoring/openscap/oscap-configuration.rst
Labels: priority: high, type: refactor

#5095 Rework of the section: Installation alternatives - Virtual Machine (OVA)
  source/deployment-options/virtual-machine/virtual-machine.rst
Labels: priority: high, type: infrastructure, type: refactor

#5089 Rework of the section: Installation alternatives - Deployment on Docker
  source/_static/js/redirects.js
  source/deployment-options/docker/container-usage.rst
  source/deployment-options/docker/docker-installation.rst
  source/deployment-options/docker/faq-wazuh-container.rst
  source/deployment-options/docker/index.rst
  source/deployment-options/docker/upgrade-guide.rst
  source/deployment-options/docker/wazuh-container.rst
Labels: priority: high, type: infrastructure, type: refactor

#5105 4.3.0 images update stage 3
  source/images/installation/Wazuh-Dashboard-Installation-3.png
  source/images/installation/Wazuh-Indexer-Installation-1.png
  source/images/installation/Wazuh-Installation-workflow-complete.png
  source/images/installation/Wazuh-Installation-workflow.png
  source/images/installation/Wazuh-Server-Installation-2.png
  source/images/installation/all-in-one-deployment.png
  source/images/installation/distributed-no-title.png
Labels: priority: high, type: refactor

#5096 Rework of Installing Wazuh with Elastic Stack basic license
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/elastic/deb/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/deb/install_filebeat.rst
  source/_templates/installations/basic/elastic/deb/install_kibana.rst
  source/_templates/installations/basic/elastic/yum/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/yum/install_filebeat.rst
  source/_templates/installations/basic/elastic/yum/install_kibana.rst
  source/_templates/installations/basic/elastic/zypp/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/zypp/install_filebeat.rst
  source/_templates/installations/basic/elastic/zypp/install_kibana.rst
  source/conf.py
  source/deployment-options/elastic-stack/all-in-one-deployment/all-in-one.rst
  source/deployment-options/elastic-stack/all-in-one-deployment/index.rst
  source/deployment-options/elastic-stack/all-in-one-deployment/unattended-installation.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/elasticsearch-single-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/kibana/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/step-by-step-installation/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/unattended/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.rst
  source/deployment-options/elastic-stack/distributed-deployment/unattended/unattended-wazuh-cluster-installation.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/wazuh-multi-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/wazuh-single-node-cluster.rst
  source/deployment-options/elastic-stack/index.rst
  source/deployment-options/index.rst
  source/images/installation/all-in-one-deployment.png
  source/images/installation/distributed-no-title.png
  source/upgrade-guide/compatibility-matrix/index.rst
Labels: priority: high, type: infrastructure, type: refactor

#5124 Rework the Getting started section
  source/getting-started/components/index.rst
  source/getting-started/components/wazuh-dashboard.rst
  source/getting-started/components/wazuh-indexer.rst
  source/getting-started/components/wazuh-server.rst
  source/getting-started/index.rst
  source/images/getting-started/data-flow.png
Labels: priority: high, type: infrastructure, type: refactor

#4945 Update Installing Wazuh from AMI document
  source/conf.py
  source/deployment-options/amazon-machine-images/amazon-machine-images.rst
  source/getting-started/architecture.rst
  source/proof-of-concept-guide/index.rst
Labels: installation guide, Pending release
