Repository wazuh/wazuh-documentation, pull requests merged in 2023-06, with the labels that each got.

#5960 4.4.0 images update - Adjust SEO - Part 2
  source/deployment-options/elastic-stack/index.rst
  source/deployment-options/splunk/splunk-app.rst
  source/deployment-options/splunk/splunk-distributed.rst
  source/deployment-options/splunk/splunk-minimal-distributed.rst
  source/getting-started/use-cases/cloud-security.rst
  source/getting-started/use-cases/configuration-assessment.rst
  source/getting-started/use-cases/container-security.rst
  source/getting-started/use-cases/file-integrity.rst
  source/getting-started/use-cases/regulatory-compliance.rst
  source/getting-started/use-cases/system-inventory.rst
  source/getting-started/use-cases/vulnerability-detection.rst
  source/images/getting-started/running-processes.png
  source/images/getting-started/software-inventory.png
  source/images/getting-started/system-inventory.png
  source/images/getting-started/use-cases/aws-security-dashboard.png
  source/images/getting-started/use-cases/compliance-requirements.png
  source/images/getting-started/use-cases/docker-alerts.png
  source/images/getting-started/use-cases/integrity-monitoring-events.png
  source/images/getting-started/use-cases/integrity-monitoring-inventory.png
  source/images/getting-started/use-cases/regulatory-compliance-dashboard.png
  source/images/getting-started/use-cases/regulatory-compliance.png
  source/images/getting-started/use-cases/sca-evaluation.png
  source/images/getting-started/use-cases/sca-events-tab.png
  source/images/getting-started/use-cases/sca-inventory-tab.png
  source/images/installation/distributed-deployment.png
  source/images/installation/macos-agent.png
  source/images/release-notes/4.3.0/vulnerability-detection.png
  source/images/splunk-app/alerts-and-events-tab.png
  source/images/splunk-app/alerts-and-events.png
  source/images/splunk-app/alerts-dashboard.png
  source/images/splunk-app/configure-index-and-source-type.png
  source/images/splunk-app/index-tab.png
  source/images/splunk-app/settings-icon.png
  source/images/splunk-app/settings-index.png
  source/images/splunk-app/settings-page.png
  source/images/splunk-app/wazuh-api-configuration.png
  source/images/splunk-app/wazuh-api-credentials.png
  source/images/splunk-app/wazuh-api-setting.png
  source/images/splunk-app/wazuh-app-for-splunk.png
  source/images/splunk-cluster/configure-receiving.png
  source/images/splunk-cluster/forwarding-and-receiving.png
  source/images/splunk-cluster/new-receiving-port.png
  source/images/splunk-cluster/splunk-distributed-architecture.png
  source/images/splunk-cluster/splunk-multi-instance-cluster.png
  source/installation-guide/wazuh-agent/wazuh-agent-package-macos.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-windows.rst
  source/release-notes/release-4-3-0.rst
  source/upgrade-guide/wazuh-agent/macos.rst
Labels: priority: high, images

#6140 Section update: Vulnerability detection guide
  source/_static/js/redirects.js
  source/user-manual/capabilities/vulnerability-detection/cpe-helper.rst
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
  source/user-manual/capabilities/vulnerability-detection/index.rst
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
  source/user-manual/capabilities/vulnerability-detection/querying-the-vulnerability-database.rst
Labels: priority: high, type: refactor

#6144 Wazuh 4.4.4 release notes
  source/_static/js/redirects.js
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-4.rst
  source/user-manual/ruleset/testing.rst
Labels: release notes, priority: high

#6142 Section update: Agentless monitoring
  source/_static/js/redirects.js
  source/images/manual/agentless-monitoring/add-the-rule-description-field.png
  source/images/manual/agentless-monitoring/after-adding-all-the-fields.png
  source/images/manual/agentless-monitoring/click-on-open.png
  source/images/manual/agentless-monitoring/click-on-save.png
  source/images/manual/agentless-monitoring/click-the-save-button.png
  source/images/manual/agentless-monitoring/discover-section.png
  source/images/manual/agentless-monitoring/expand-one-of-the-alerts-with-rule-id-550.png
  source/images/manual/agentless-monitoring/expand-one-of-the-alerts.png
  source/images/manual/agentless-monitoring/expand-the-alert-with-rule-id-555.png
  source/images/manual/agentless-monitoring/filter-agentless-logs.png
  source/images/manual/agentless-monitoring/navigate-to-modules-security-events.png
  source/images/manual/agentless-monitoring/search-for-agentless-host.png
  source/images/manual/agentless-monitoring/select-the-syscheck-path.png
  source/user-manual/capabilities/agentless-monitoring/agentless-configuration.rst
  source/user-manual/capabilities/agentless-monitoring/agentless-faq.rst
  source/user-manual/capabilities/agentless-monitoring/connection.rst
  source/user-manual/capabilities/agentless-monitoring/how-it-works.rst
  source/user-manual/capabilities/agentless-monitoring/index.rst
  source/user-manual/capabilities/agentless-monitoring/use-cases.rst
  source/user-manual/capabilities/agentless-monitoring/visualization.rst
Labels: priority: high, type: refactor

#6198 Add Solaris to syscollector´s compatibility matrix - Implementation
  source/user-manual/capabilities/system-inventory/compatibility-matrix.rst
Labels: core/syscollector
