Repository wazuh/wazuh-documentation, pull requests merged in 2023-09, with the labels that each got.

#6401 [4.6.0] Remove Kibana and Splunk from documentation
  source/_static/js/redirects.js
  source/deployment-options/elastic-stack/all-in-one-deployment/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/elasticsearch-multi-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/elasticsearch-single-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/kibana/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/index.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/wazuh-multi-node-cluster.rst
  source/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/wazuh-single-node-cluster.rst
  source/deployment-options/elastic-stack/index.rst
  source/deployment-options/index.rst
  source/deployment-options/offline-installation.rst
  source/deployment-options/splunk/index.rst
  source/deployment-options/splunk/splunk-app.rst
  source/deployment-options/splunk/splunk-basic.rst
  source/deployment-options/splunk/splunk-distributed.rst
  source/deployment-options/splunk/splunk-install.rst
  source/deployment-options/splunk/splunk-minimal-distributed.rst
  source/deployment-options/splunk/splunk-polling.rst
  source/deployment-options/splunk/splunk-rbac.rst
  source/deployment-options/splunk/splunk-reverse-proxy.rst
  source/deployment-options/splunk/splunk-wazuh.rst
  source/development/packaging/generate-wazuh-kibana-app.rst
  source/development/packaging/generate-wazuh-splunk-app.rst
  source/development/packaging/index.rst
  source/release-notes/release-3-9-1.rst
  source/upgrade-guide/compatibility-matrix/index.rst
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.rst
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.rst
  source/upgrade-guide/index.rst
  source/upgrade-guide/legacy/index.rst
  source/upgrade-guide/legacy/upgrading-agent/from-1.x-to-2.x.rst
  source/upgrade-guide/legacy/upgrading-agent/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-agent/index.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-2.x-to-5.x.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.8-to-7.x.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.x-to-6.8.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/from-1.x-to-2.x.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.rst
  source/user-manual/elasticsearch/configure-indices.rst
  source/user-manual/elasticsearch/elastic-tuning.rst
  source/user-manual/elasticsearch/elasticsearch.rst
  source/user-manual/elasticsearch/index.rst
  source/user-manual/elasticsearch/troubleshooting.rst
  source/user-manual/index.rst
  source/user-manual/uninstall/central-components.rst
  source/user-manual/uninstall/elastic-stack.rst
  source/user-manual/uninstall/index.rst
  source/user-manual/uninstall/open-distro.rst
  source/user-manual/wazuh-dashboard/config-file.rst
Labels: level/task, type/change

#6420 Update maltiverse rule id
  source/images/manual/integration/maltiverse.png
  source/user-manual/manager/manual-integration.rst
Labels: integrator, level/task, type/bug

#6232 Refactored and standarized the Python dependencies section for cloud and docker modules
  source/cloud-security/amazon/services/prerequisites/considerations.rst
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
  source/cloud-security/amazon/services/troubleshooting.rst
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
  source/cloud-security/gcp/prerequisites/dependencies.rst
  source/conf.py
  source/user-manual/capabilities/container-security/monitoring-docker.rst
Labels: level/task, type/bug

#5962 Options section for integrations.
  source/user-manual/manager/manual-integration.rst
  source/user-manual/reference/ossec-conf/integration.rst
Labels: integrator, level/task, type/enhancement, team/core/security warriors

#6428 Added code for missing icons on index
  source/_themes/wazuh_doc_theme_v3/src/scss/pages/index.scss
  source/_themes/wazuh_doc_theme_v3/static/css/min/index.min.css
  source/_themes/wazuh_doc_theme_v3/static/images/icons/index-icons.svg
Labels: level/task, type/bug

#6430 Update Debian OVAL URL for offline update
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: core/vuln detector, level/task, type/change

#6442 Add timeout and retries settings to integratord configuration
  source/user-manual/manager/manual-integration.rst
  source/user-manual/reference/ossec-conf/integration.rst
Labels: level/task, type/enhancement

#6481 Update deploy new agent from UI screenshots
  source/images/installation/deploy-new-agent-from-ui-options.png
  source/images/installation/deploy-new-agent-from-ui.png
Labels: level/task, request/operational, type/maintenance

#6506 Inconsistent configurations in Wazuh Puppet agent installation
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
Labels: level/task, type/bug

#6505 Add note for Microsoft Graph multi-tenant not supported
  source/cloud-security/ms-graph/monitoring-ms-graph-activity.rst
  source/user-manual/reference/ossec-conf/ms-graph-module.rst
Labels: level/task, type/enhancement

#6435 Update SUSE OVAL URL for offline update
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: core/vuln detector, level/task, type/change

#6495 [4.5] Fixed an error on the API reference pages
  source/_themes/wazuh_doc_theme_v3/config/uglifyjs-group.js
  source/_themes/wazuh_doc_theme_v3/src/scss/pages/index.scss
  source/_themes/wazuh_doc_theme_v3/static/js/min/api-reference.min.js
  source/conf.py
Labels: level/task, type/bug

#6500 Add Wazuh dashboard queries documentation
  source/_static/js/redirects.js
  source/images/wazuh-dashboard/queries/search-bar-wql-with-implicit-filter.png
  source/images/wazuh-dashboard/queries/search-bar-wql.png
  source/user-manual/wazuh-dashboard/index.rst
  source/user-manual/wazuh-dashboard/queries.rst
Labels: level/task, type/change

#6509 Fix in GCP configuration examples
  source/cloud-security/gcp/prerequisites/credentials.rst
  source/user-manual/reference/ossec-conf/gcp-bucket.rst
Labels: level/task, type/bug

#6502 Email App version for Shuffle
  source/user-manual/manager/manual-integration.rst
Labels: level/task, type/bug

#6514 Add differentiation between commands from different Python versions
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
  source/cloud-security/gcp/prerequisites/dependencies.rst
Labels: level/task, type/bug

#6513 Change python 3.11 pyarrow dependency version
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
Labels: level/task, type/bug

#6524 Add path parameter usage example to Azure Storage
  source/cloud-security/azure/activity-services/prerequisites/considerations.rst
  source/cloud-security/azure/activity-services/services/storage.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
Labels: level/task, type/enhancement

#6531 Add support for Kibana 7.17.13
  source/_templates/installations/basic/elastic/deb/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/deb/install_filebeat.rst
  source/_templates/installations/basic/elastic/deb/install_kibana.rst
  source/_templates/installations/basic/elastic/yum/install_elasticsearch.rst
  source/_templates/installations/basic/elastic/yum/install_filebeat.rst
  source/_templates/installations/basic/elastic/yum/install_kibana.rst
  source/_variables/replacements.py
  source/deployment-options/elastic-stack/all-in-one-deployment/index.rst
  source/deployment-options/elastic-stack/index.rst
  source/upgrade-guide/compatibility-matrix/index.rst
Labels: level/task, request/operational, type/enhancement

#6362 Add a nested query example
  source/user-manual/api/queries.rst
Labels: API, level/subtask, type/enhancement

#6034 Wazuh 4.6.0 release notes
  source/_static/js/redirects.js
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-6-0.rst
Labels: release notes, priority: high

#6446 Add support for Amazon Linux 2023 in Vulnerability Detector
  source/deployment-options/deploying-with-ansible/reference.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: core/vuln detector, level/task, type/enhancement

#6555 Added clarifications in the Docker multi-node deployment
  source/deployment-options/docker/wazuh-container.rst
Labels: level/task, type/enhancement

#6554 Added note on Docker passwords change
  source/deployment-options/docker/wazuh-container.rst
Labels: level/task, type/enhancement
