Repository wazuh/wazuh-documentation, pull requests merged in 2023-11, with the labels that each got.

#6711 Update dashboard settings screenshots
  source/images/kibana-app/features/settings/about.png
  source/images/kibana-app/features/settings/api.png
  source/images/kibana-app/features/settings/configuration.png
  source/images/kibana-app/features/settings/extensions.png
  source/images/kibana-app/features/settings/logs.png
Labels: level/task, type/enhancement

#6674 Add Alpine Linux installation procedure
  source/upgrade-guide/wazuh-agent/linux.rst
Labels: level/task, type/enhancement

#6735 remove cache deletion from upgrade guide
  source/upgrade-guide/upgrading-central-components.rst
Labels: level/task, type/enhancement

#6592 Rename Azure Active Directory to Microsoft Entra ID
  source/_static/js/redirects.js
  source/_variables/redirect_same_release.py
  source/cloud-security/azure/activity-services/active-directory/index.rst
  source/cloud-security/azure/activity-services/entra/graph.rst
  source/cloud-security/azure/activity-services/entra/index.rst
  source/cloud-security/azure/activity-services/index.rst
  source/cloud-security/azure/activity-services/prerequisites/considerations.rst
  source/cloud-security/azure/activity-services/prerequisites/credentials.rst
  source/cloud-security/azure/activity-services/services/log-analytics.rst
  source/cloud-security/azure/activity-services/services/storage.rst
  source/cloud-security/azure/index.rst
  source/cloud-security/ms-graph/index.rst
  source/cloud-security/office365/index.rst
  source/getting-started/components/wazuh-agent.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
  source/user-manual/user-administration/index.rst
  source/user-manual/user-administration/single-sign-on/administrator/index.rst
  source/user-manual/user-administration/single-sign-on/administrator/microsoft-entra-id.rst
  source/user-manual/user-administration/single-sign-on/read-only/index.rst
  source/user-manual/user-administration/single-sign-on/read-only/microsoft-entra-id.rst
Labels: level/task, type/bug

#6738 Deprecate vulnerability endpoints
  source/user-manual/api/rbac/reference.rst
Labels: level/task, type/enhancement

#6693 Adds missing RBAC References.
  source/user-manual/api/rbac/reference.rst
Labels: level/task, type/bug

#6760 Update Filebeat module revision to 0.3
  source/deployment-options/offline-installation.rst
  source/installation-guide/wazuh-server/step-by-step.rst
  source/upgrade-guide/upgrading-central-components.rst
Labels: level/task, type/enhancement

#6750 Add INDEXER_PASSWORD for wazuh-indexer
  source/deployment-options/docker/wazuh-container.rst
Labels: level/task, type/change

#6687 Add documentation for the ISM rollover policy
  .gitignore
  source/deployment-options/offline-installation.rst
  source/installation-guide/wazuh-indexer/step-by-step.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/user-manual/wazuh-dashboard/config-file.rst
  source/user-manual/wazuh-indexer/index-life-management.rst
Labels: level/task, type/enhancement

#6766 Add pyarrow_hotfix dependency to AWS Prerequisites section
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
Labels: level/task, type/enhancement

#6761 Improved Ansible Wazuh agent documentation
  source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-agent.rst
  source/deployment-options/deploying-with-ansible/reference.rst
Labels: level/task, type/enhancement

#6776 Set the default value of allow_higher_versions to no
  source/user-manual/reference/ossec-conf/auth.rst
  source/user-manual/reference/ossec-conf/remote.rst
Labels: type/change

#6769 Modify bucket popfsenselicies template
  source/_templates/cloud/amazon/bucket_policies.rst
Labels: level/task, type/bug

#6775 Change home URL to just the base path
  CHANGELOG.md
  source/images/single-sign-on/azure-active-directory/read-only/11-click-edit-and-set-wazuh-saml-RO.png
  source/images/single-sign-on/keycloak/08-fine-grain-saml-endpoint-configuration.png
  source/images/single-sign-on/onelogin/05-search-for-saml-custom-connector.png
  source/user-manual/user-administration/single-sign-on/administrator/keycloak.rst
  source/user-manual/user-administration/single-sign-on/administrator/onelogin.rst
  source/user-manual/user-administration/single-sign-on/read-only/keycloak.rst
  source/user-manual/user-administration/single-sign-on/read-only/microsoft-entra-id.rst
  source/user-manual/user-administration/single-sign-on/read-only/onelogin.rst
Labels: level/task, type/change

#6779 Change custom branding top logo configuration
  source/images/kibana-app/features/white-labeling/custom-branding-settings-header.png
  source/images/kibana-app/features/white-labeling/custom-branding-settings-health-check.png
  source/images/kibana-app/features/white-labeling/custom-branding-settings-loading.png
  source/images/kibana-app/features/white-labeling/custom-branding-settings.jpg
  source/user-manual/wazuh-dashboard/custom-branding.rst
Labels: level/task, type/enhancement

#6791 Add fix to 4.7.0 release notes
  source/release-notes/release-4-7-0.rst
Labels: level/task, type/bug

#6770 Enhance the discard regex and field feature description and examples
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: level/task, type/enhancement
