Repository wazuh/wazuh-documentation, pull requests merged in 2023-02, with the labels that each got.

#5897 Moved remove_from_bucket from wodle to bucket
  source/proof-of-concept-guide/aws-infrastructure-monitoring.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: type: refactor

#5908 Update 4.4.0 release notes
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-0.rst
Labels: release notes, priority: high

#5912 Fix typo: Integration with external APIs section
  source/user-manual/manager/manual-integration.rst
Labels: typo

#5919 Update 4.4.0 release notes
  source/images/release-notes/4.4.0/alpine-linux.png
  source/release-notes/release-4-4-0.rst
Labels: release notes, priority: high

#5921 Update 4.4.0 release notes V2
  source/release-notes/release-4-4-0.rst
Labels: release notes, priority: high

#5909 4.4.0 images update - Part 1
  source/images/getting-started/dashboard_API_console1.png
  source/images/getting-started/dashboard_API_console2.png
  source/images/getting-started/dashboard_ruleset_test.png
  source/images/getting-started/dashboard_screenshot_agent.png
  source/images/getting-started/screenshot-01-Wazuh-Security-Analytics.png
  source/images/getting-started/screenshot-02-Wazuh-Intrusion-Detection.png
  source/images/getting-started/screenshot-03-Wazuh-Log-Data-Analysis.png
  source/images/getting-started/screenshot-04-Wazuh-File-Integrity-Monitoring.png
  source/images/getting-started/screenshot-05-Wazuh-Vulnerability-Detection.png
  source/images/getting-started/screenshot-06-Wazuh-Configuration-Assessment.png
  source/images/getting-started/screenshot-07-Wazuh-Incident-Response.png
  source/images/getting-started/screenshot-08-Wazuh-Regulatory-Compliance.png
  source/images/getting-started/screenshot-09-Wazuh-Cloud-Security.png
  source/images/getting-started/screenshot-10-Wazuh-Containers-Security.png
  source/images/getting-started/use-cases/wazuh-use-cases-cloud-geo.png
  source/images/getting-started/use-cases/wazuh-use-cases-docker.png
  source/images/getting-started/use-cases/wazuh-use-cases-fim1.png
  source/images/getting-started/use-cases/wazuh-use-cases-fim2.png
  source/images/getting-started/use-cases/wazuh-use-cases-fim3.png
  source/images/getting-started/use-cases/wazuh-use-cases-log-data-analysis1.png
  source/images/getting-started/use-cases/wazuh-use-cases-log-data-analysis2.png
  source/images/getting-started/use-cases/wazuh-use-cases-regulatory1.png
  source/images/getting-started/use-cases/wazuh-use-cases-regulatory2.png
  source/images/getting-started/use-cases/wazuh-use-cases-regulatory3.png
  source/images/getting-started/use-cases/wazuh-use-cases-sca01.png
  source/images/getting-started/use-cases/wazuh-use-cases-sca2.png
  source/images/getting-started/use-cases/wazuh-use-cases-sca3.png
  source/images/kibana-app/agent-management/agents-preview.png
  source/images/kibana-app/features/query-configuration/cluster.png
  source/images/kibana-app/features/query-configuration/configuration-section.png
  source/images/kibana-app/features/query-configuration/is-sync.png
  source/images/kibana-app/features/query-configuration/logcollector-json.png
  source/images/kibana-app/features/query-configuration/logcollector-query.png
  source/images/manual/automatic-remediation/561-host-blocked-by-firewall-drop.png
  source/images/manual/automatic-remediation/5712-sshd-brute-force.png
  source/images/manual/deploy-a-new-agent-from-ui.png
  source/images/manual/devtools-syscollector.png
  source/images/manual/fim/fim-kibana-overview-1.png
  source/images/manual/inventory.png
  source/images/manual/managing-agents/agents-dashboard.png
  source/images/manual/managing-agents/agents-menu.png
  source/images/release-notes/4.3.0/packages-inventory.png
  source/images/sca/sca-agent-check-result.png
  source/images/sca/sca-agent-overview.png
  source/images/sca/sca-alert-ssh-permit-root-login.png
  source/images/wodles-oscap/oscap-dashboard.png
  source/images/wodles-oscap/oscap-example.png
  source/images/wodles-oscap/oscap-overview.png
  source/images/wodles-oscap/pci-dashboard.png
  source/images/wodles-oscap/pci-oscap.png
Labels: priority: high, type: refactor

#5916 4.4.0 images update - Part 2
  source/amazon/services/supported-services/macie.rst
  source/azure/activity-services/active-directory/graph.rst
  source/images/aws/trusted-ui-1.png
  source/images/aws/trusted-ui-2.png
  source/images/azure/kibana-services-1.png
  source/images/azure/kibana-services-2.png
  source/images/azure/new-user-event.png
  source/images/azure/storage-kibana.png
  source/images/gcp/gcp-kibana-filtered-logs.png
  source/images/gcp/gcp-kibana-log-filter.png
  source/images/gcp/gcp-overview.png
  source/images/kibana-app/features/settings/about.png
  source/images/kibana-app/features/settings/api.png
  source/images/kibana-app/features/settings/configuration.png
  source/images/kibana-app/features/settings/extensions.png
  source/images/kibana-app/features/settings/logs.png
  source/images/manual/user-administration/rbac/create-new-role-mapping.png
  source/images/manual/user-administration/rbac/create-policy.png
  source/images/manual/user-administration/rbac/create-role.png
  source/images/manual/user-administration/rbac/environment.png
  source/images/manual/user-administration/rbac/team_A-agents.png
  source/images/manual/vuln-detector/vuln-inventory01.png
  source/images/manual/vuln-detector/vuln-inventory02.png
  source/images/pci/alert-generated-for-the-file-deleted.png
  source/images/pci/alert-generated-on-the-next- syscheck-scan-01.png
  source/images/pci/alert-generated-on-the-next- syscheck-scan-02.png
  source/images/pci/alert-generated-on-the-next-syscheck-scan-01.png
  source/images/pci/alert-generated-on-the-next-syscheck-scan-02.png
  source/images/pci/attempt-to-login-using-non-existent-user.png
  source/images/pci/configure-settings.png
  source/images/pci/define-an-index-pattern.png
  source/images/pci/ensure-ip-forwarding-is-disabled.png
  source/images/pci/ensure-password-reuse-is-limited.png
  source/images/pci/file-modified-in-the-monitored-directory-2.png
  source/images/pci/file-modified-in-the-monitored-directory.png
  source/images/pci/filter-for-vulnerabilities.png
  source/images/pci/host-based-anomaly-detection-event.png
  source/images/pci/overview-of-the-issue-detected.png
  source/images/pci/pci-dss-requirement-10.4.1-1.png
  source/images/pci/pci-dss-requirement-10.4.1-2.png
  source/images/pci/results-on-the-wazuh-dashboard.png
  source/images/pci/rule-5710 generates-an-alert-01.png
  source/images/pci/rule-5710 generates-an-alert-02.png
  source/images/pci/rule-5710 generates-an-alert-03.png
  source/images/pci/rule-5710 generates-an-alert-04.png
  source/images/pci/rule-5710-generates-an-alert-01.png
  source/images/pci/rule-5710-generates-an-alert-02.png
  source/images/pci/rule-5710-generates-an-alert-03.png
  source/images/pci/rule-5710-generates-an-alert-04.png
  source/images/pci/select-create-index-pattern.png
  source/images/pci/select-discover-1.png
  source/images/pci/select-discover-2.png
  source/images/pci/select-stack-management.png
  source/images/pci/user-successfully-logs-into-a-system-via-SSH.png
  source/pci-dss/active-response.rst
  source/pci-dss/file-integrity-monitoring.rst
Labels: priority: high, type: refactor

#5924 4.4.0 images update - Part 3
  source/images/gdpr/SCA-28690-no-alerts.png
  source/images/gdpr/fim-file-del.png
  source/images/gdpr/fim-file-mod-who1.png
  source/images/gdpr/fim-file-mod-who2.png
  source/images/gdpr/fim-file-mod.png
  source/images/gdpr/gdprii-tag.png
  source/images/gdpr/integrity-monitoring-level-15.png
  source/images/gdpr/integrity-monitoring-level-7.png
  source/images/gdpr/invalid-ssh-login-attempt1.png
  source/images/gdpr/invalid-ssh-login-attempt2.png
  source/images/gdpr/syscheck-no-alerts.png
  source/images/hipaa/01-log-data-analysis.png
  source/images/hipaa/02-configuration-assessment.png
  source/images/hipaa/03-configuration-assessment.png
  source/images/hipaa/04-file-integrity-monitoring.png
  source/images/hipaa/05-file-integrity-monitoring.png
  source/images/hipaa/06-vulnerability-detection.png
  source/images/hipaa/07-vulnerability-detection.png
  source/images/hipaa/08-active-response.png
  source/images/hipaa/09-active-response.png
  source/images/hipaa/visualization-and-dashboard/01-hipaa-related-events.png
  source/images/hipaa/visualization-and-dashboard/02-hipaa-module.png
  source/images/hipaa/visualization-and-dashboard/03-hipaa-standard-alerts.png
  source/images/hipaa/visualization-and-dashboard/04-hipaa-related-events.png
  source/images/hipaa/visualization-and-dashboard/05-hipaa-section.png
  source/images/pci/alerts-generated-by-suspicious activities-01.png
  source/images/pci/alerts-generated-by-suspicious-activities-01.png
  source/images/pci/processes-are-running-on-a-specific-endpoint-01.png
  source/images/pci/processes-are-running-on-a-specific-endpoint-02.png
  source/images/pci/processes-are-running-on-a-specific-endpoint-03.png
  source/images/pci/regulatory-compliance-module-01.png
  source/images/pci/regulatory-compliance-module-02.png
  source/images/pci/regulatory-compliance-module-03.png
  source/images/poc/AWS-alerts.png
  source/images/poc/NIDS-suricata-alerts.png
  source/images/poc/SQL-injection-rule-31103.png
  source/images/poc/SQL-injection-rule-31106.png
  source/images/poc/audit-commands-alerts.png
  source/images/poc/block-malicious-actor-ubuntu-alerts.png
  source/images/poc/block-malicious-actor-windows-alerts.png
  source/images/poc/brute-force-attack-alerts-ubuntu.png
  source/images/poc/brute-force-attack-alerts-windows.png
  source/images/poc/docker-actions-alerts.png
  source/images/poc/docker-group-alerts.png
  source/images/poc/fim-alerts-ubuntu.png
  source/images/poc/fim-alerts-windows.png
  source/images/poc/hidden-processes-alerts.png
  source/images/poc/malware-yara-linux-alerts.png
  source/images/poc/malware-yara-windows-alerts.png
  source/images/poc/shellshock-alerts.png
  source/images/poc/suspicious-binary-alerts.png
  source/images/poc/unauthorized-processes-alerts.png
  source/images/poc/virustotal-remove-malware-linux-alert.png
  source/images/poc/virustotal-remove-malware-windows-alert.png
  source/images/poc/vulnerabilities-ubuntu-alerts.png
  source/images/poc/vulnerabilities-windows-alerts.png
  source/pci-dss/dashboard.rst
Labels: priority: high, type: refactor

#5938 Add missing internal options to the reference documentation
  source/user-manual/reference/internal-options.rst
Labels: user manual, type: bug
