Repository wazuh/wazuh-documentation, pull requests merged in 2023-05, with the labels that each got.

#6032 Wazuh 4.4.2 release notes
  source/_static/js/redirects.js
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-2.rst
Labels: release notes, priority: high

#6069 Section update: File integrity monitoring
  source/_static/js/redirects.js
  source/images/manual/fim/advanced-audit-policy-configuration-section.png
  source/images/manual/fim/alert-for-the-private-file-conf.png
  source/images/manual/fim/alerts-related-monitored-directory.png
  source/images/manual/fim/audit-policy-section.png
  source/images/manual/fim/changed-fields-expanded-alert.png
  source/images/manual/fim/changed-windows-startup-registries.png
  source/images/manual/fim/changes-user-details-file.png
  source/images/manual/fim/changes-windows-authorized-keys-file.png
  source/images/manual/fim/changes-windows-startup-folder.png
  source/images/manual/fim/content-added-to-the-file.png
  source/images/manual/fim/dashboard.png
  source/images/manual/fim/deleted-file-alert.png
  source/images/manual/fim/entry-details.png
  source/images/manual/fim/events.png
  source/images/manual/fim/expand-the-alert-with-rule.id:550.png
  source/images/manual/fim/expand-the-alert.png
  source/images/manual/fim/expanded-alert-entry.png
  source/images/manual/fim/fim-alerts.png
  source/images/manual/fim/fim-detects-changes.png
  source/images/manual/fim/fim-flow.png
  source/images/manual/fim/fim-overview.png
  source/images/manual/fim/get-more-information-about-the-event.png
  source/images/manual/fim/inventory.png
  source/images/manual/fim/modification-of-the-configuration-file.png
  source/images/manual/fim/modification-of-the-monitored-registry-value.png
  source/images/manual/fim/severity-of-12-alert.png
  source/images/manual/fim/synchronization-diagram.png
  source/images/manual/fim/test-the-configuration.png
  source/images/manual/fim/visualize-the-alert.png
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
  source/user-manual/capabilities/file-integrity/basic-settings.rst
  source/user-manual/capabilities/file-integrity/creating-custom-fim-rules.rst
  source/user-manual/capabilities/file-integrity/fim-configuration.rst
  source/user-manual/capabilities/file-integrity/fim-fields-rule-mapping.rst
  source/user-manual/capabilities/file-integrity/how-it-works.rst
  source/user-manual/capabilities/file-integrity/how-to-configure-fim.rst
  source/user-manual/capabilities/file-integrity/index.rst
  source/user-manual/capabilities/file-integrity/interpreting-fim-module-analysis.rst
  source/user-manual/capabilities/file-integrity/use-cases/detecting-account-manipulation.rst
  source/user-manual/capabilities/file-integrity/use-cases/detecting-malware-persistence-technique.rst
  source/user-manual/capabilities/file-integrity/use-cases/index.rst
  source/user-manual/capabilities/file-integrity/use-cases/monitoring-configuration-changes.rst
  source/user-manual/capabilities/file-integrity/use-cases/monitoring-files-at-specific-intervals.rst
  source/user-manual/capabilities/file-integrity/use-cases/reporting-file-changes.rst
  source/user-manual/capabilities/file-integrity/windows-registry-monitoring.rst
Labels: priority: high, type: refactor

#6080 Remove the `Auditing who-data` section
  source/_static/js/redirects.js
  source/container-security/docker-monitor/monitoring-docker-server.rst
  source/proof-of-concept-guide/poc-file-integrity-monitoring.rst
  source/release-notes/release-3-4-0.rst
  source/user-manual/capabilities/auditing-whodata/index.rst
  source/user-manual/capabilities/auditing-whodata/who-linux.rst
  source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst
  source/user-manual/capabilities/auditing-whodata/who-windows.rst
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
  source/user-manual/capabilities/index.rst
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: priority: high, type: refactor

#6096 Section update: Single sign-on 4.4
  source/user-manual/user-administration/single-sign-on/azure-active-directory.rst
  source/user-manual/user-administration/single-sign-on/google.rst
  source/user-manual/user-administration/single-sign-on/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/keycloak.rst
  source/user-manual/user-administration/single-sign-on/okta.rst
  source/user-manual/user-administration/single-sign-on/onelogin.rst
  source/user-manual/user-administration/single-sign-on/pingone.rst
Labels: priority: high, type: refactor

#6104 Section update: Single sign-on 4.3
  source/user-manual/user-administration/single-sign-on/azure-active-directory.rst
  source/user-manual/user-administration/single-sign-on/google.rst
  source/user-manual/user-administration/single-sign-on/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/keycloak.rst
  source/user-manual/user-administration/single-sign-on/okta.rst
  source/user-manual/user-administration/single-sign-on/onelogin.rst
  source/user-manual/user-administration/single-sign-on/pingone.rst
Labels: priority: high, type: refactor

#6093 Section update: File integrity monitoring
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
  source/user-manual/capabilities/file-integrity/creating-custom-fim-rules.rst
  source/user-manual/capabilities/file-integrity/use-cases/detecting-account-manipulation.rst
  source/user-manual/capabilities/file-integrity/use-cases/detecting-malware-persistence-technique.rst
  source/user-manual/capabilities/file-integrity/use-cases/monitoring-configuration-changes.rst
  source/user-manual/capabilities/file-integrity/use-cases/monitoring-files-at-specific-intervals.rst
  source/user-manual/capabilities/file-integrity/use-cases/reporting-file-changes.rst
  source/user-manual/capabilities/file-integrity/windows-registry-monitoring.rst
Labels: priority: medium, type: refactor

#6107 Fixed supported python version from 3.7 and above
  source/azure/activity-services/prerequisites/dependencies.rst
  source/container-security/docker-monitor/dependencies.rst
  source/gcp/prerequisites/dependencies.rst
Labels: type/bug

#6108 Wazuh 4.4.2 release notes
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-2.rst
Labels: release notes

#6109 Update File integrity monitoring on 4.5
  source/images/manual/fim/click-on-add.png
  source/images/manual/fim/click-on-advanced.png
  source/images/manual/fim/successful-entry-in-the-auditing-tab.png
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
Labels: priority: high, type: refactor

#6110 Update File integrity monitoring on 4.4
  source/images/manual/fim/click-on-add.png
  source/images/manual/fim/click-on-advanced.png
  source/images/manual/fim/successful-entry-in-the-auditing-tab.png
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
Labels: priority: high, type: refactor

#6083 Wazuh v4.4.2 documentation
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/amazon/services/prerequisites/dependencies.rst
  source/amazon/services/supported-services/index.rst
  source/amazon/services/supported-services/security-lake.rst
  source/amazon/services/troubleshooting.rst
  source/azure/activity-services/prerequisites/dependencies.rst
  source/conf.py
  source/container-security/docker-monitor/dependencies.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/gcp/prerequisites/dependencies.rst
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-2.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
  source/user-manual/reference/tools/cluster-control.rst
Labels: Pending release

#6105 Section update: Monitoring system calls
  source/_static/js/redirects.js
  source/images/manual/system-calls-monitoring/audit-configuration-alerts.png
  source/images/manual/system-calls-monitoring/change-permissions-alert.png
  source/images/manual/system-calls-monitoring/create-a-new-file-alert.png
  source/images/manual/system-calls-monitoring/delete-file-alert.png
  source/images/manual/system-calls-monitoring/execute-access-alert.png
  source/images/manual/system-calls-monitoring/monitoring-commands-run-as-root.png
  source/images/manual/system-calls-monitoring/root-commands-alerts.png
  source/images/manual/system-calls-monitoring/test-the-configuration.png
  source/images/manual/system-calls-monitoring/write-access-alert.png
  source/user-manual/capabilities/system-calls-monitoring/audit-configuration.rst
  source/user-manual/capabilities/system-calls-monitoring/how-it-works.rst
  source/user-manual/capabilities/system-calls-monitoring/index.rst
  source/user-manual/capabilities/system-calls-monitoring/use-cases/index.rst
  source/user-manual/capabilities/system-calls-monitoring/use-cases/monitoring-commands-run-as-root.rst
  source/user-manual/capabilities/system-calls-monitoring/use-cases/monitoring-file-and-directory-access.rst
  source/user-manual/capabilities/system-calls-monitoring/use-cases/privilege-abuse.rst
Labels: priority: high, type: refactor

#6116 Section update: System inventory
  source/_static/js/redirects.js
  source/amazon/instances.rst
  source/getting-started/use-cases/system-inventory.rst
  source/images/manual/system-inventory/api-console.png
  source/images/manual/system-inventory/download-csv.png
  source/images/manual/system-inventory/generate-report.png
  source/images/manual/system-inventory/inventory-data-tab.png
  source/images/manual/system-inventory/inventory-data.png
  source/images/manual/system-inventory/port-opening-operation-alert.png
  source/images/manual/system-inventory/query-the-inventory-data.png
  source/pci-dss/system-inventory.rst
  source/user-manual/capabilities/index.rst
  source/user-manual/capabilities/syscollector.rst
  source/user-manual/capabilities/system-inventory/available-inventory-fields.rst
  source/user-manual/capabilities/system-inventory/compatibility-matrix.rst
  source/user-manual/capabilities/system-inventory/configuration.rst
  source/user-manual/capabilities/system-inventory/generating-system-inventory-reports.rst
  source/user-manual/capabilities/system-inventory/how-it-works.rst
  source/user-manual/capabilities/system-inventory/index.rst
  source/user-manual/capabilities/system-inventory/using-syscollector-information-to-trigger-alerts.rst
  source/user-manual/capabilities/system-inventory/viewing-system-inventory-data.rst
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
  source/user-manual/ruleset/custom.rst
Labels: priority: high, type: refactor

#6119 Add Wazuh dashboard screenshots
  source/amazon/services/prerequisites/considerations.rst
  source/gcp/prerequisites/considerations.rst
  source/github/monitoring-github-activity.rst
  source/images/aws/aws-dashboard-event.png
  source/images/aws/aws-dashboard.png
  source/images/aws/aws-events.png
  source/images/aws/aws-module.png
  source/images/gcp/gcp-dashboard-event.png
  source/images/gcp/gcp-dashboard.png
  source/images/gcp/gcp-events.png
  source/images/gcp/gcp-module.png
  source/images/github/github-dashboard-event.png
  source/images/github/github-dashboard.png
  source/images/github/github-events.png
  source/images/github/github-module.png
  source/images/office365/office365-dashboard-event.png
  source/images/office365/office365-dashboard.png
  source/images/office365/office365-events.png
  source/images/office365/office365-module.png
  source/office365/monitoring-office365-activity.rst
Labels: Documentation improvements

#6010 Added new section to increase visibility of feature for cloud services
  source/amazon/services/prerequisites/considerations.rst
  source/gcp/prerequisites/considerations.rst
  source/github/monitoring-github-activity.rst
  source/images/aws/aws-dashboard.png
  source/images/aws/aws-events.png
  source/images/aws/aws-module.png
  source/images/gcp/gcp-dashboard.png
  source/images/gcp/gcp-events.png
  source/images/gcp/gcp-module.png
  source/images/github/github-dashboard.png
  source/images/github/github-events.png
  source/images/github/github-module.png
  source/images/office365/office365-dashboard.png
  source/images/office365/office365-events.png
  source/images/office365/office365-module.png
  source/office365/monitoring-office365-activity.rst
Labels: Documentation improvements

#6134 Section rework: Enhancing detection with MITRE ATT&CK framework
  source/images/manual/mitre/dashboard-tab.png
  source/images/manual/mitre/events-filters.png
  source/images/manual/mitre/events-tab.png
  source/images/manual/mitre/framework-tab.png
  source/images/manual/mitre/intelligence-tab.png
  source/images/manual/mitre/mitre-att&ck-module.png
  source/images/manual/mitre/mitre-id-t1110-information.png
  source/images/manual/mitre/visualize-the-alerts.png
  source/user-manual/ruleset/mitre.rst
Labels: priority: high, type: refactor
