Repository wazuh/wazuh-documentation, pull requests merged in 2023-10, with the labels that each got.

#6579 Fix typos on nginx-scheme image
  source/images/cloud-service/nginx-scheme.png
Labels: hacktoberfest-accepted

#6568 Update osd version to 2.10.0
  source/user-manual/user-administration/single-sign-on/administrator/azure-active-directory.rst
  source/user-manual/user-administration/single-sign-on/administrator/google.rst
  source/user-manual/user-administration/single-sign-on/administrator/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/administrator/keycloak.rst
  source/user-manual/user-administration/single-sign-on/administrator/okta.rst
  source/user-manual/user-administration/single-sign-on/administrator/onelogin.rst
  source/user-manual/user-administration/single-sign-on/administrator/pingone.rst
  source/user-manual/user-administration/single-sign-on/read-only/azure-active-directory.rst
  source/user-manual/user-administration/single-sign-on/read-only/google.rst
  source/user-manual/user-administration/single-sign-on/read-only/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/read-only/keycloak.rst
  source/user-manual/user-administration/single-sign-on/read-only/okta.rst
  source/user-manual/user-administration/single-sign-on/read-only/onelogin.rst
  source/user-manual/user-administration/single-sign-on/read-only/pingone.rst
  source/user-manual/wazuh-dashboard/queries.rst
Labels: level/task, type/change

#6586 Solaris 10 installation and upgrade process review
  source/installation-guide/wazuh-agent/wazuh-agent-package-solaris.rst
  source/upgrade-guide/wazuh-agent/solaris.rst
Labels: level/task, type/bug

#6591 Add K8s password change to documentation
  source/deployment-options/deploying-with-kubernetes/kubernetes-deployment.rst
Labels: level/task, type/enhancement

#6557 Remove deprecated plain text auth examples for AWS and Azure wodles
  source/cloud-security/amazon/services/prerequisites/considerations.rst
  source/cloud-security/amazon/services/prerequisites/credentials.rst
  source/cloud-security/azure/activity-services/prerequisites/considerations.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: level/task, type/bug

#6620 Source field is not available for rpm format pkgs
  source/user-manual/capabilities/system-inventory/available-inventory-fields.rst
Labels: level/task, type/bug

#6622 Clarifying use of centralized configuration options
  source/user-manual/reference/centralized-configuration.rst
Labels: level/task, type/bug

#6570 Improve GCP wodle options descriptions
  source/cloud-security/gcp/supported-services/access_logs.rst
  source/cloud-security/gcp/supported-services/dns_queries.rst
  source/cloud-security/gcp/supported-services/index.rst
  source/user-manual/reference/ossec-conf/gcp-bucket.rst
  source/user-manual/reference/ossec-conf/gcp-pubsub.rst
Labels: level/task, type/bug

#6640 Changed Windows agent support in Ansible deployment
  source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-agent.rst
Labels: level/task, type/bug

#6637 Update links to the `wazuh-kibana-app` repo
  CONTRIBUTING.md
  source/migration-guide/index.rst
  source/user-manual/wazuh-dashboard/settings.rst
Labels: level/task, type/change

#6650 Update Wazuh v4.6.0 release notes
  source/release-notes/release-4-6-0.rst
Labels: hacktoberfest-accepted

#6651 Fix Virustotal "How it works" documentation
  source/user-manual/capabilities/malware-detection/virus-total-integration.rst
Labels: level/task, type/bug

#6653 Removed reference for Wazuh indexer and dashboard mixed node from Readme file of production ready deployment with Ansible
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-cluster.rst
Labels: level/task, type/change

#6673 Add update_check config reference
  source/user-manual/reference/ossec-conf/global.rst
Labels: level/task, type/enhancement

#6686 Improved offline installation steps
  source/deployment-options/offline-installation.rst
Labels: level/task, type/enhancement

#6705 Update vacuum default settings
  source/user-manual/reference/internal-options.rst
Labels: level/task, type/bug

#5942 Add new setting queue_size inside whodata configuration block
  source/user-manual/reference/ossec-conf/syscheck.rst
Labels: pending-core, core/fim

#6691 Enable alert forwarding to Fluentd for Analysisd
  source/user-manual/manager/fluent-forwarder.rst
Labels: use cases, core/analysisd, level/task, type/enhancement
