Repository wazuh/wazuh-documentation, pull requests merged in 2023-04, with the labels that each got.

#6015 POC VirusTotal changes
  source/images/poc/virustotal-remove-malware-linux-alert.png
  source/images/poc/virustotal-remove-malware-windows-alert.png
  source/proof-of-concept-guide/detect-remove-malware-virustotal.rst
Labels: priority: high, Documentation improvements

#6013 Wazuh 4.4.1 release notes and versions update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-1.rst
Labels: release notes, priority: high

#6019 Wazuh v4.4.1 documentation update
  source/_static/js/redirects.js
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-4-1.rst
  source/user-manual/api/configuration.rst
Labels: Pending release

#6023 Upgrade guide grammar review
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.rst
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.rst
  source/upgrade-guide/index.rst
  source/upgrade-guide/legacy/index.rst
  source/upgrade-guide/legacy/upgrading-agent/from-1.x-to-2.x.rst
  source/upgrade-guide/legacy/upgrading-agent/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-agent/index.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.8-to-7.x.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.x-to-6.8.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/upgrade-guide/wazuh-agent/aix.rst
  source/upgrade-guide/wazuh-agent/linux.rst
  source/upgrade-guide/wazuh-agent/macos.rst
  source/upgrade-guide/wazuh-agent/solaris.rst
Labels: priority: high, type/enhancement

#5972 Add var requirement in ruleset
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: type: refactor

#6030 Bump version to 4.4.2
  source/_templates/installations/basic/elastic/common/install_wazuh_kibana_plugin.rst
  source/_templates/installations/basic/wazuh/common/check_wazuh_cluster.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s10_sparc.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_intel.rst
  source/_templates/installations/wazuh/solaris/install_wazuh_agent_s11_sparc.rst
  source/conf.py
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.rst
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
Labels: priority: high, Pending release

#6038 Adjust ossec issue
  source/user-manual/reference/ossec-conf/global.rst
Labels: priority: medium, type/enhancement

#6042 4.3 Upgrade guide grammar review
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.rst
  source/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-open-distro.rst
  source/upgrade-guide/index.rst
  source/upgrade-guide/legacy/index.rst
  source/upgrade-guide/legacy/upgrading-agent/from-1.x-to-2.x.rst
  source/upgrade-guide/legacy/upgrading-agent/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-agent/index.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.8-to-7.x.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/from-6.x-to-6.8.rst
  source/upgrade-guide/legacy/upgrading-elastic-stack/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/from-2.x-to-3.x.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/index.rst
  source/upgrade-guide/legacy/upgrading-wazuh-server/restore-alerts-from-2.x-to-3.x.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/upgrade-guide/wazuh-agent/aix.rst
  source/upgrade-guide/wazuh-agent/linux.rst
  source/upgrade-guide/wazuh-agent/macos.rst
  source/upgrade-guide/wazuh-agent/solaris.rst
Labels: priority: high, type/enhancement

#6065 Capabilities sections to be moved
  source/_static/js/redirects.js
  source/release-notes/release-2-1.rst
  source/user-manual/agents/antiflooding.rst
  source/user-manual/agents/index.rst
  source/user-manual/agents/labels.rst
  source/user-manual/capabilities/index.rst
  source/user-manual/manager/fluent-forwarder.rst
  source/user-manual/manager/index.rst
  source/user-manual/reference/centralized-configuration.rst
  source/user-manual/user-administration/rbac.rst
Labels: priority: high, type: infrastructure

#6043 Wazuh 4.3.11 release notes for 4.4
  source/_static/js/redirects.js
  source/release-notes/index-4x.rst
  source/release-notes/index.rst
  source/release-notes/release-4-3-11.rst
Labels: release notes, priority: high
