Repository wazuh/wazuh-documentation, pull requests merged in 2024-09, with the labels that each got.

#7729 Restore AIX packages and purge Alpine references
  source/_templates/installations/wazuh/apk/add_repository.rst
  source/_templates/installations/wazuh/apk/disabling_repository.rst
  source/_templates/installations/wazuh/apk/uninstall_wazuh_agent.rst
  source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst
  source/_variables/replacements.py
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
  source/development/packaging/generate-wpk-package.rst
  source/installation-guide/packages-list.rst
  source/installation-guide/uninstalling-wazuh/agent.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-linux.rst
  source/upgrade-guide/wazuh-agent/linux.rst
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
Labels: level/task, type/bug, module/install, module/upgrade

#7580 Add new config block anti_tampering
  source/_static/js/redirects.js
  source/user-manual/reference/ossec-conf/anti-tampering.rst
  source/user-manual/reference/ossec-conf/index.rst
Labels: level/task, type/change

#7728 Enhance Cloud Service FAQs When EPS Limits Are Exceeded
  source/cloud-service/getting-started/starting-faq.rst
Labels: level/task, type/enhancement

#7758 Fix missing slash in localfile block at Logcollector reference
  source/user-manual/reference/ossec-conf/localfile.rst
Labels: level/task, type/bug

#7755 Added package dependencies to Offline documentation
  source/deployment-options/offline-installation/installation-assistant.rst
  source/deployment-options/offline-installation/step-by-step.rst
Labels: level/task, type/bug

#7763 Reverted to the prefix word
  source/cloud-security/amazon/services/supported-services/index.rst
Labels: level/task, type/bug

#7764 Update SECURITY.md
  SECURITY.md
Labels: level/task, type/enhancement

#7776 Removed aarch64 from manager package list
  source/_variables/replacements.py
  source/installation-guide/packages-list.rst
Labels: level/task, type/change

#7806 Add ARM64 Packages for Wazuh Manager
  source/installation-guide/packages-list.rst
Labels: packages

#7810 Remove step to delete ss4o index templates before a wazuh-indexer upgrade
  source/upgrade-guide/upgrading-central-components.rst
Labels: level/task, type/change

#7819 Remove the certificate blob copy instruction
  source/user-manual/user-administration/single-sign-on/administrator/okta.rst
  source/user-manual/user-administration/single-sign-on/read-only/okta.rst
Labels: level/task, type/change

#7818 Add SSO section to upgrade troubleshooting guide
  source/upgrade-guide/troubleshooting.rst
Labels: level/task, type/change

#7814 Update Uninstalling Documentation on Wazuh Server
  source/_templates/installations/wazuh/common/disable_wazuh_manager_service.rst
  source/installation-guide/uninstalling-wazuh/central-components.rst
Labels: level/task, type/change
