Repository wazuh/wazuh-documentation, pull requests merged in 2024-07, with the labels that each got.

#7487 Use document references instead of anchors
  source/cloud-security/amazon/services/supported-services/cisco-umbrella.rst
  source/cloud-security/amazon/services/supported-services/cloudtrail.rst
  source/cloud-security/amazon/services/supported-services/cloudwatchlogs.rst
  source/cloud-security/amazon/services/supported-services/config.rst
  source/cloud-security/amazon/services/supported-services/custom-buckets.rst
  source/cloud-security/amazon/services/supported-services/ecr-image-scanning.rst
  source/cloud-security/amazon/services/supported-services/elastic-load-balancing/alb.rst
  source/cloud-security/amazon/services/supported-services/elastic-load-balancing/clb.rst
  source/cloud-security/amazon/services/supported-services/elastic-load-balancing/nlb.rst
  source/cloud-security/amazon/services/supported-services/guardduty.rst
  source/cloud-security/amazon/services/supported-services/index.rst
  source/cloud-security/amazon/services/supported-services/inspector.rst
  source/cloud-security/amazon/services/supported-services/kms.rst
  source/cloud-security/amazon/services/supported-services/macie.rst
  source/cloud-security/amazon/services/supported-services/security-lake.rst
  source/cloud-security/amazon/services/supported-services/server-access.rst
  source/cloud-security/amazon/services/supported-services/trusted-advisor.rst
  source/cloud-security/amazon/services/supported-services/vpc.rst
  source/cloud-security/amazon/services/supported-services/waf.rst
  source/cloud-security/amazon/services/troubleshooting.rst
Labels: level/task, type/enhancement

#7498 Use launchctl to start and stop macos agent
  source/installation-guide/uninstalling-wazuh/agent.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-macos.rst
  source/migration-guide/files-backup/restoring/wazuh-agent.rst
Labels: level/task, type/enhancement

#7501 Add description and note for new parameters to `generate_wazuh_msi.ps1` script to sign Windows packages
  source/development/packaging/generate-windows-package.rst
Labels: level/task, type/enhancement

#7517 Fix image tag for certificate creator
  source/deployment-options/docker/wazuh-container.rst
Labels: level/task, type/bug

#7499 Updating with new parameters of Wazuh Keystore
  source/deployment-options/offline-installation/step-by-step.rst
  source/installation-guide/wazuh-server/step-by-step.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst
  source/user-manual/reference/tools/wazuh-keystore.rst
Labels: level/task, type/enhancement

#7527 Change IPs into Ansible Doc
  source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-agent.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-cluster.rst
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-manager.rst
  source/deployment-options/deploying-with-ansible/roles/wazuh-agent.rst
  source/deployment-options/deploying-with-ansible/roles/wazuh-dashboard.rst
  source/deployment-options/deploying-with-ansible/roles/wazuh-indexer.rst
  source/deployment-options/deploying-with-ansible/roles/wazuh-manager.rst
Labels: level/task, type/enhancement

#7481 Added documentation for Wazuh certificates tool in Docker
  source/installation-guide/wazuh-indexer/step-by-step.rst
  source/user-manual/wazuh-indexer/certificates.rst
Labels: level/task, type/enhancement

#7485 Added warning note for Ansible deployment when using macOS as Ansible node
  source/deployment-options/deploying-with-ansible/guide/install-wazuh-cluster.rst
Labels: level/task, type/change

#7530 Revert version of `azure-storage-blob`
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
Labels: level/task, type/bug

#7572 Updating settings documentation
  source/cloud-service/your-environment/settings.rst
Labels: level/task, type/enhancement

#7571 Fix installation commands for each component in Offline Assisted Installation
  source/deployment-options/offline-installation/installation-assistant.rst
Labels: level/task, type/bug

#7577 Update GCP wodle storage required roles
  source/cloud-security/gcp/prerequisites/credentials.rst
Labels: level/task, type/bug

#7583 Fix Indexer/dashboard management sections references
  source/cloud-service/your-environment/manage-auth.rst
  source/migration-guide/files-backup/restoring/wazuh-central-components.rst
  source/user-manual/capabilities/system-inventory/generating-system-inventory-reports.rst
  source/user-manual/user-administration/ldap.rst
  source/user-manual/user-administration/single-sign-on/read-only/google.rst
  source/user-manual/user-administration/single-sign-on/read-only/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/read-only/keycloak.rst
  source/user-manual/user-administration/single-sign-on/read-only/microsoft-entra-id.rst
  source/user-manual/user-administration/single-sign-on/read-only/okta.rst
  source/user-manual/user-administration/single-sign-on/read-only/onelogin.rst
  source/user-manual/user-administration/single-sign-on/read-only/pingone.rst
  source/user-manual/wazuh-dashboard/config-file.rst
  source/user-manual/wazuh-dashboard/custom-branding.rst
  source/user-manual/wazuh-indexer/re-indexing.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-indices.rst
Labels: level/task, type/bug

#7579 Enhancement Matrix Compatibility VD
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
Labels: level/task, type/enhancement

#7587 Add --api parameter when changing the API users passwords
  source/deployment-options/offline-installation.rst
  source/installation-guide/wazuh-dashboard/step-by-step.rst
  source/user-manual/user-administration/password-management.rst
Labels: level/task, type/bug

#7586 Split Security Lake integration docs into Source and Subscriber sections
  source/_static/js/redirects.js
  source/cloud-security/amazon/services/supported-services/amazon-security-lake/index.rst
  source/cloud-security/amazon/services/supported-services/index.rst
  source/cloud-security/amazon/services/supported-services/security-lake.rst
  source/integrations-guide/amazon-security-lake/index.rst
  source/integrations-guide/index.rst
Labels: level/task, type/change

#7589 Add `NumPy` dependency to AWS requirements
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
Labels: level/task, type/bug

#7593 Backport: Updating with new parameters of Wazuh Keystore
  source/deployment-options/offline-installation/step-by-step.rst
  source/installation-guide/wazuh-server/step-by-step.rst
  source/upgrade-guide/troubleshooting.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/user-manual/capabilities/vulnerability-detection/configuring-scans.rst
  source/user-manual/reference/tools/wazuh-keystore.rst
Labels: level/task, type/enhancement
