Repository wazuh/wazuh-documentation, pull requests merged in 2024-08, with the labels that each got.

#7629 Remove SCA for Rocky Linux 8
  source/release-notes/release-4-8-0.rst
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/change

#7644 Move SCA policies for Rocky Linux 8 to 4.9.0
  source/release-notes/release-4-9-0.rst
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: release notes, type/enhancement

#7646 Fixed PDF custom branding logo property
  CHANGELOG.md
  source/user-manual/wazuh-dashboard/custom-branding.rst
Labels: level/task, type/bug

#7641 Enhance Architecture Diagram with Vulnerability Detection and Indexer Connection Details
  source/getting-started/architecture.rst
  source/images/getting-started/deployment-architecture.png
Labels: level/task, type/bug

#7649 Improve security hub docs
  source/cloud-security/amazon/services/supported-services/security-hub.rst
  source/images/aws/security-hub-s3-1.png
  source/images/aws/security-hub-s3-2.png
  source/images/aws/security-hub-sqs-1.png
  source/images/aws/security-hub-sqs-2.png
  source/images/aws/security-hub-sqs-3.png
Labels: level/task, type/enhancement

#7652 Repaired wazuh-template.json links
  source/user-manual/manager/wazuh-server-cluster.rst
  source/user-manual/upscaling/adding-server-node.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-indices.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-tuning.rst
Labels: level/task, type/bug

#7668 Bug/24943 update gcp posture documentation
  source/cloud-security/gcp/posture-management.rst
Labels: level/task, type/bug

#7661 Add MDM Intune integration mentions in documentation
  source/cloud-security/ms-graph/index.rst
  source/cloud-security/ms-graph/monitoring-ms-graph-activity.rst
  source/images/cloud-security/ms-graph/4-azure-wazuh-app-configure-permissions-intune.png
  source/user-manual/reference/ossec-conf/ms-graph-module.rst
Labels: level/task, type/enhancement

#7665 Change documentation of custom loading logo
  source/images/kibana-app/features/white-labeling/custom-branding-settings-loading-page.png
  source/user-manual/wazuh-dashboard/custom-branding.rst
Labels: level/task, type/bug

#7684 References to PowerPC packages removed
  source/installation-guide/packages-list.rst
Labels: level/task, type/change

#7678 Add the step of restarting Wazuh-dashboard when modifying logos
  source/user-manual/wazuh-dashboard/custom-branding.rst
Labels: level/task, type/bug

#7669 Change create wazuh-archives index pattern gif
  source/images/manual/wazuh-server/creating-wazuh-archives-index-pattern.gif
  source/user-manual/manager/event-logging.rst
Labels: level/task, type/bug

#7677 Update VD compatilibty matrix
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
Labels: level/task, type/bug

#7702 Updating SSH key path for agentless connection
  source/user-manual/capabilities/agentless-monitoring/connection.rst
Labels: level/task, type/enhancement

#7685 Add step that sets the policy's initial state
  source/images/manual/wazuh-indexer/ism-policy-states.png
  source/user-manual/wazuh-indexer/index-life-management.rst
Labels: level/task, type/enhancement

#7697 Change/7695 Update Available SCA Documentation
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/change

#7673 Add compatibility with Python 3.12
  source/_templates/cloud/pip_installation.rst
  source/_variables/replacements.py
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
  source/cloud-security/gcp/prerequisites/dependencies.rst
  source/proof-of-concept-guide/monitoring-docker.rst
  source/user-manual/capabilities/container-security/monitoring-docker.rst
Labels: level/task, type/enhancement

#7708 Add agent uninstall RBAC action
  source/user-manual/api/rbac/reference.rst
Labels: level/task, type/enhancement

#7710 Fix wazuh-template.json link to use GitHub tag instead of minor branch
  source/user-manual/manager/wazuh-server-cluster.rst
  source/user-manual/upscaling/adding-server-node.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-indices.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-tuning.rst
Labels: level/task, type/bug

#7714 Revert cluster async tasks documentation changes
  CHANGELOG.md
  source/development/wazuh-cluster.rst
  source/images/development/cluster-process-pool.png
Labels: level/task, type/change
