Repository wazuh/wazuh-documentation, pull requests merged in 2024-10, with the labels that each got.

#7511 Add AWS WAF native
  source/cloud-security/amazon/services/supported-services/index.rst
  source/cloud-security/amazon/services/supported-services/waf.rst
  source/images/cloud-security/aws/waf-native-1.png
  source/images/cloud-security/aws/waf-native-2.png
  source/images/cloud-security/aws/waf-native-3.png
  source/images/cloud-security/aws/waf-native-4.png
  source/images/cloud-security/aws/waf-native-5.png
  source/images/cloud-security/aws/waf-native-6.png
  source/images/cloud-security/aws/waf-native-7.png
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: level/task, type/enhancement

#7784 Add Cloud's Custom DNS feature documentation
  source/_static/js/redirects.js
  source/cloud-service/your-environment/custom-dns.rst
  source/cloud-service/your-environment/index.rst
Labels: level/task, type/enhancement

#7830 Added architecture information to assistant pages
  CHANGELOG.md
  source/deployment-options/offline-installation/index.rst
  source/deployment-options/offline-installation/installation-assistant.rst
  source/installation-guide/wazuh-dashboard/installation-assistant.rst
  source/installation-guide/wazuh-indexer/installation-assistant.rst
  source/installation-guide/wazuh-server/installation-assistant.rst
  source/quickstart.rst
Labels: level/task, type/enhancement

#7855 Remove cache configuration option
  source/user-manual/api/configuration.rst
Labels: level/task, type/bug

#7864 Support new OSs - macOS Sequoia 15 - Update list of SCAs
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/enhancement

#7860 Updated documentation on AMI passwords
  source/deployment-options/amazon-machine-images/amazon-machine-images.rst
Labels: level/task, type/bug

#7859 Add new steps for upgrade Wazuh Docker and Kubernetes
  source/deployment-options/deploying-with-kubernetes/kubernetes-upgrade.rst
  source/deployment-options/docker/upgrading-wazuh-docker.rst
Labels: level/task, type/enhancement

#7877 Fixed permission issues for Wazuh-db restoration in 4.9
  source/migration-guide/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7882 Fixed permission issues for Wazuh-db restoration in 4.8
  source/migration-guide/files-backup/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7881 Fixed permission issues for Wazuh-db restoration in 4.7
  source/migration-guide/files-backup/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7880 Fixed permission issues for Wazuh-db restoration in 4.6
  source/user-manual/files-backup/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7879 Fixed permission issues for Wazuh-db restoration in 4.5
  source/user-manual/files-backup/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7878 Fixed permission issues for Wazuh-db restoration in 4.4
  source/user-manual/files-backup/restoring/wazuh-central-components.rst
Labels: level/task, type/bug

#7861 Explain with more detail the alerts behavior
  source/images/manual/vuln-detector/vuln-detector-workflow.png
  source/proof-of-concept-guide/poc-vulnerability-detection.rst
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
Labels: level/task, type/enhancement

#7907 Explain with more detail the alerts behavior - 4.9 changes
  source/images/manual/vuln-detector/vuln-detector-workflow.png
  source/proof-of-concept-guide/poc-vulnerability-detection.rst
  source/user-manual/capabilities/vulnerability-detection/how-it-works.rst
Labels: level/task, type/enhancement

#7909 Update time and weekday options in rules syntax
  source/user-manual/ruleset/ruleset-xml-syntax/rules.rst
Labels: level/task, type/change

#7920 Update Puppet URL into installation process
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
Labels: level/task, type/bug

#7918 Remove Unsupported OS from Package List
  source/installation-guide/packages-list.rst
Labels: level/task, type/bug

#7926 Change wazuh-packages to wazuh-virtual-machines refs in ova generation
  source/development/packaging/generate-ova.rst
Labels: level/task, type/change

#7932 Add gnupg dependecy into Ansible install
  source/deployment-options/deploying-with-ansible/guide/install-ansible.rst
Labels: level/task, type/bug

#7931 Added missing dependencies to the assisted offline installation
  source/deployment-options/offline-installation/installation-assistant.rst
Labels: level/task, type/bug

#7929 Add steps for wazuh-docker upgrade
  source/deployment-options/docker/upgrading-wazuh-docker.rst
Labels: level/task, type/bug

#7930 Fixing OpenSearch version in Release Notes for 4.9.0
  source/release-notes/release-4-9-0.rst
Labels: level/task, type/bug

#7933 Update API host default value
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.rst
  source/development/rbac-database-integrity.rst
  source/user-manual/api/configuration.rst
  source/user-manual/api/securing-api.rst
Labels: level/task, type/bug
