Repository wazuh/wazuh-documentation, pull requests merged in 2024-01, with the labels that each got.

#6694 Fixes step of Azure Storage documentation.
  source/cloud-security/azure/activity-services/services/storage.rst
  source/images/cloud-security/azure/storage-activity-1.png
  source/images/cloud-security/azure/storage-activity-2.png
  source/images/cloud-security/azure/storage-activity-3.png
  source/images/cloud-security/azure/storage-activity-4.png
Labels: level/task, type/bug

#6918 Add download content to installation
  source/deployment-options/wazuh-from-sources/wazuh-server/index.rst
Labels: level/task, type/enhancement

#6920 Added offline installation with the assistant
  source/_static/js/redirects.js
  source/deployment-options/index.rst
  source/deployment-options/offline-installation/index.rst
  source/deployment-options/offline-installation/installation-assistant.rst
  source/deployment-options/offline-installation/step-by-step.rst
Labels: level/task, type/enhancement

#6927 Fix AWS name references
  source/getting-started/use-cases/posture-management.rst
  source/user-manual/agents/labels.rst
Labels: level/task, type/bug

#6930 Add reset password process
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
Labels: level/task, type/bug

#6948 Add the security updates to 4.5.3 release notes
  source/release-notes/release-4-5-3.rst
Labels: release notes, level/task, type/bug

#6949 Add the security updates to 4.5.3 release notes
  source/release-notes/release-4-5-3.rst
Labels: release notes, level/task, type/bug

#6950 Add the security updates to 4.5.3 release notes
  source/release-notes/release-4-5-3.rst
Labels: release notes, level/task, type/bug

#6954 Add wazuh::repo class in agent instalation
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
Labels: level/task, type/bug

#6945 Add `-i` option to command in offline installation documentation
  source/deployment-options/offline-installation.rst
Labels: level/task, type/bug

#6958 Remove the modification of number of shards from the offline installation
  source/deployment-options/offline-installation.rst
Labels: level/task, type/bug

#6956 Update security lake module name
  source/cloud-security/amazon/services/supported-services/security-lake.rst
  source/images/aws/security-lake-1.png
Labels: level/task, type/change

#6967 Updated password tool documentation for distributed deployments
  source/user-manual/user-administration/password-management.rst
Labels: level/task, type/bug

#6953 Check first if the file detected by VirusTotal was already removed.
  source/proof-of-concept-guide/detect-remove-malware-virustotal.rst
Labels: level/task, type/bug

#6972 Fix cloud service docs redirections
  source/_static/js/redirects.js
  source/_variables/redirect_same_release.py
Labels: level/task, type/bug

#6964 Update GCP documentation
  source/cloud-security/gcp/prerequisites/credentials.rst
  source/cloud-security/gcp/prerequisites/pubsub.rst
  source/images/cloud-security/gcp/gcp-topic.png
Labels: level/task, type/enhancement

#6962 Update MITRE documentation
  source/images/manual/mitre/dashboard-tab.png
  source/images/manual/mitre/events-filters.png
  source/images/manual/mitre/events-tab.png
  source/images/manual/mitre/framework-tab.png
  source/images/manual/mitre/intelligence-tab.png
  source/images/manual/mitre/mitre-att&ck-module.png
  source/images/manual/mitre/mitre-id-t1543.003-information.png
  source/images/manual/mitre/visualize-the-alerts.png
  source/user-manual/ruleset/mitre.rst
Labels: level/task, type/bug

#6973 Fixes related to build an agent from sources.
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
Labels: Documentation improvements, level/task, type/enhancement

#6974 Add new <global> option <forward_to> to configuration reference
  source/user-manual/reference/ossec-conf/global.rst
  source/user-manual/reference/ossec-conf/socket.rst
Labels: level/task, type/bug

#6988 [4.7] Updated some dependencies
  requirements.txt
  source/_themes/wazuh_doc_theme_v3/package-lock.json
  source/_themes/wazuh_doc_theme_v3/static/js/min/bootstrap.bundle.min.js
Labels: level/task, request/operational, type/bug

#6991 Update 4.8.0 documentation changelog
  CHANGELOG.md
Labels: level/task, request/operational, type/maintenance

#6992 Update 4.9.0 documentation changelog
  CHANGELOG.md
Labels: level/task, request/operational, type/maintenance
