Repository wazuh/wazuh-documentation, pull requests merged in 2024-03, with the labels that each got.

#7058 Update documentation to include the indexer URLs
  source/_templates/installations/manager/configure_indexer_connection.rst
  source/installation-guide/wazuh-server/step-by-step.rst
  source/proof-of-concept-guide/poc-vulnerability-detection.rst
  source/upgrade-guide/upgrading-central-components.rst
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: level/task, type/bug

#7093 Add step to the wazuh-indexer upgrade guide to remove old ss4o templates
  source/upgrade-guide/upgrading-central-components.rst
Labels: level/task, type/bug

#7106 Added deprecated msg to cache API configuration.
  source/user-manual/api/configuration.rst
Labels: level/task, type/change

#7107 Change all references to HP-UX package to tar.gz
  source/development/packaging/generate-hpux-package.rst
  source/installation-guide/packages-list.rst
  source/installation-guide/wazuh-agent/wazuh-agent-package-hpux.rst
  source/upgrade-guide/wazuh-agent/hp-ux.rst
Labels: level/task, type/bug

#7063 Add considerations for max_size API options
  source/user-manual/api/configuration.rst
  source/user-manual/api/getting-started.rst
Labels: level/task, type/enhancement

#7123 Remove launchtl unload step from macOS uninstalling manual
  source/installation-guide/uninstalling-wazuh/agent.rst
Labels: Documentation improvements, macOS, level/task, type/bug

#7135 Add warning about 4.8.0 upgrade
  source/deployment-options/deploying-with-kubernetes/kubernetes-deployment.rst
  source/deployment-options/deploying-with-kubernetes/kubernetes-upgrade.rst
Labels: level/task, type/enhancement

#7120 Fix puppet config steps
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst
  source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.rst
Labels: level/task, type/bug

#7130 Bump cloud services python minimum version to 3.8
  source/_variables/replacements.py
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
  source/cloud-security/gcp/prerequisites/dependencies.rst
Labels: level/task, type/maintenance
