Repository wazuh/wazuh-documentation, pull requests merged in 2024-05, with the labels that each got.

#7234 Changed API configuration step in offline documentation
  source/deployment-options/offline-installation.rst
  source/installation-guide/wazuh-dashboard/step-by-step.rst
Labels: level/task, type/change

#7246 Update WPK documentation: adapt new names and paths
  source/user-manual/agent/agent-management/remote-upgrading/agent-upgrade-module.rst
  source/user-manual/agent/agent-management/remote-upgrading/custom-repository.rst
  source/user-manual/agent/agent-management/remote-upgrading/wpk-list.rst
Labels: level/task, type/enhancement

#7238 Fix GCC version in Centos8
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
  source/deployment-options/wazuh-from-sources/wazuh-server/index.rst
Labels: level/task, type/bug

#7273 Add note for apt installations
  source/upgrade-guide/upgrading-central-components.rst
Labels: level/task, type/enhancement

#7274 Modify Wazuh app and Wazuh plugin references
  CONTRIBUTING.md
  source/cloud-security/gcp/prerequisites/visualizing-events.rst
  source/cloud-service/your-environment/limits.rst
  source/deployment-options/deploying-with-ansible/reference.rst
  source/deployment-options/deploying-with-ansible/roles/wazuh-indexer.rst
  source/deployment-options/deploying-with-kubernetes/kubernetes-conf.rst
  source/deployment-options/docker/data-migration.rst
  source/deployment-options/docker/wazuh-container.rst
  source/migration-guide/index.rst
  source/user-manual/manager/manual-integration.rst
  source/user-manual/reference/daemons/wazuh-modulesd.rst
  source/user-manual/user-administration/single-sign-on/administrator/keycloak.rst
  source/user-manual/user-administration/single-sign-on/read-only/keycloak.rst
  source/user-manual/wazuh-dashboard/queries.rst
Labels: level/task, type/bug

#7145 Wazuh Cloud - Add Canada Region
  source/cloud-service/glossary.rst
  source/cloud-service/your-environment/technical-faq.rst
Labels: level/task, type/maintenance

#7285 Change localhost to 127.0.0.1 in wazuh.yml
  CHANGELOG.md
  source/user-manual/upscaling/adding-server-node.rst
  source/user-manual/user-administration/ldap.rst
  source/user-manual/user-administration/password-management.rst
  source/user-manual/user-administration/single-sign-on/administrator/google.rst
  source/user-manual/user-administration/single-sign-on/administrator/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/administrator/keycloak.rst
  source/user-manual/user-administration/single-sign-on/administrator/microsoft-entra-id.rst
  source/user-manual/user-administration/single-sign-on/administrator/okta.rst
  source/user-manual/user-administration/single-sign-on/administrator/onelogin.rst
  source/user-manual/user-administration/single-sign-on/administrator/pingone.rst
  source/user-manual/user-administration/single-sign-on/read-only/google.rst
  source/user-manual/user-administration/single-sign-on/read-only/jumpcloud.rst
  source/user-manual/user-administration/single-sign-on/read-only/keycloak.rst
  source/user-manual/user-administration/single-sign-on/read-only/microsoft-entra-id.rst
  source/user-manual/user-administration/single-sign-on/read-only/okta.rst
  source/user-manual/user-administration/single-sign-on/read-only/onelogin.rst
  source/user-manual/user-administration/single-sign-on/read-only/pingone.rst
  source/user-manual/wazuh-dashboard/config-file.rst
  source/user-manual/wazuh-dashboard/troubleshooting.rst
Labels: level/task, type/change

#7281 Coredump generation HOWTO for Linux and MacOS Wazuh agents
  source/_static/js/redirects.js
  source/development/coredump.rst
  source/development/index.rst
Labels: level/task, type/enhancement

#7247 Minimum syscollector scan interval set to 60 seconds
  source/user-manual/reference/ossec-conf/wodle-syscollector.rst
Labels: level/task, type/enhancement

#7291 Add note related to 'never,task' rule in auditd
  source/user-manual/capabilities/file-integrity/advanced-settings.rst
Labels: level/task, type/enhancement

#7299 Coredump generation config on Windows endpoints
  source/development/coredump.rst
Labels: level/task, type/enhancement

#7298 Add python and pip installation templates
  source/_templates/cloud/notes.rst
  source/_templates/cloud/pip_installation.rst
  source/_templates/cloud/python_installation.rst
  source/cloud-security/amazon/services/prerequisites/dependencies.rst
  source/cloud-security/azure/activity-services/prerequisites/dependencies.rst
  source/cloud-security/gcp/prerequisites/dependencies.rst
Labels: level/task, type/maintenance

#7316 Update manager installation by sources with the latest changes of VD
  source/deployment-options/wazuh-from-sources/wazuh-server/index.rst
Labels: level/task, type/bug

#7309 Add multiple agents group assignment section
  source/user-manual/agent/agent-management/grouping-agents.rst
Labels: level/task, type/bug

#7223 Wazuh Cloud - Cold Storage Documentation
  source/cloud-service/archive-data/access.rst
  source/cloud-service/cli/index.rst
Labels: level/task, type/enhancement

#7296 Update API script file name
  source/development/selinux-wazuh-context.rst
Labels: level/task, type/bug

#7321 Added warning message in changing passwords in Docker and Kubernetes
  source/deployment-options/deploying-with-kubernetes/kubernetes-deployment.rst
  source/deployment-options/docker/wazuh-container.rst
Labels: level/task, type/enhancement

#7339 Update `internal options` for VD.
  source/user-manual/reference/internal-options.rst
Labels: level/task, type/enhancement

#7347 Core dump config RHLE
  source/development/coredump.rst
Labels: level/task, type/change

#7279 Add HAProxy helper docs
  source/images/manual/cluster/haproxy-helper-architecture.png
  source/images/manual/cluster/haproxy-helper-flow.png
  source/user-manual/manager/configuring-cluster/advanced-settings.rst
  source/user-manual/manager/configuring-cluster/index.rst
  source/user-manual/reference/ossec-conf/cluster.rst
Labels: level/task, type/enhancement

#7355 Add documentation for Wazuh Indexer Packages generation
  source/_static/js/redirects.js
  source/development/packaging/generate-indexer-package.rst
  source/development/packaging/index.rst
Labels: level/task, type/enhancement

#7204 Update documentation after package migration
  source/_static/js/redirects.js
  source/development/packaging/generate-aix-package.rst
  source/development/packaging/generate-deb-package.rst
  source/development/packaging/generate-deb-rpm-package.rst
  source/development/packaging/generate-hpux-package.rst
  source/development/packaging/generate-osx-package.rst
  source/development/packaging/generate-rpm-package.rst
  source/development/packaging/generate-sol-package.rst
  source/development/packaging/generate-windows-package.rst
  source/development/packaging/generate-wpk-package.rst
  source/development/packaging/index.rst
  source/user-manual/agent/agent-management/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.rst
Labels: level/task, type/enhancement

#7310 Add documentation for Wazuh as a custom source ASL integration
  source/_static/js/redirects.js
  source/cloud-security/amazon/services/supported-services/amazon-security-lake/index.rst
  source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-source.rst
  source/cloud-security/amazon/services/supported-services/amazon-security-lake/security-lake-subscriber.rst
  source/cloud-security/amazon/services/supported-services/index.rst
  source/images/aws/asl-custom-source-form.png
  source/images/aws/asl-custom-source.png
  source/images/aws/asl-lambda-trigger.png
  source/images/aws/asl-overview.png
Labels: level/task, type/enhancement
