Repository wazuh/wazuh-documentation, pull requests merged in 2024-02, with the labels that each got.

#6987 Update Azure diagnostic step
  source/cloud-security/azure/activity-services/services/storage.rst
  source/images/cloud-security/azure/storage-activity-3.png
Labels: level/task, type/bug

#7006 Update RBAC reference
  source/user-manual/api/rbac/reference.rst
Labels: level/task, type/bug

#7007 Add mapping users example
  source/user-manual/user-administration/rbac.rst
Labels: level/task, type/bug

#6810 Remove logs.level app setting
  source/cloud-security/amazon/services/troubleshooting.rst
  source/images/kibana-app/features/settings/logs.png
  source/user-manual/wazuh-dashboard/config-file.rst
  source/user-manual/wazuh-dashboard/settings.rst
  source/user-manual/wazuh-dashboard/troubleshooting.rst
Labels: level/task, type/enhancement

#7043 Add Debian 12 to list of available SCA policies
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/bug

#7004 Add Pub/Sub configuration warning
  source/cloud-security/gcp/posture-management.rst
  source/user-manual/reference/ossec-conf/gcp-pubsub.rst
Labels: level/task, type/bug

#7049 Review and update available SCA policies in 4.8.0 version
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/bug

#6853 Add deprecation notes to Syscheck and Syscollector related sections
  source/development/wazuh-cluster.rst
  source/user-manual/api/getting-started.rst
  source/user-manual/api/rbac/reference.rst
  source/user-manual/capabilities/system-inventory/viewing-system-inventory-data.rst
Labels: level/task, type/change

#7056 Fix inconsistency in image
  source/images/single-sign-on/google/03-select-continue-and-configure.png
Labels: level/task, type/bug

#7072 Fix Keystore execution order
  source/deployment-options/offline-installation.rst
  source/installation-guide/wazuh-server/step-by-step.rst
Labels: level/task, type/bug

#6405 Remove deprecated plain text auth references for wodles
  source/cloud-security/amazon/services/prerequisites/considerations.rst
  source/cloud-security/amazon/services/prerequisites/credentials.rst
  source/cloud-security/azure/activity-services/prerequisites/credentials.rst
  source/user-manual/reference/ossec-conf/wodle-azure-logs.rst
  source/user-manual/reference/ossec-conf/wodle-s3.rst
Labels: aws, azure, level/task, type/maintenance
