Repository wazuh/wazuh-documentation, pull requests merged in 2024-12, with the labels that each got.

#8004 Offline setting clarification
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: level/task, type/enhancement

#8005 Offline setting clarification
  source/user-manual/reference/ossec-conf/vuln-detector.rst
Labels: level/task, type/enhancement

#8009 Fix Filebeat certificates directory creation
  source/user-manual/wazuh-server-cluster.rst
Labels: level/task, type/bug

#8016 Documentation updated
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: level/task, type/enhancement

#8017 Documentation updated
  source/user-manual/capabilities/vulnerability-detection/offline-update.rst
Labels: level/task, type/enhancement

#8021 Add Ubuntu 24.04 SCA to list of available SCAs
  source/user-manual/capabilities/sec-config-assessment/available-sca-policies.rst
Labels: level/task, type/change

#8027 Update screenshots of the configuration section
  source/images/kibana-app/features/query-configuration/configuration-section.png
  source/images/kibana-app/features/query-configuration/configuration-synchronized.png
  source/images/kibana-app/features/query-configuration/logcollector-query.png
Labels: level/task, type/enhancement

#8026 `Securing your Wazuh installation` API section is changing every password
  source/user-manual/user-administration/password-management.rst
Labels: level/task, type/change

#8002 Missing steps building Wazuh dashboard from sources
  source/_variables/replacements.py
  source/development/packaging/generate-dashboard-package.rst
Labels: level/task, type/enhancement

#8010 Fix the wazuh dashboard reference when cloning the repository
  source/_variables/replacements.py
  source/development/packaging/generate-dashboard-package.rst
Labels: level/task, type/change

#8048 `Securing your Wazuh installation` API section is changing every password
  source/installation-guide/wazuh-dashboard/step-by-step.rst
Labels: level/task, type/change

#8049 `Securing your Wazuh installation` API section is changing every password
  source/installation-guide/wazuh-dashboard/step-by-step.rst
Labels: level/task, type/change

#8044 Updated screenshots from System Inventory
  CHANGELOG.md
  source/images/manual/system-inventory/export-formatted.png
  source/images/manual/system-inventory/generate-report.png
  source/images/manual/system-inventory/inventory-data-network-tab.png
  source/images/manual/system-inventory/inventory-data-processes-tab.png
  source/images/manual/system-inventory/inventory-data-software-tab.png
  source/images/manual/system-inventory/inventory-data.png
Labels: level/task, type/change

#8014 Create a troubleshooting guide for vulnerability detector module
  source/_static/js/redirects.js
  source/user-manual/capabilities/vulnerability-detection/FAQ.rst
  source/user-manual/capabilities/vulnerability-detection/index.rst
  source/user-manual/capabilities/vulnerability-detection/known-issues.rst
  source/user-manual/capabilities/vulnerability-detection/troubleshooting.rst
Labels: level/task, type/enhancement
