Repository wazuh/wazuh-documentation, pull requests merged in 2024-11, with the labels that each got.

#7960 Fix log sample in sibling decoders section
  source/user-manual/ruleset/decoders/sibling-decoders.rst
Labels: level/task, type/enhancement

#7942 Updated screenshots agent dashboard: inventory, stats, and configuration
  source/images/wazuh-dashboard/queries/filter-value.png
  source/images/wazuh-dashboard/queries/port-greater-than-value.png
  source/images/wazuh-dashboard/queries/port-less-than-value.png
  source/images/wazuh-dashboard/queries/port-ranges.png
  source/images/wazuh-dashboard/queries/protocol-not-ipv6.png
  source/images/wazuh-dashboard/queries/wildcards-not-supported.png
  source/user-manual/wazuh-dashboard/queries.rst
Labels: level/task, type/change

#7944 Identify and update references new agent management section
  source/cloud-service/getting-started/enroll-agents.rst
  source/compliance/tsc/common-criteria/cc6.1.rst
  source/images/wazuh-dashboard/navigating/agents-management.png
  source/images/wazuh-dashboard/navigating/server-management.png
  source/installation-guide/wazuh-agent/index.rst
  source/user-manual/agent/agent-enrollment/enrollment-methods/via-agent-configuration/linux-endpoint.rst
  source/user-manual/agent/agent-enrollment/enrollment-methods/via-agent-configuration/macos-endpoint.rst
  source/user-manual/agent/agent-enrollment/enrollment-methods/via-agent-configuration/windows-endpoint.rst
  source/user-manual/agent/agent-enrollment/enrollment-methods/via-manager-API/importing-the-key.rst
  source/user-manual/agent/agent-enrollment/requirements.rst
  source/user-manual/agent/agent-enrollment/security-options/agent-identity-verification.rst
  source/user-manual/agent/agent-enrollment/security-options/manager-identity-verification.rst
  source/user-manual/agent/agent-enrollment/security-options/using-password-authentication.rst
  source/user-manual/agent/agent-management/agent-connection.rst
  source/user-manual/agent/agent-management/listing/wazuh-dashboard.rst
  source/user-manual/agent/agent-management/query-configuration.rst
  source/user-manual/capabilities/command-monitoring/command-output-analysis.rst
  source/user-manual/user-administration/rbac.rst
  source/user-manual/wazuh-dashboard/navigating-the-wazuh-dashboard.rst
  source/user-manual/wazuh-indexer/wazuh-indexer-indices.rst
Labels: level/task, type/change

#7961 Update documentation to build Wazuh dashboard package
  source/development/packaging/generate-dashboard-package.rst
Labels: level/task, type/change

#7946 Remove VirusTotal references
  CHANGELOG.md
  source/compliance/hipaa/malware-detection.rst
  source/compliance/nist/malware-detection.rst
  source/getting-started/index.rst
  source/images/getting-started/endpoints-summary.png
  source/images/getting-started/virustotal.png
  source/proof-of-concept-guide/detect-remove-malware-virustotal.rst
  source/user-manual/capabilities/file-integrity/use-cases/detecting-malware-persistence-technique.rst
  source/user-manual/capabilities/malware-detection/virus-total-integration.rst
Labels: level/task, type/change

#7975 Update malware detection documentation to include virustotal
  source/images/ansible/wazuh-dashboard-main.png
  source/images/getting-started/endpoint-security-modules.png
  source/images/getting-started/malware-detection.png
  source/images/wazuh-dashboard/navigating/endpoint-security.png
Labels: level/task, type/change

#7976 Update inventory page screenshots
  source/compliance/tsc/common-criteria/cc6.1.rst
  source/images/compliance/nist/inventory-data.png
  source/images/compliance/pci/processes-are-running-on-a-specific-endpoint-01.png
  source/images/compliance/pci/processes-are-running-on-a-specific-endpoint-02.png
  source/images/compliance/pci/processes-are-running-on-a-specific-endpoint-03.png
  source/images/compliance/tsc/common-criteria/agent-inventory-data.png
  source/images/getting-started/agents-monitoring.png
  source/images/getting-started/use-cases/it-hygiene/inventory-data-dashboard.png
  source/images/getting-started/use-cases/it-hygiene/inventory-data-download.png
  source/images/getting-started/use-cases/regulatory-compliance/tsc-cc-compliance.png
  source/images/manual/system-inventory/download-csv.png
  source/images/manual/system-inventory/export-formatted.png
  source/images/manual/system-inventory/generate-report.png
  source/images/manual/system-inventory/inventory-data-network-tab.png
  source/images/manual/system-inventory/inventory-data-processes-tab.png
  source/images/manual/system-inventory/inventory-data-software-tab.png
  source/images/manual/system-inventory/inventory-data-tab.png
  source/images/manual/system-inventory/inventory-data.png
  source/user-manual/capabilities/system-inventory/generating-system-inventory-reports.rst
  source/user-manual/capabilities/system-inventory/viewing-system-inventory-data.rst
Labels: level/task, type/change

#7978 Change the Python version and `urllib3` to `1.26.20`
  source/proof-of-concept-guide/monitoring-docker.rst
  source/user-manual/capabilities/container-security/monitoring-docker.rst
Labels: level/task, type/bug

#7979 Updated images in FIM PoC
  CHANGELOG.md
  source/images/poc/fim-alerts-ubuntu.png
  source/images/poc/fim-alerts-windows.png
Labels: level/task, type/change

#7994 Add Puppet manifest description
  source/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.rst
Labels: level/task, type/enhancement

#7995 Change all migrated wazuh-packages references of agent packages
  source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst
  source/development/packaging/generate-aix-package.rst
  source/development/packaging/generate-hpux-package.rst
  source/development/packaging/generate-osx-package.rst
  source/development/packaging/generate-sol-package.rst
  source/user-manual/agent/agent-management/remote-upgrading/wpk-files/create-custom-wpk.rst
Labels: level/task, type/change
